// Catálogo "¿Cómo hago…?" (guías paso a paso de cada acción) y "Me trabé"
// (soluciones a los atascos típicos) — por rol. Lo consume el botón de ayuda
// flotante y el centro de ayuda. Todo con lenguaje de la plataforma y rutas reales.
import type { TourRole } from '@/lib/tour-content'

export type HowTo = {
  id: string
  title: string
  time: string
  steps: string[]
  href?: string
  cta?: string
}

export type Trouble = {
  id: string
  q: string
  /** por qué pasa */
  why: string
  /** qué hacer */
  fix: string
  href?: string
  hrefLabel?: string
}

export const HOWTOS: Record<TourRole, HowTo[]> = {
  cliente: [
    {
      id: 'publicar',
      title: 'Publicar un trabajo para recibir presupuestos',
      time: '3 min',
      steps: [
        'Entrá a Panel → Publicar trabajo.',
        'Escribí qué necesitás (cuanto más claro, mejores presupuestos) y sumá fotos del lugar o del problema.',
        'Elegí tu zona y un presupuesto estimado: es una referencia, no un precio final.',
        'Revisá el resumen y publicá. Tu publicación sale gratis a la bolsa de trabajos.',
        'Esperá los presupuestos: te llega una notificación por cada uno.',
      ],
      href: '/panel/cliente/publicar',
      cta: 'Ir a publicar',
    },
    {
      id: 'comparar',
      title: 'Comparar presupuestos y elegir profesional',
      time: '2 min',
      steps: [
        'Entrá a Panel → Mis trabajos y abrí tu publicación.',
        'Mirá cada presupuesto: precio, plazo y el mensaje del profesional.',
        'Si tenés dudas, tocá su nombre: ves sus reseñas, obras y si está verificado. Podés chatear sin compromiso.',
        'Cuando decidas, aceptá el presupuesto: se crea el proyecto y el profesional recibe tu brief.',
      ],
      href: '/panel/cliente/trabajos',
      cta: 'Ver mis trabajos',
    },
    {
      id: 'contratar-directorio',
      title: 'Contratar directo desde el directorio',
      time: '4 min',
      steps: [
        'Entrá al Directorio: está ordenado de mejor a peor reputación, con filtros por rubro y precio.',
        'Abrí la tarjeta del profesional que te guste: reseñas con fotos, obras hechas y verificación.',
        'Tocá Contratar: un asistente de 4 pasos te pide qué necesitás (con fotos), cuándo y dónde, y presupuesto estimado.',
        '¿Ya lo publicaste? Arriba del primer paso elegí tu trabajo en "¿Es para algo que ya publicaste?" y se cargan sus datos (los podés cambiar). Si no, dejá "No, lo escribo ahora".',
        'Confirmá: se crea el proyecto y el profesional recibe todo el brief al instante. Si elegiste un trabajo publicado, queda en proceso: si ese profesional te había ofertado, se acepta su oferta; las demás ofertas se rechazan y les avisamos.',
      ],
      href: '/panel/cliente/directorio',
      cta: 'Abrir directorio',
    },
    {
      id: 'seguir-obra',
      title: 'Seguir la obra: etapas, materiales y acuerdo',
      time: '1 min',
      steps: [
        'Entrá a Panel → Proyectos y abrí tu proyecto.',
        'Seguí las etapas que marca tu profesional y mirá los materiales que propone, con precios reales de proveedores.',
        'Aprobá o rechazá cada material propuesto: solo los aprobados se compran.',
        'La tarjeta "¿Quién paga los materiales?" muestra el acuerdo siempre: si los adelanta el profesional, van en su factura; si no, pagás al proveedor directo.',
        'Cuando la obra está terminada (etapa Ejecución o Revisión), tocá «Finalizar obra»: solo vos podés darla por terminada, y ahí se activan las reseñas.',
      ],
      href: '/panel/cliente/proyectos',
      cta: 'Ver mis proyectos',
    },
    {
      id: 'fechas-cliente',
      title: 'Acordar las fechas del trabajo',
      time: '1 min',
      steps: [
        'Cuando el presupuesto queda aprobado, tu profesional te propone inicio, fin estimado y horario de cada día (o todo el día): te llega un aviso.',
        'Abrí el proyecto: en "Fechas del trabajo" tocá Aceptar fechas, Proponer otras (con otro horario, si querés) o Rechazar (con el motivo, si querés).',
        'Si el profesional ya tiene ese horario ocupado con otro trabajo acordado, HomIA te lo dice y no deja confirmarlo: elegí otro día u horario.',
        'Si después necesitás moverlas, tocá "Pedir reprogramar": hasta que el profesional responda, siguen las fechas acordadas.',
        'Antes de contratar, en el perfil del profesional mirá su Disponibilidad: días libres, con lugar o completos; tocá un día para ver qué horarios tiene ocupados y cuáles libres.',
      ],
      href: '/panel/cliente/proyectos',
      cta: 'Ver mis proyectos',
    },
    {
      id: 'pagar-factura',
      title: 'Pagar una factura (Mercado Pago o efectivo)',
      time: '2 min',
      steps: [
        'Entrá a Panel → Facturas (o al detalle del proyecto) y abrí la factura pendiente.',
        'Elegí el método: Pagar con Mercado Pago (el dinero va directo al profesional y se suma el cargo de servicio HomIA del 1%) o Efectivo (sin cargo).',
        'Si tu profesional todavía no conectó Mercado Pago, la factura se paga en efectivo: la pantalla te lo avisa.',
        'Con efectivo: el acuerdo queda registrado y tu profesional lo confirma cuando recibe el dinero. Podés cancelar el acuerdo antes y cambiar de método.',
        'Descargá el comprobante con el botón PDF cuando quieras.',
      ],
      href: '/panel/cliente/facturas',
      cta: 'Ver facturas',
    },
    {
      id: 'pagar-proveedor',
      title: 'Pagar los materiales al proveedor',
      time: '2 min',
      steps: [
        'Si el proyecto usa el modo "el cliente paga al proveedor", tus materiales se cobran por separado de la factura del profesional.',
        'En el detalle del proyecto, buscá la sección Pagos a proveedores.',
        'Cada proveedor emite su cobro por los materiales aprobados: lo pagás con Mercado Pago (+1% de cargo de servicio HomIA) o acordás efectivo sin cargo.',
        'El proveedor confirma el efectivo al recibirlo y todo queda registrado.',
      ],
      href: '/panel/cliente/proyectos',
      cta: 'Ir a proyectos',
    },
    {
      id: 'carrito',
      title: 'Comprar materiales con el carrito',
      time: '3 min',
      steps: [
        'En Materiales (o en la búsqueda) tocá «Agregar al carrito» en cada producto con stock, o «Reservar» (lo que no tiene stock solo se reserva). Pueden ser de proveedores distintos.',
        'Abrí el carrito (ícono de arriba): los productos están agrupados por proveedor; ajustá cantidades o sacá lo que no va.',
        'Tocá «Confirmar pedido» y elegí producto por producto si lo comprás o lo reservás. Comprar (con stock) no necesita aprobación: el stock queda reservado al confirmar. Reservar lo aprueba el proveedor.',
        'En Mis pedidos pagá tus compras en las próximas 24 h: Mercado Pago (+1% de cargo de servicio) o efectivo al retirar (7 días para retirar). Tus reservas las pagás cuando el proveedor las aprueba (48 h para retirar).',
        'Retirás, el proveedor marca la entrega y calificás tu compra.',
      ],
      href: '/panel/cliente/pedidos',
      cta: 'Ver mis pedidos',
    },
    {
      id: 'sobrantes',
      title: 'Devolver materiales que sobraron',
      time: '3 min',
      steps: [
        'Si fueron materiales de una obra, entrá al proyecto → Sobrantes; si fue una compra tuya, entrá al pedido en Mis pedidos.',
        'Cargá cada sobrante con foto, cantidad y cómo está (sin abrir o abierto sin usar). Tenés hasta 30 días desde el pago.',
        'Se lo devolvés a quien te lo cobró: el proveedor si le pagaste a él, o tu profesional si te lo cobró en su factura. Acepta todo o algunos ítems.',
        'Se lo entregás y marca recibido. Si pagaste con Mercado Pago, el reembolso vuelve solo a tu medio de pago (sin el 1% del cargo de servicio); si fue en efectivo, te lo devuelve en mano y tocás «Recibí el reembolso».',
      ],
      href: '/panel/cliente/proyectos',
      cta: 'Ir a proyectos',
    },
    {
      id: 'resena',
      title: 'Dejar una reseña (a quién, dónde y cuándo)',
      time: '2 min',
      steps: [
        'Las reseñas se activan recién cuando el proyecto finaliza: es la garantía de que son de obras reales.',
        'Entrá al detalle del proyecto finalizado: la sección Reseñas aparece activa.',
        'Calificá a tu profesional (estrellas, comentario y hasta 4 fotos) y a cada proveedor que te vendió materiales.',
        'Las compras de materiales se califican desde Mis pedidos, cuando ya las retiraste.',
        'Tu reseña se publica con tu nombre y recalcula la reputación del destinatario al instante.',
      ],
      href: '/panel/cliente/proyectos',
      cta: 'Ir a mis proyectos',
    },
    {
      id: 'chatear',
      title: 'Chatear con profesional o proveedor',
      time: '1 min',
      steps: [
        'Entrá a Panel → Mensajes: tu bandeja estilo chat.',
        'Para empezar una conversación nueva, tocá un profesional o proveedor desde el directorio o su perfil y usá el botón de contacto.',
        'Por tu seguridad, ellos nunca pueden escribirte primero: solo responden.',
        'Toda la conversación queda registrada en la plataforma.',
      ],
      href: '/panel/cliente/mensajes',
      cta: 'Abrir mensajes',
    },
    {
      id: 'verificar',
      title: 'Verificar tu identidad con el DNI',
      time: '3 min',
      steps: [
        'Entrá a Panel → Verificación.',
        'Subí una foto clara del FRENTE y otra del DORSO de tu DNI.',
        'La IA analiza que el documento sea real y legible: en minutos ves el resultado.',
        'Cuando aprobás, tu perfil muestra el check "Verificado" para todos.',
      ],
      href: '/panel/cliente/verificacion',
      cta: 'Verificar ahora',
    },
    {
      id: 'pdf',
      title: 'Descargar una factura en PDF',
      time: '10 seg',
      steps: [
        'Entrá a Panel → Facturas, o al detalle del proyecto que la generó.',
        'Tocá el botón PDF de la factura: se descarga al instante con formato profesional.',
        'Las facturas pagadas y pendientes se pueden descargar igual.',
      ],
      href: '/panel/cliente/facturas',
      cta: 'Ver facturas',
    },
    {
      id: 'mi-cuenta',
      title: 'Tus datos, avisos por mail y tu cuenta',
      time: '2 min',
      steps: [
        'Entrá a Panel → Mi perfil.',
        'Cambiá tus datos: tu nombre, el país y el número de celular (sirve cualquier país), dirección y ciudad. Tocá Guardar.',
        'En «Email y celular» mirá si tu email dice Verificado. Si dice Sin verificar, tocá «Verificar ahora» y escribí el código de 6 números que te llega por mail.',
        'Más abajo, «Recibir avisos por mail» prende o apaga los mails de los eventos importantes (los mensajes del chat nunca llegan por mail).',
        'Al final está «Eliminar mi cuenta»: escribís ELIMINAR y tu contraseña. Si tenés algo abierto, la app te dice qué cerrar primero. No se puede deshacer.',
      ],
      href: '/panel/cliente/perfil',
      cta: 'Ir a Mi perfil',
    },
    {
      id: 'sugerencia',
      title: 'Mandar una sugerencia, queja o reportar un problema',
      time: '2 min',
      steps: [
        'Entrá a Panel → Sugerencias (en el celular, dentro de «Más») y tocá «Nueva sugerencia».',
        'Elegí el tipo (Sugerencia, Queja, Mejora, Oportunidad, Problema técnico u Otro) y sobre qué parte de HomIA es.',
        'Escribí un título y qué pasó, qué esperabas y qué te gustaría. Si querés, sumá hasta 4 fotos o capturas.',
        'Enviá. En «Mis envíos» ves el estado y la respuesta del equipo, que también te llega por notificación y por mail.',
      ],
      href: '/panel/cliente/sugerencias',
      cta: 'Ir a Sugerencias',
    },
  ],

  profesional: [
    {
      id: 'presupuestar',
      title: 'Enviar un presupuesto a un trabajo publicado',
      time: '4 min',
      steps: [
        'Entrá a Panel → Bolsa de trabajos y filtrá por tu rubro y zona.',
        'Abrí el trabajo: leé el brief con fotos y mirá si hay preguntas por chat.',
        'Tocá Enviar presupuesto: precio, plazo y un mensaje que explique cómo lo vas a resolver.',
        'Seguí su estado en Mis ofertas. Si te lo aceptan, el proyecto se crea solo.',
      ],
      href: '/panel/profesional/bolsa',
      cta: 'Ir a la bolsa',
    },
    {
      id: 'gestionar-proyecto',
      title: 'Gestionar la obra por etapas',
      time: '2 min',
      steps: [
        'Entrá a Panel → Proyectos y abrí tu obra.',
        'Cotizá la mano de obra: sin eso el proyecto no sale de Presupuesto.',
        'Tocá «Avanzar a …» para pasar de etapa (Materiales, Ejecución, Revisión). Las etapas solo van hacia adelante y el cliente lo ve en tiempo real.',
        'Contale el avance al cliente por Mensajes: todo queda por escrito.',
        'Cuando terminás, dejala en Revisión: la obra la finaliza el cliente, y ahí se activan las reseñas.',
      ],
      href: '/panel/profesional/proyectos',
      cta: 'Ver proyectos',
    },
    {
      id: 'calendario',
      title: 'Proponer fechas y usar tu calendario',
      time: '2 min',
      steps: [
        'Con el presupuesto aprobado, abrí el proyecto y en "Fechas del trabajo" tocá Proponer fechas: inicio, fin estimado, horario de cada día (por ejemplo de 07:00 a 12:00, o todo el día) y una nota si hace falta.',
        'Podés tener varios trabajos el mismo día en horarios distintos (07:00–12:00 en uno y 14:00–19:00 en otro). Si el horario choca con otro trabajo ya acordado, HomIA no te deja; si choca con otra propuesta sin confirmar, solo te avisa.',
        'El cliente las acepta, las rechaza o te propone otras; si te propone otras, vos las aceptás, rechazás o contraproponés.',
        'En Panel → Calendario ves el mes con cuántos trabajos tenés cada día y si está completo o con lugar; tocá un día para ver la agenda por hora con tus huecos libres. En "Mi jornada" elegís tu horario habitual (por defecto de 06:00 a 18:00).',
        'Tus clientes y proveedores ven en tu perfil qué días estás libre, con lugar o completo, y qué horarios tenés ocupados, sin detalles de cada trabajo.',
      ],
      href: '/panel/profesional/calendario',
      cta: 'Ver mi calendario',
    },
    {
      id: 'materiales-comparar',
      title: 'Proponer materiales comparando precios',
      time: '3 min',
      steps: [
        'En el detalle del proyecto, entrá a la sección Materiales.',
        'Compará el mismo material entre proveedores: precio, stock y distancia.',
        'Elegí el mejor y proponelo: el cliente aprueba o rechaza cada propuesta.',
        'Solo los materiales aprobados se compran; nunca compres sin aprobación.',
      ],
      href: '/panel/profesional/proyectos',
      cta: 'Ir a proyectos',
    },
    {
      id: 'quien-paga',
      title: 'Definir quién paga los materiales',
      time: '1 min',
      steps: [
        'En el detalle del proyecto está la tarjeta "¿Quién paga los materiales?".',
        'Modo 1 — los adelantás vos: los comprás y los cobrás junto con la mano de obra en tu factura.',
        'Modo 2 — el cliente paga al proveedor: cada proveedor emite su cobro directo; tu factura va solo con mano de obra.',
        'El cambio queda notificado a la contraparte y lo ven los dos siempre.',
      ],
      href: '/panel/profesional/proyectos',
      cta: 'Ir a proyectos',
    },
    {
      id: 'devoluciones-pro',
      title: 'Devoluciones de sobrantes (clientes y proveedores)',
      time: '3 min',
      steps: [
        'Si le cobraste los materiales al cliente en tu factura, sus devoluciones de sobrantes te llegan a vos: Panel → Devoluciones → De mis clientes.',
        'Aceptá todo o algunos ítems (con el monto a devolver) o rechazá con un motivo. Cuando te los entregue, marcá recibido.',
        'Si te pagó la factura con Mercado Pago, el reembolso sale solo de tu cuenta; si fue en efectivo, se lo devolvés en mano y tocás "Ya lo reembolsé en efectivo".',
        'Si querés devolverle esos materiales (o los que te sobraron) a tu proveedor: en el proyecto, Sobrantes → Pedir devolución a …. Como le pagaste por fuera de HomIA, te devuelve la plata por fuera y vos confirmás que la recibiste.',
      ],
      href: '/panel/profesional/devoluciones',
      cta: 'Ir a Devoluciones',
    },
    {
      id: 'facturar-cobrar',
      title: 'Emitir factura y cobrar',
      time: '3 min',
      steps: [
        'En el detalle del proyecto, tocá Emitir factura: incluye la mano de obra y, si los adelantaste vos, los materiales aprobados que todavía no facturaste. Hay una sola factura pendiente por proyecto a la vez.',
        'Si conectaste tu Mercado Pago en Cobros y el cliente paga por ahí, el dinero va directo a tu cuenta, sin comisión de HomIA.',
        'Si el cliente elige efectivo, vas a ver el acuerdo registrado: al recibir el dinero, tocá Confirmar cobro en efectivo (en el proyecto o en Cobros).',
        'Todo queda documentado: facturas descargables en PDF para vos y para el cliente.',
      ],
      href: '/panel/profesional/proyectos',
      cta: 'Ir a proyectos',
    },
    {
      id: 'cobrar-mp',
      title: 'Cobrar tus facturas con tu Mercado Pago',
      time: '2 min',
      steps: [
        'Entrá a Panel → Cobros (en el celular está en «Más»).',
        'Tocá «Conectar Mercado Pago» e ingresá con tu cuenta: volvés solo a Cobros, con la cuenta conectada.',
        'Desde ahí, cuando un cliente paga tu factura por Mercado Pago, el pago entra en tu cuenta por el 100% de la factura: el cargo de servicio HomIA del 1% lo paga el cliente. Mercado Pago lo libera según tus plazos y te descuenta su comisión.',
        'En la misma pantalla ves lo cobrado este mes, lo pendiente y todas tus facturas: descargás el PDF y, si el cliente te pagó en efectivo, tocás «Confirmar cobro en efectivo».',
        'Sin conexión, tus clientes solo pueden pagarte en efectivo (vos confirmás el cobro).',
      ],
      href: '/panel/profesional/cobros',
      cta: 'Ir a Cobros',
    },
    {
      id: 'obras',
      title: 'Cargar tus obras para vender más',
      time: '3 min',
      steps: [
        'Entrá a Panel → Mis obras.',
        'Sumá cada trabajo terminado con fotos reales: antes y después suma mucho. Las fotos del celular se suben de cualquier tamaño.',
        'Tus obras se ven en tu perfil público, y la cantidad de obras aparece en tu tarjeta del directorio.',
        'Si una obra ya no va, la eliminás desde la misma lista.',
      ],
      href: '/panel/profesional/obras',
      cta: 'Cargar obras',
    },
    {
      id: 'crm',
      title: 'Usar el CRM para seguir tus oportunidades',
      time: '2 min',
      steps: [
        'Entrá a Panel → CRM clientes: es un tablero con columnas (Consultas, Presupuesto enviado, En negociación, En obra, Cerrado / Facturado).',
        'Tocá «Nuevo trato» en una columna y sumá un trato con un nombre (por ejemplo, el cliente y el trabajo) y un monto estimado.',
        'Movelo de columna con las flechas a medida que avanza; si ya no va, borralo.',
        'Arriba ves cuánto suman tus tratos: así sabés qué tenés en camino.',
      ],
      href: '/panel/profesional/crm',
      cta: 'Abrir CRM',
    },
    {
      id: 'chats',
      title: 'Responder chats (y la regla del primero)',
      time: '1 min',
      steps: [
        'Entrá a Panel → Mensajes: toda tu bandeja con los no leídos marcados.',
        'Podés responder todas las conversaciones que quieras.',
        'La conversación nueva siempre la inicia el cliente: es la regla de confianza de HomIA.',
        'Respondé dentro del día: el cliente está comparando en ese momento.',
      ],
      href: '/panel/profesional/mensajes',
      cta: 'Abrir mensajes',
    },
    {
      id: 'verificar',
      title: 'Verificarte con el DNI',
      time: '3 min',
      steps: [
        'Entrá a Panel → Verificación.',
        'Subí foto clara del FRENTE y del DORSO de tu DNI.',
        'La IA valida el documento y tu perfil muestra el check "Verificado".',
        'Sin verificar figurás como "No verificado" ante todos: es gratis y tarda 2 minutos.',
      ],
      href: '/panel/profesional/verificacion',
      cta: 'Verificar ahora',
    },
    {
      id: 'retiro',
      title: 'Vincularte con un proveedor (cuenta de retiro)',
      time: '2 min',
      steps: [
        'Entrá a Panel → Cuentas de retiro.',
        'Ingresá el email del proveedor registrado en HomIA y un nombre para la cuenta (ej.: "Obra Palermo"). Queda pendiente hasta que el proveedor la activa.',
        'Con la vinculación activa, retirás materiales de su local a cuenta de tus proyectos. Si querés cortarla, la pausás.',
        'No es una cuenta bancaria: tus cobros llegan por Mercado Pago o efectivo desde tus facturas.',
      ],
      href: '/panel/profesional/vinculaciones',
      cta: 'Vincular',
    },
    {
      id: 'finanzas',
      title: 'Ver si tu trabajo deja ganancia (Finanzas)',
      time: '5 min',
      steps: [
        'Entrá a Panel → Finanzas. La primera vez te pide 3 datos para arrancar.',
        'Lo que pasa por HomIA se carga solo y dice «Automático · viene de HomIA»: tus facturas (facturado y cobrado por separado), los materiales que compraste en la app, las devoluciones y los subcontratos.',
        'En Movimientos sumá lo que hacés por fuera: trabajos cobrados por fuera, costos de cada trabajo, gastos fijos (los mensuales se cargan una vez), herramientas o vehículo (se reparten mes a mes), retiros, aportes y préstamos.',
        'Mirá Resultados (si ganás plata), Caja (cuánta plata tenés) y Balance (cuánto vale tu negocio). La pestaña Aprendé explica cada número. Podés exportar todo a Excel.',
      ],
      href: '/panel/profesional/finanzas',
      cta: 'Ir a Finanzas',
    },
    {
      id: 'comprar-materiales',
      title: 'Comprar materiales para vos (carrito)',
      time: '3 min',
      steps: [
        'Entrá a Panel → Materiales y buscá lo que necesitás: ves las ofertas de todos los proveedores con precio, stock y distancia.',
        'Tocá «Agregar al carrito» (con stock) o «Reservar» (lo que no tiene stock solo se reserva). Pueden ser de varios proveedores.',
        'Abrí el carrito (ícono de arriba), confirmá y elegí producto por producto si lo comprás o lo reservás.',
        'En Mis pedidos pagá tus compras en las próximas 24 h (Mercado Pago +1% o efectivo al retirar, con 7 días para retirar). Las reservas las pagás cuando el proveedor las aprueba.',
      ],
      href: '/panel/profesional/materiales',
      cta: 'Ir a Materiales',
    },
    {
      id: 'subcontratar',
      title: 'Subcontratar a otro profesional para una obra',
      time: '3 min',
      steps: [
        'Buscá al profesional en el Directorio y abrí su perfil.',
        'Tocá Contratar y, en «¿Es para algo que ya publicaste?», elegí uno de tus proyectos activos: se cargan sus datos (los podés cambiar).',
        'Confirmá: se crea un proyecto aparte entre vos y él, vinculado al tuyo. Tu cliente no lo ve.',
        'Lo seguís en Proyectos → «Profesionales que contrataste»: su cotización, el avance, el pago y la reseña, como cliente.',
      ],
      href: '/panel/profesional/directorio',
      cta: 'Abrir directorio',
    },
    {
      id: 'mi-cuenta',
      title: 'Tus datos, avisos por mail y tu cuenta',
      time: '2 min',
      steps: [
        'Entrá a Panel → Mi perfil.',
        'Cambiá tus datos: tus rubros, tu zona, tu descripción, tu foto, el país y el número de celular (sirve cualquier país), dirección y ciudad. Tocá Guardar.',
        'En «Email y celular» mirá si tu email dice Verificado. Si dice Sin verificar, tocá «Verificar ahora» y escribí el código de 6 números que te llega por mail.',
        'Más abajo, «Recibir avisos por mail» prende o apaga los mails de los eventos importantes (los mensajes del chat nunca llegan por mail).',
        'Al final está «Eliminar mi cuenta»: escribís ELIMINAR y tu contraseña. Si tenés algo abierto, la app te dice qué cerrar primero. No se puede deshacer.',
      ],
      href: '/panel/profesional/perfil',
      cta: 'Ir a Mi perfil',
    },
    {
      id: 'sugerencia',
      title: 'Mandar una sugerencia, queja o reportar un problema',
      time: '2 min',
      steps: [
        'Entrá a Panel → Sugerencias (en el celular, dentro de «Más») y tocá «Nueva sugerencia».',
        'Elegí el tipo (Sugerencia, Queja, Mejora, Oportunidad, Problema técnico u Otro) y sobre qué parte de HomIA es.',
        'Escribí un título y qué pasó, qué esperabas y qué te gustaría. Si querés, sumá hasta 4 fotos o capturas.',
        'Enviá. En «Mis envíos» ves el estado y la respuesta del equipo, que también te llega por notificación y por mail.',
      ],
      href: '/panel/profesional/sugerencias',
      cta: 'Ir a Sugerencias',
    },
  ],

  proveedor: [
    {
      id: 'cargar-stock',
      title: 'Publicar materiales en tu catálogo',
      time: '4 min',
      steps: [
        'Entrá a Panel → Stock y tocá para agregar un material.',
        'Buscalo en el catálogo (entiende errores de tipeo y plurales) y elegilo. Si no existe, tocá «Agregar «…» al catálogo con IA»: la IA escribe la descripción y se revisa que no esté repetido.',
        'Cargá tu precio, la cantidad disponible y, si querés, la marca y una foto (de cualquier tamaño).',
        'Tu stock aparece en Materiales, en las búsquedas y en tu perfil público.',
      ],
      href: '/panel/proveedor/stock',
      cta: 'Ir al stock',
    },
    {
      id: 'actualizar-stock',
      title: 'Actualizar precios y stock (tu vidriera)',
      time: '2 min',
      steps: [
        'Entrá a Panel → Stock y revisá los alertados "por agotar" y "agotados" del Inicio.',
        'Actualizá precio y cantidad: el stock viejo aleja a los compradores.',
        'El Inicio te avisa solo cuando algo está por agotarse.',
        'Stock actualizado = aparecer arriba en las comparaciones = vender más.',
      ],
      href: '/panel/proveedor/stock',
      cta: 'Actualizar stock',
    },
    {
      id: 'emitir-cobro',
      title: 'Emitir el cobro de tus materiales',
      time: '2 min',
      steps: [
        'Entrá a Panel → Cobros → pestaña «Cobros de proyectos»: ves los materiales aprobados listos para cobrar.',
        'Elegí el proyecto y emití el cobro agrupado por esos materiales.',
        'El cliente lo paga con Mercado Pago o acuerda efectivo.',
        'Emití apenas se aprueban los materiales: cuanto antes cobrás, mejor.',
      ],
      href: '/panel/proveedor/cobros',
      cta: 'Ir a cobros',
    },
    {
      id: 'ventas-pedidos',
      title: 'Compras y reservas del carrito',
      time: '2 min',
      steps: [
        'Entrá a Panel → Cobros → Ventas (pedidos): ves tu parte de cada pedido con todos sus productos.',
        'Las compras te llegan ya «Por pagar»: el stock está reservado y el cobro emitido, no tenés que aprobar nada. Preparalas. Si no podés cumplir, cancelá con un motivo (si ya estaba pagada por Mercado Pago, se le devuelve completa desde tu cuenta).',
        'Las reservas sí las aprobás: con stock, «Aprobar reserva» reserva todo junto y el cliente tiene 48 h. Sin stock, indicá «Disponible aproximadamente el…» y, cuando lo tengas, tocá «Ya lo tengo: disponible». Si no podés, rechazala con un motivo.',
        'El cliente paga por Mercado Pago (te paga el 100% de tu precio; el 1% de cargo de servicio lo paga él; Mercado Pago te descuenta su comisión) o en efectivo al retirar.',
        'Cuando retira, marcá «Entregado». Todo queda en la línea de tiempo del pedido.',
      ],
      href: '/panel/proveedor/cobros?tab=ventas',
      cta: 'Ir a Ventas',
    },
    {
      id: 'confirmar-efectivo',
      title: 'Confirmar un cobro en efectivo',
      time: '30 seg',
      steps: [
        'En Panel → Cobros, buscá el cobro "esperando pago en efectivo".',
        'Cuando el cliente te entrega el dinero, tocá Confirmar cobro.',
        'El sistema registra el pago y cierra el circuito para los dos.',
        'Nunca confirmes antes de recibir: el registro es la prueba del pago.',
      ],
      href: '/panel/proveedor/cobros',
      cta: 'Ir a cobros',
    },
    {
      id: 'vinculaciones',
      title: 'Vincular a un profesional (cuenta de retiro)',
      time: '2 min',
      steps: [
        'Entrá a Panel → Vinculaciones. Las que te piden los profesionales llegan pendientes: vos decidís si las activás.',
        'Para crear una vos, ingresá el email del profesional registrado en HomIA y un nombre para su cuenta de retiro.',
        'Con la vinculación activa, retira materiales de tu local a cuenta de un proyecto y después lo cobrás desde Cobros.',
        'No es una cuenta bancaria: para cobrar por Mercado Pago, conectalo desde Panel → Cobros.',
      ],
      href: '/panel/proveedor/vinculaciones',
      cta: 'Vincular',
    },
    {
      id: 'conectar-mp',
      title: 'Conectar tu Mercado Pago',
      time: '2 min',
      steps: [
        'Entrá a Panel → Cobros.',
        'Tocá «Conectar Mercado Pago» e ingresá con tu cuenta: autorizás a HomIA y volvés a Cobros con la cuenta conectada.',
        'Desde ahí tus clientes te pagan por Mercado Pago y el pago entra en tu cuenta por el 100% de tu precio (el 1% de cargo de servicio lo paga el cliente). Mercado Pago lo libera según tus plazos y te descuenta su comisión.',
        'Sin conexión, solo te pueden pagar en efectivo. Si la conexión vence, el botón dice «Volver a conectar».',
      ],
      href: '/panel/proveedor/cobros',
      cta: 'Ir a Cobros',
    },
    {
      id: 'devoluciones',
      title: 'Gestionar devoluciones de sobrantes',
      time: '3 min',
      steps: [
        'Entrá a Panel → Cobros → pestaña «Devoluciones».',
        'Revisá cada pedido (foto, cantidad y estado) y aceptá todo, algunos ítems (con el monto) o rechazá con un motivo. Si no respondés en 72 h te llega un recordatorio.',
        'Cuando te los traen, marcá recibido: vuelven a tu stock. Si te pagaron con Mercado Pago, el reembolso sale solo de tu cuenta; si fue en efectivo, lo devolvés en mano y lo marcás.',
        'Si te lo pide un profesional (le vendiste por fuera de HomIA), marcás cómo le devolviste la plata: efectivo, transferencia o saldo a favor.',
      ],
      href: '/panel/proveedor/cobros',
      cta: 'Ir a Cobros',
    },
    {
      id: 'plan',
      title: 'Elegir o cambiar tu plan',
      time: '2 min',
      steps: [
        'Entrá a Panel → Mi plan: ves cuántos días de prueba te quedan (son 14).',
        'Tocá Elegir Básico ($50.000/mes) o Pasarme a PRO ($100.000/mes): te lleva a Mercado Pago para autorizar el cobro mensual.',
        'Al volver, la app confirma el pago (puede tardar hasta un minuto). Si cambiás de plan, la suscripción anterior se cancela sola cuando se confirma la nueva.',
        'Para cancelar, hacelo desde tu cuenta de Mercado Pago: en la app no hay botón. Sin plan activo dejás de aparecer, pero tus datos, reseñas y vinculaciones se conservan.',
      ],
      href: '/panel/proveedor/plan',
      cta: 'Ir a Mi plan',
    },
    {
      id: 'marca-pro',
      title: 'Poner tu logo y tu marca en la portada (PRO)',
      time: '2 min',
      steps: [
        'Con el plan PRO activo, entrá a Panel → Mi perfil → «Tu marca en la home».',
        'Subí tu logo (PNG, WEBP o JPG) y, si querés, una frase de hasta 60 caracteres y un color.',
        'Tocá «Guardar mi marca»: aparece en la cinta de la portada. Si no subís logo, se usa tu foto de perfil.',
      ],
      href: '/panel/proveedor/perfil',
      cta: 'Ir a Mi perfil',
    },
    {
      id: 'finanzas',
      title: 'Ver si tu negocio gana plata (Finanzas)',
      time: '5 min',
      steps: [
        'Entrá a Panel → Finanzas. La primera vez te pide 3 datos para arrancar.',
        'Tus ventas por HomIA y las devoluciones se cargan solas y dicen «Automático · viene de HomIA».',
        'En Resultados → «Cargar costos» poné lo que te cuesta cada producto (o un margen estimado para los que no tengan dato).',
        'En Movimientos sumá gastos, compras de mercadería y lo que vendés en el mostrador. Mirá Resultados, Caja y Balance; la pestaña Aprendé explica cada número. Podés exportar todo a Excel.',
      ],
      href: '/panel/proveedor/finanzas',
      cta: 'Ir a Finanzas',
    },
    {
      id: 'crm',
      title: 'Usar el CRM para seguir tus tratos',
      time: '2 min',
      steps: [
        'Entrá a Panel → CRM: es un tablero con columnas (Nuevos contactos, Cotizando, Compra en curso, Cliente recurrente).',
        'Sumá un trato con un nombre, un monto estimado y con quién es.',
        'Movelo de columna a medida que avanza; si ya no va, borralo.',
      ],
      href: '/panel/proveedor/crm',
      cta: 'Abrir CRM',
    },
    {
      id: 'chats',
      title: 'Responder chats de clientes y profesionales',
      time: '1 min',
      steps: [
        'Entrá a Panel → Mensajes: tu bandeja con los no leídos marcados.',
        'La conversación nueva siempre la inicia el cliente; vos respondés todo lo que llega.',
        'Respondé rápido: el profesional suele estar comparando proveedores en ese momento.',
        'Los precios acordados por chat quedan registrados en la plataforma.',
      ],
      href: '/panel/proveedor/mensajes',
      cta: 'Abrir mensajes',
    },
    {
      id: 'verificar',
      title: 'Verificarte con el DNI',
      time: '3 min',
      steps: [
        'Entrá a Panel → Verificación.',
        'Subí foto clara del FRENTE y del DORSO de tu DNI.',
        'La IA valida el documento y tu perfil muestra el check "Verificado".',
        'Entre proveedores con precio parecido, el cliente elige al verificado.',
      ],
      href: '/panel/proveedor/verificacion',
      cta: 'Verificar ahora',
    },
    {
      id: 'reputacion',
      title: 'Construir reputación que vende',
      time: 'en el día a día',
      steps: [
        'Entregá a tiempo y en completo: los clientes reseñan con fotos la entrega real.',
        'Cuidá el orden del directorio: se ordena por reseñas positivas.',
        'Respondé los chats rápido y por escrito: todo queda registrado.',
        'Sin DNI verificado figurás como "No verificado": verificá tu identidad.',
      ],
      href: '/panel/proveedor/directorio',
      cta: 'Ver mi tarjeta',
    },
    {
      id: 'mi-cuenta',
      title: 'Tus datos, avisos por mail y tu cuenta',
      time: '2 min',
      steps: [
        'Entrá a Panel → Mi perfil.',
        'Cambiá tus datos: los datos del negocio (nombre, tipo, CUIT, dirección), tu foto, el país y el número de celular (sirve cualquier país), dirección y ciudad. Tocá Guardar.',
        'En «Email y celular» mirá si tu email dice Verificado. Si dice Sin verificar, tocá «Verificar ahora» y escribí el código de 6 números que te llega por mail.',
        'Más abajo, «Recibir avisos por mail» prende o apaga los mails de los eventos importantes (los mensajes del chat nunca llegan por mail).',
        'Al final está «Eliminar mi cuenta»: escribís ELIMINAR y tu contraseña. Si tenés algo abierto, la app te dice qué cerrar primero. No se puede deshacer.',
      ],
      href: '/panel/proveedor/perfil',
      cta: 'Ir a Mi perfil',
    },
    {
      id: 'sugerencia',
      title: 'Mandar una sugerencia, queja o reportar un problema',
      time: '2 min',
      steps: [
        'Entrá a Panel → Sugerencias (en el celular, dentro de «Más») y tocá «Nueva sugerencia».',
        'Elegí el tipo (Sugerencia, Queja, Mejora, Oportunidad, Problema técnico u Otro) y sobre qué parte de HomIA es.',
        'Escribí un título y qué pasó, qué esperabas y qué te gustaría. Si querés, sumá hasta 4 fotos o capturas.',
        'Enviá. En «Mis envíos» ves el estado y la respuesta del equipo, que también te llega por notificación y por mail.',
      ],
      href: '/panel/proveedor/sugerencias',
      cta: 'Ir a Sugerencias',
    },
  ],
}

export const TROUBLES: Record<TourRole, Trouble[]> = {
  cliente: [
    {
      id: 'sin-presupuestos',
      q: 'No me llegan presupuestos',
      why: 'Lo más común: publicación sin fotos, sin presupuesto estimado o con muy poco detalle. Los profesionales presupuestan mejor (y más rápido) cuanto más les mostrás.',
      fix: 'Una publicación no se edita: si le faltaban fotos, zona o un presupuesto estimado realista, cerrala desde Mis trabajos y publicá una nueva más completa. Además, podés ir al Directorio, elegir profesionales con buena reputación y escribirles o contratarlos directo (en Contratar elegís tu trabajo publicado y se cargan sus datos).',
      href: '/panel/cliente/trabajos',
      hrefLabel: 'Ir a mis trabajos',
    },
    {
      id: 'pro-no-responde',
      q: 'El profesional no me responde',
      why: 'Le llega una notificación por cada mensaje, pero nadie puede obligarlo a contestar. Por eso HomIA te da siempre varias opciones con reputación a la vista.',
      fix: 'Revisá en Mensajes que tu mensaje se haya enviado. Si no responde en el día, volvé al Directorio y contactá otros profesionales bien calificados: comparar 2-3 opciones sube mucho la respuesta.',
      href: '/panel/cliente/directorio',
      hrefLabel: 'Ver otros profesionales',
    },
    {
      id: 'no-puedo-resenar',
      q: 'No encuentro dónde dejar la reseña',
      why: 'La sección Reseñas se activa recién cuando el proyecto finaliza, y solo para quienes participaron de esa obra. Es la garantía de que las reseñas son de trabajos reales.',
      fix: 'Entrá al detalle del proyecto: si la obra sigue activa, verás la sección bloqueada con la explicación. Cuando esté terminada (etapa Ejecución o Revisión), tocá «Finalizar obra»: solo vos podés hacerlo, y ahí la reseña se activa (estrellas, comentario y fotos) para tu profesional y cada proveedor. Las compras de materiales se califican desde Mis pedidos.',
      href: '/panel/cliente/proyectos',
      hrefLabel: 'Ver mis proyectos',
    },
    {
      id: 'pago-no-acredita',
      q: 'El pago no se acredita',
      why: 'Con Mercado Pago, la acreditación puede demorar unos minutos y se refleja sola en Facturas. Con efectivo, la factura queda pagada recién cuando el profesional confirma que lo recibió.',
      fix: 'Si pagaste con Mercado Pago, esperá unos minutos y recargá: el estado se actualiza solo. Si acordaste efectivo, avisale a tu profesional (por chat, queda registrado) y él confirma el cobro desde su panel. Podés cancelar el acuerdo de efectivo y pagar con Mercado Pago si preferís.',
      href: '/panel/cliente/facturas',
      hrefLabel: 'Ver mis facturas',
    },
    {
      id: 'me-equivoque',
      q: 'Me equivoqué en lo que publiqué',
      why: 'A veces el detalle cambia después de publicar (medidas, fechas, alcance del trabajo).',
      fix: 'Una publicación no se puede editar. Entrá a Mis trabajos, cerrala y publicá una nueva con los datos correctos. Si ya recibiste presupuestos, contale el cambio por chat a los profesionales que te ofertaron.',
      href: '/panel/cliente/trabajos',
      hrefLabel: 'Ir a mis trabajos',
    },
    {
      id: 'cobro-proveedor',
      q: 'Me llegó un cobro de un proveedor y no lo esperaba',
      why: 'Si el proyecto usa el modo "el cliente paga al proveedor", los materiales se cobran aparte de la factura del profesional: es el acuerdo visible en la tarjeta "¿Quién paga los materiales?".',
      fix: 'En el detalle del proyecto, revisá la tarjeta del acuerdo y los materiales que aprobaste: el cobro corresponde exactamente a esos materiales. Si algo no coincide, chateá con el profesional antes de pagar: todo queda registrado.',
      href: '/panel/cliente/proyectos',
      hrefLabel: 'Revisar el proyecto',
    },
    {
      id: 'email-codigo',
      q: 'No me llega el código por mail',
      why: 'El código de 6 números vence en 10 minutos y a veces el mail cae en spam o en promociones.',
      fix: 'Revisá spam y promociones. Si no está, esperá un minuto y pedí otro. Revisá que el email esté bien escrito. Si ya tenés cuenta y tu email dice Sin verificar, en Mi perfil → Email y celular tocá «Verificar ahora».',
      href: '/panel/cliente/perfil',
      hrefLabel: 'Ir a Mi perfil',
    },
    {
      id: 'no-aparece-directorio',
      q: 'No encuentro a alguien en el directorio',
      why: 'El directorio ordena por reputación y muestra perfiles con datos completos. Un profesional sin verificación, sin obras o sin reseñas queda más abajo o puede ser difícil de hallar.',
      fix: 'Usá los filtros por rubro y precio, y probá buscar por parte del nombre. Si igual no aparece, es probable que su perfil esté incompleto: elegí alternativas mejor documentadas.',
      href: '/panel/cliente/directorio',
      hrefLabel: 'Abrir directorio',
    },
  ],

  profesional: [
    {
      id: 'sin-trabajos',
      q: 'No recibo invitaciones ni aceptan mis presupuestos',
      why: 'Los clientes comparan tres cosas a simple vista: reputación (reseñas), verificación (check verde) y velocidad de respuesta. Un perfil sin obras ni DNI compite con una mano atada.',
      fix: 'Verificá tu identidad con el DNI, cargá tus obras con fotos y respondé presupuestos el mismo día. Mirá los presupuestos aceptados de otros: ajustá precio y presentación al contexto real del cliente.',
      href: '/panel/profesional/verificacion',
      hrefLabel: 'Verificar mi identidad',
    },
    {
      id: 'cliente-no-responde',
      q: 'El cliente no me responde',
      why: 'Los clientes suelen comparar varios presupuestos antes de decidir. Además, la conversación nueva siempre la inicia el cliente: es la regla de confianza de HomIA.',
      fix: 'Hacé un seguimiento amable por chat (queda registrado). Si no responde, retomalo desde el CRM con notas del caso y foco en los trabajos con señales claras: mensajes leídos y preguntas son buena señal de compra.',
      href: '/panel/profesional/crm',
      hrefLabel: 'Registrar seguimiento',
    },
    {
      id: 'no-puedo-cobrar',
      q: 'No sé cómo cobrar mi trabajo',
      why: 'Primero emitís la factura desde el proyecto; después el cliente la paga con Mercado Pago (si conectaste tu cuenta) o en efectivo (vos confirmás al recibirlo).',
      fix: 'En el detalle del proyecto tocá Emitir factura si aún no lo hiciste. Para cobrar por Mercado Pago, conectá tu cuenta en Cobros: sin eso el cliente solo puede pagarte en efectivo. Si eligió efectivo, al recibir el dinero tocá Confirmar cobro en efectivo (en Cobros o en el proyecto). En Cobros ves todas tus facturas, lo cobrado y lo pendiente.',
      href: '/panel/profesional/cobros',
      hrefLabel: 'Ir a Cobros',
    },
    {
      id: 'materiales-confuso',
      q: 'Me confundo con quién paga los materiales',
      why: 'Hay dos modos válidos y el proyecto usa uno solo, acordado con el cliente: (1) vos adelantás los materiales y los cobrás en tu factura, o (2) el cliente le paga directo al proveedor.',
      fix: 'Mirá la tarjeta "¿Quién paga los materiales?" del proyecto: está siempre visible para los dos. En el modo 2, tu factura va solo con mano de obra y cada proveedor emite su cobro directo al cliente. Cualquier cambio queda notificado.',
      href: '/panel/profesional/proyectos',
      hrefLabel: 'Ver el acuerdo',
    },
    {
      id: 'no-aparezco',
      q: 'No aparezco bien en el directorio',
      why: 'El orden es por reputación: reseñas positivas primero. Los perfiles sin verificación, sin obras ni reseñas quedan al fondo, aunque sean muy buenos.',
      fix: 'Verificá tu DNI, cargá tus mejores obras con fotos y pedile a tus clientes que dejen su reseña al finalizar cada obra (se activa sola al finalizar el proyecto).',
      href: '/panel/profesional/perfil',
      hrefLabel: 'Completar mi perfil',
    },
    {
      id: 'no-puedo-resenar',
      q: 'No encuentro dónde calificar a un cliente',
      why: 'Las reseñas entre participantes se activan cuando la obra finaliza, y la finaliza el cliente: es lo que las mantiene reales.',
      fix: 'La obra la finaliza el cliente: dejala en Revisión desde el detalle y pedile por chat que toque «Finalizar obra». En ese momento se activa tu reseña al cliente (estrellas, comentario y fotos).',
      href: '/panel/profesional/proyectos',
      hrefLabel: 'Ir a proyectos',
    },
    {
      id: 'fecha-choca',
      q: 'No me deja proponer o aceptar una fecha',
      why: 'Ese horario choca con otro trabajo tuyo ya acordado: HomIA no deja superponer trabajos confirmados. Si choca solo con una propuesta sin confirmar, te avisa pero te deja.',
      fix: 'Mirá tu Calendario (tocá el día para ver la agenda por hora con tus huecos libres) y proponé otro día u horario, por ejemplo de 07:00 a 12:00 en vez de todo el día.',
      href: '/panel/profesional/calendario',
      hrefLabel: 'Ver mi calendario',
    },
    {
      id: 'presupuesto-rechazado',
      q: 'Me rechazaron un presupuesto',
      why: 'Suele ser por precio fuera del contexto del cliente, plazo poco claro o una presentación genérica sin detalle de cómo se resuelve el trabajo.',
      fix: 'Revisá tu oferta en Mis ofertas y ajustá la próxima: detallá materiales, etapas y plazos. Un mensaje que explica el cómo vale más que un precio recortado.',
      href: '/panel/profesional/presupuestos',
      hrefLabel: 'Ver mis presupuestos',
    },
  ],

  proveedor: [
    {
      id: 'no-vendo',
      q: 'No me compran nada',
      why: 'Clientes y profesionales comparan precio, stock y distancia entre todos los proveedores. Catálogo incompleto, precios fuera de mercado o stock en cero te sacan de la comparación.',
      fix: 'Actualizá precios y cantidades en Stock, sumá fotos claras y verificá tu identidad con el DNI. Revisá que tu plan esté activo (Mi plan). Mirá tu tarjeta del directorio como si fueras el comprador.',
      href: '/panel/proveedor/stock',
      hrefLabel: 'Actualizar mi stock',
    },
    {
      id: 'cobro-pendiente',
      q: 'El cliente no me paga los materiales',
      why: 'En el modo "el cliente paga al proveedor", el pago depende de que el cobro esté emitido y de que el cliente elija método (Mercado Pago o efectivo).',
      fix: 'En Cobros → Cobros de proyectos, verificá que el cobro esté emitido (no solo pendiente de emitir). Si está esperando pago en efectivo, el cliente acordó eso: tocá Confirmar cobro cuando lo recibas. Si demora, respondé por chat cuando el cliente o el profesional te escriban (queda registrado).',
      href: '/panel/proveedor/cobros',
      hrefLabel: 'Ver mis cobros',
    },
    {
      id: 'plan-vencido',
      q: 'No puedo tocar mi stock o dejé de aparecer',
      why: 'Sin plan activo (terminó la prueba de 14 días, se canceló la suscripción o pasaron 35 días sin cobro) tu negocio sale de materiales, directorio, búsquedas y Homy, y no podés editar el stock ni gestionar ventas.',
      fix: 'Entrá a Mi plan y elegí Básico o PRO: se paga por Mercado Pago y, cuando se confirma, volvés a aparecer. Tus datos, reseñas y vinculaciones siguen ahí.',
      href: '/panel/proveedor/plan',
      hrefLabel: 'Ir a Mi plan',
    },
    {
      id: 'reserva-sin-stock',
      q: 'Me reservaron algo que no tengo',
      why: 'Las reservas se pueden hacer con o sin stock: el cliente te avisa que lo quiere y vos decidís.',
      fix: 'En Cobros → Ventas (pedidos), indicá «Disponible aproximadamente el…» con una fecha, y cuando lo tengas tocá «Ya lo tengo: disponible» (ahí el cliente tiene 48 h). Si no vas a conseguirlo, rechazala con un motivo.',
      href: '/panel/proveedor/cobros',
      hrefLabel: 'Ir a Ventas',
    },
    {
      id: 'puedo-resenar',
      q: '¿Puedo dejar reseñas yo también?',
      why: 'Hoy las reseñas las dejan los clientes (a profesionales y proveedores) y los profesionales (a clientes). El proveedor no reseña a nadie.',
      fix: 'Tu mejor estrategia es que cada entrega merezca 5 estrellas y foto: entregá a tiempo, completo y con comprobante. Las reseñas con fotos son tu marketing gratuito.',
      href: '/panel/proveedor/directorio',
      hrefLabel: 'Ver mi reputación',
    },
    {
      id: 'stock-agotado',
      q: 'Se me agotó un material y perdí ventas',
      why: 'El profesional compra donde hay stock: un catálogo con agotados empuja la venta al competidor.',
      fix: 'Usá las alertas del Inicio ("por agotar" y "agotados") para reponer antes de llegar a cero, y actualizá cantidades en Stock apenas cambien.',
      href: '/panel/proveedor',
      hrefLabel: 'Ver alertas del Inicio',
    },
    {
      id: 'no-aparezco',
      q: 'No aparezco en el directorio',
      why: 'El directorio ordena por reputación y muestra perfiles con catálogo activo. Sin stock cargado o sin verificación, tu tarjeta queda invisible o al fondo.',
      fix: 'Cargá tu catálogo en Stock y verificá tu DNI: tu perfil público se arma solo con esos datos y tus reseñas.',
      href: '/panel/proveedor/verificacion',
      hrefLabel: 'Verificar mi identidad',
    },
  ],
}
