// ═══════════════════════════════════════════════════════════════════════════
// CATÁLOGO MAESTRO HomIA — todos los elementos de una casa (dentro y fuera)
// Formato por elemento: [nombre estándar, [aliases], unidad, descripción]
// - nombre: el nombre correcto, como lo dice el catálogo del rubro
// - aliases: cómo lo llama la gente / el gremio (para el buscador y la IA)
// - unidad: cómo se vende (unidad, bolsa, paquete, metro, m2, kg, litro, rollo…)
// - descripción: qué es, para qué sirve y dónde se usa, en lenguaje natural
// Fuente de verdad para: buscador de la home, directorio, stock de proveedores
// y el agente de IA (Homy) cuando alguien no sabe cómo se llama lo que necesita.
// ═══════════════════════════════════════════════════════════════════════════

export const CATALOG_MAESTRO = [
{
  slug: 'albanileria', name: 'Corralón · Albañilería', icon: 'brick-wall', items: [
    ['Cemento Portland 50kg', ['cemento', 'bolsa cemento', 'portland'], 'bolsa', 'Bolsa de 50 kilos del polvo gris que, mezclado con arena y agua, forma el mortero y el hormigón. Es la base de toda obra: plateas, muros, revoques y contrapisos.'],
    ['Cemento blanco 25kg', ['cemento blanco'], 'bolsa', 'Igual que el cemento común pero blanco: se usa para revoques finos a la vista, mosaicos y trabajos donde el gris arruinaría el color final.'],
    ['Cemento hidrófugo', ['hidrófugo', 'cemento para techos'], 'bolsa', 'Cemento con aditivo que repele el agua. Se usa para revoques de muros húmedos, tanques, sótanos y reparaciones donde el agua filtra.'],
    ['Cal hidratada 25kg', ['cal', 'bolsa cal'], 'bolsa', 'Bolsa de cal que se mezcla con cemento y arena para hacer revoques plásticos que no se agrietan. También la usan los albañiles para asentar ladrillos.'],
    ['Arena gruesa m³', ['arena', 'arena gruesa'], 'm3', 'Arena con partículas grandes para preparar hormigón y contrapisos. Se vende por metro cúbico o por tonelada en cualquier corralón.'],
    ['Arena fina m³', ['arena fina', 'arena para revoque'], 'm3', 'Arena tamizada, de partícula chica, para revoques finos, asentado de cerámicos y terminaciones lisas. La pide el albañil para el revoque grueso y el fino.'],
    ['Piedra braza m³', ['piedra', 'braza', 'piedra partida'], 'm3', 'Piedra partida grande que va dentro del hormigón estructural para darle cuerpo. Se usa en plateas, fundaciones y pavimentos.'],
    ['Ladrillo común 6cm', ['ladrillo', 'ladrillo común', 'bordo'], 'unidad', 'El ladrillo rojo de toda la vida, de 6 centímetros de alto. Sirve para levantar muros de 15, 30 o más centímetros de espesor.'],
    ['Ladrillo hueco 8cm', ['ladrillo hueco', 'ladrillón', 'hueco 8'], 'unidad', 'Ladrillo cerámico con huecos internos, más liviano y aislante que el común. Ideal para muros exteriores de casas: cubre más con menos peso.'],
    ['Ladrillo Ceramón 18x18', ['ceramón', 'bloque cerámico'], 'unidad', 'Bloque cerámico grande de 18 por 18 centímetros. Levanta muros en poco tiempo porque equivale a varios ladrillos comunes; se usa en construcción moderna.'],
    ['Bloque de cemento 19x19x39', ['bloque hormigón', 'bloque de cemento'], 'unidad', 'Bloque macizo de cemento y arena para muros portantes, paredes dobles y cierres de frente. Se lo ve mucho en obras y galpones.'],
    ['Ladrillo refractario', ['refractario', 'ladrillo para parrilla'], 'unidad', 'Ladrillo especial que aguanta el fuego directo. Es el que lleva el fondo de parrillas, hornos de barro, salamandras y estufas a leña.'],
    ['Hierro cemento 6mm x12m', ['hierro 6', 'acero 6'], 'barra', 'Barra de acero corrugado de 6 milímetros, de 12 metros. Refuerza columnas chicas, contrapisos y losas livianas.'],
    ['Hierro cemento 8mm x12m', ['hierro 8', 'acero 8'], 'barra', 'Barra corrugada de 8 milímetros y 12 metros, la más usada en viviendas: refuerza losas, columnas y vigas de toda casa.'],
    ['Hierro cemento 10mm x12m', ['hierro 10', 'acero 10'], 'barra', 'Acero corrugado de 10 milímetros para columnas y vigas con más carga. Se combina con estribos para armar la estructura.'],
    ['Hierro cemento 12mm x12m', ['hierro 12', 'acero 12'], 'barra', 'Barra de acero de 12 milímetros para fundaciones, vigas centrales y columnas de cargas grandes.'],
    ['Hierro cemento 16mm x12m', ['hierro 16', 'acero 16'], 'barra', 'Acero de 16 milímetros para estructuras exigentes: losas grandes, columnas principales y obras de varios pisos.'],
    ['Alambre armar 17', ['alambre armar', 'fiadarme', 'alambre 17'], 'bobina', 'Alambre delgado que ata los hierros entre sí antes de volcar el hormigón. Todo el esqueleto de acero se amarra con este alambre.'],
    ['Malla futures 15x15', ['malla futures', 'futures', 'malla gallinero'], 'rollo', 'Malla metálica liviana que va sobre el contrapiso para que el piso no se fisure. También sirve para revoques sobre ladrillones.'],
    ['Malla soldada 15x15 Q188', ['malla soldada', 'malla Q188'], 'placa', 'Panel soldado de acero que refuerza contrapisos, losas y pisos industriales. Reemplaza el atado manual de hierros en pisos.'],
    ['Yeso negro 30kg', ['yeso negro', 'yeso'], 'bolsa', 'Yeso grueso para nivelar y emparchar paredes y cielorrasos antes del enduido. Terminación previa a la pintura.'],
    ['Yeso blanco 30kg', ['yeso blanco'], 'bolsa', 'Yeso fino de terminación para cielorrasos y detalles de interiores. Da superficie lisa lista para enduido y pintura.'],
    ['Hormigón elaborado', ['hormigón', 'concreto preparado'], 'm3', 'Hormigón que llega mezclado en camión listo para volcar. Se pide por metro cúbico cuando hay que hacer una platea o losa grande de una sola vez.'],
    ['Aditivo plastificante', ['plastificante', 'aditivo hormigón'], 'litro', 'Líquido que se agrega al hormigón o mortero para hacerlo más fluido sin agregar más agua. Mejora la resistencia y evita que el mezclado quede débil.'],
    ['Retardador de fragua', ['retardador'], 'litro', 'Aditivo que demora el endurecimiento del hormigón en días calurosos, dando tiempo a terminarlo bien antes de que fragüe.'],
    ['Polvo de ladrillo', ['polvo de ladrillo', 'toba'], 'bolsa', 'Ladrillo molido que se usa como agregado en morteros tradicionales y para juntas de ladrillo a la vista.'],
  ],
},
{
  slug: 'durlock', name: 'Durlock · Chapa seca', icon: 'panels-top-left', items: [
    ['Placa yeso 9.5mm 1.20x2.40', ['durlock', 'placa yeso', 'placa 9 y medio'], 'placa', 'Placa de yeso entre dos cartones: el panel clásico para paredes y cielorrasos secos de interiores. Se atornilla sobre perfiles.'],
    ['Placa yeso 12.7mm 1.20x2.40', ['placa 12 y medio', 'durlock grueso'], 'placa', 'Placa de yeso más gruesa y resistente, para paredes que necesitan mayor aislación y solidez acústica.'],
    ['Placa RH resistencia humedad', ['placa RH', 'durlock verde', 'resistente humedad'], 'placa', 'Placa de yeso tratada contra la humedad, de núcleo verde. Es la que se usa en baños, lavaderos y cocinas.'],
    ['Placa RF resistencia fuego', ['placa RF', 'durlock rosa'], 'placa', 'Placa con aditivos contra el fuego para parrillas interiores, instalaciones de calefacción y salidas de escapes.'],
    ['Perfil durlock 89mm x3m', ['perfil 89', 'caño durlock 89'], 'barra', 'Perfil metálico estructural de 89 milímetros que forma el esqueleto de las paredes dobles de durlock.'],
    ['Perfil durlock 35mm x3m', ['perfil 35', 'caño durlock 35'], 'barra', 'Perfil liviano de 35 milímetros para cielorrasos y paredes simples de chapa seca.'],
    ['Solera durlock 89mm', ['solera 89'], 'barra', 'Perfil en U que se fija al piso y al techo para encastrar los verticales de 89. Es el arraque de toda pared de durlock.'],
    ['Masilla durlock 20kg', ['masilla durlock', 'enduido durlock'], 'bolsa', 'Pasta que se aplica sobre las juntas y tornillos de la placa para dejar la pared lista para pintar. Se lija una vez seca.'],
    ['Masilla plástica durlock', ['masilla plástica', 'pasta junta'], 'lata', 'Masilla lista para usar que no requiere mezcla: se levanta con espátula y cubre juntas y cabezas de tornillos.'],
    ['Cinta papel para juntas', ['cinta durlock', 'cinta papel'], 'rollo', 'Cinta de papel que refuerza las juntas entre placas antes de aplicar la masilla. Evita que la junta se marque o se rompa.'],
    ['Tornillo autoperforante 6x1"', ['autoperforante 6x1', 'tornillo durlock'], 'caja', 'Tornillo punta mecha para fijar la placa al perfil metálico. Se compra por caja de cientos.'],
    ['Tornillo punta aguja 6x3/4"', ['punta aguja', 'tornillo planchuela'], 'caja', 'Tornillo para unir perfiles metálicos entre sí y fijar soleras. Pasa a través del metal sin perforación previa.'],
    ['Esquinero metálico durlock', ['esquinero', 'cono esquinero'], 'unidad', 'Perfil metálico en L que protege y endereza los cantos exteriores de las paredes de durlock antes de masillar.'],
  ],
},
{
  slug: 'plomeria', name: 'Sanitarios · Plomería', icon: 'droplets', items: [
    ['Caño termofusión 20mm', ['termofusión 20', 'caño agua 20'], 'barra', 'Caño plástico blanco para agua fría y caliente que se une por termofusión con un soldador. Es el estándar actual en instalaciones domiciliarias.'],
    ['Caño termofusión 25mm', ['termofusión 25', 'caño agua fría'], 'barra', 'Caño de termofusión de 25 milímetros para alimentación principal de baños y cocinas.'],
    ['Caño termofusión 32mm', ['termofusión 32'], 'barra', 'Caño termofusión de 32 milímetros para la entrada principal de agua de la casa.'],
    ['Caño PVC desagüe 110mm', ['caño 110', 'tubo desagüe', 'PVC cloacal'], 'barra', 'Tubo plástico rígido de 110 milímetros para desagües cloacales y pluviales. Es el caño estándar para inodoros, colectores y bajadas.'],
    ['Caño PVC 63mm', ['caño 63', 'PVC 63'], 'barra', 'Tubo PVC de 63 milímetros para desagües secundarios: piletas, lavaderos y desagües de piso.'],
    ['Caño ABS 40mm', ['ABS 40', 'caño ABS'], 'barra', 'Caño plástico negro de 40 milímetros para desagües internos de piletas y lavatorios. Se pega con cemente ABS.'],
    ['Codo PVC 90° 110mm', ['codo 110', 'codo cloacal'], 'unidad', 'Codo plástico que gira 90 grados el desagüe cloacal de 110. Se usa en cada cambio de dirección de la cañería.'],
    ['Codo termofusión 25mm', ['codo termofusión 25', 'codo agua'], 'unidad', 'Pieza de termofusión que dobla 90 grados el caño de agua. Se suelda con el soldador de termofusión.'],
    ['Tee termofusión 25mm', ['tee termofusión', 'tres termofusión'], 'unidad', 'Pieza en T para derivar el caño de agua hacia un punto nuevo: una canilla, un inodoro o una lavarropas.'],
    ['Unión universal 110mm', ['unión universal', 'cama universal'], 'unidad', 'Unión desmontable de goma y PVC que permite desarmar el desagüe sin cortar: se usa para mantener y limpiar cañerías cloacales.'],
    ['Llave de paso esférica 1/2"', ['llave paso', 'llave esférica', 'llave medio'], 'unidad', 'Llave con esfera interna que corta el agua de un tramo de cañería. La de media pulgada va en baños, piletas y calefones.'],
    ['Llave de paso esférica 3/4"', ['llave paso 34', 'llave tres cuartos'], 'unidad', 'Llave de paso de tres cuartos para entradas principales de agua, tanques y termotanques.'],
    ['Llave de paso esférica 1"', ['llave paso 1', 'llave pulgada'], 'unidad', 'Llave de una pulgada para cañerías principales y bombeo. Se usa antes de la cisterna o la bomba.'],
    ['Flexible de inodoro', ['flexible toilet', 'flexible vaso'], 'unidad', 'Manguera metálica flexible que conecta la cañería al depósito del inodoro. Se cambia cada vez que el depósito se instala o gotea.'],
    ['Flexible de lavatorio', ['flexible lavatorio', 'flexible pileta'], 'unidad', 'Conector flexible metálico para unir la grifería del lavatorio o bidet a la cañería. La pieza que más se cambia en un baño.'],
    ['Depósito de inodoro completo', ['depósito', 'tanque inodoro', 'mochila'], 'unidad', 'Tanque superior con mecanismo interno (botón, flotante y válvula) que carga el agua del inodoro. Se vende completo listo para armar.'],
    ['Mecanismo depósito doble carga', ['mecanismo inodoro', 'flotante depósito'], 'unidad', 'Repuesto interno del depósito: flotante, válvula de carga y descarga con doble opción de agua. Lo que se cambia cuando el inodoro pierde o no carga.'],
    ['Inodoro blanco completo', ['inodoro', 'vaso sanitario'], 'unidad', 'Conjunto de vaso y depósito de porcelana sanitaria blanca. Es la pieza principal del baño; se vende con asiento aparte o incluido según marca.'],
    ['Inodoro c/depósito y asiento', ['inodoro completo', 'kit inodoro'], 'unidad', 'Kit completo listo para instalar: vaso, depósito mecánico y asiento. Lo elige quien cambia el baño entero de una vez.'],
    ['Bidet blanco', ['bidet'], 'unidad', 'Porcelana sanitaria para higiene personal, del mismo juego que el inodoro. Requiere grifería específica de bidet.'],
    ['Grifería monocomando cocina', ['canilla cocina', 'monocomando cocina'], 'unidad', 'Canilla de una sola palanca que regula caudal y temperatura. La más práctica para piletas de cocina.'],
    ['Grifería monocomando baño', ['canilla baño', 'monocomando lavatorio'], 'unidad', 'Canilla de palanca única para lavatorio, con desagüe con pulsador incluido en la mayoría de los modelos.'],
    ['Grifería ducha monocomando', ['canilla ducha', 'monocomando ducha'], 'unidad', 'Grifería de pared para ducha con palanca única. Controla el agua de la ducha y suele incluir el caño y la mira.'],
    ['Grifería lavadero', ['canilla lavadero', 'grifería doble lavadero'], 'unidad', 'Canilla de dos salidas para el lavadero de la casa: agua fría y caliente con boquillas para manguera.'],
    ['Mira de ducha', ['mira', 'ducha fija', 'flor de ducha'], 'unidad', 'Pieza perforada por donde sale el agua de la ducha. Se cambia cuando se tapa de cal o se rompe.'],
    ['Ducha escocesa', ['ducha escocesa', 'ducha manual'], 'unidad', 'Ducha de mano con manguera flexible y soporte: permite dirigir el agua donde se necesita. Ideal para baños con familia.'],
    ['Sifón de lavatorio', ['sifón', 'sifón pileta'], 'unidad', 'Tubo curvo bajo el lavatorio que retiene agua para que los olores de la cloaca no vuelvan al baño. Primera pieza que se revisa si hay olor o goteo.'],
    ['Sifón de cocina', ['sifón cocina', 'sifón doble pileta'], 'unidad', 'Sifón para piletas de cocina, con o sin toma para lavarropas. Evita que suban olores por el desagüe de la pileta.'],
    ['Rejilla desagüe piso', ['rejilla piso', 'sumidero'], 'unidad', 'Rejilla metálica o plástica a nivel del piso que recoge el agua del baño o lavadero y la manda al desagüe.'],
    ['Tanque de agua 1100L', ['tanque 1100', 'cisterna', 'tanque tricapa'], 'unidad', 'Tanque plástico tricapa de mil cien litros que reserva el agua de la casa. Va arriba para gravedad o abajo con bomba presurizadora.'],
    ['Tanque de agua 750L', ['tanque 750'], 'unidad', 'Tanque tricapa de setecientos cincuenta litros, el más pedido para viviendas medianas.'],
    ['Bomba de agua 1/2 HP', ['bomba agua', 'electrobomba', 'bomba medio caballo'], 'unidad', 'Bomba eléctrica que eleva el agua del tanque o pozo a la casa. Da presión en pisos altos cuando el agua llega débil.'],
    ['Bomba presurizadora', ['presurizadora', 'bomba presión'], 'unidad', 'Bomba con presostato que mantiene presión constante en toda la casa mientras se usa el agua. Es lo que se instala cuando la ducha pierde fuerza.'],
    ['Termotanque eléctrico 80L', ['termotanque', 'termotanque 80'], 'unidad', 'Calefón eléctrico de 80 litros con resistencias internas: guarda agua caliente para toda la casa. Necesista toma dedicada y llave de paso.'],
    ['Termotanque eléctrico 50L', ['termotanque 50'], 'unidad', 'Termotanque eléctrico de 50 litros para departamentos o casas de dos personas.'],
    ['Termotanque a gas 80L', ['termotanque gas'], 'unidad', 'Termotanque que calienta el agua quemando gas, con encendido piloto. Más económico de uso que el eléctrico si hay gas natural.'],
    ['Calefón a gas 14L', ['calefón', 'calefón 14'], 'unidad', 'Calefón de paso que calienta el agua al momento, sin tanque. Catorce litros por minuto alcanzan para ducha y cocina simultáneas.'],
    ['Cinta teflón', ['teflón', 'cinta teflón agua'], 'unidad', 'Cinta blanca que se enrolla en la rosca de caños y llaves para que el agua no gotee. Está en cada caja de herramientas de plomero.'],
    ['Silicona sanitaria', ['silicona', 'sellador sanitario'], 'unidad', 'Silicona blanca antihongos que sella el borde del inodoro, bidet, pileta y cerámicos del baño. Impermeabiliza y evita filtraciones.'],
    ['Cemente PVC', ['cementé PVC', 'pegamento caño PVC'], 'lata', 'Adhesivo líquido que suelda tubos y accesorios de PVC cloacal. Se aplica con brocha en la unión y fragua en minutos.'],
    ['Manguera lavarropas', ['manguera washing', 'manguera lavarropas'], 'unidad', 'Manguera reforzada que conecta el lavarropas a la canilla. Se repone cuando se seca o pierde.'],
    ['Codo evacuación calefón', ['codo evacuación', 'tiro calefón'], 'unidad', 'Tubo de evacuación de gases del calefón o termotanque a gas hacia el exterior. Pieza de seguridad obligatoria en toda instalación.'],
  ],
},
{
  slug: 'gasistas', name: 'Gas · Gasistas', icon: 'flame', items: [
    ['Caño gas epoxi 25mm', ['caño gas', 'epoxi 25'], 'barra', 'Caño metálico con recubrimiento epoxi naranja para instalaciones de gas. Es el material obligatorio para cañerías vistas de gas natural.'],
    ['Caño gas epoxi 32mm', ['epoxi 32'], 'barra', 'Caño epoxi de 32 milímetros para la entrada principal de gas o instalaciones de gran caudal.'],
    ['Caño gas epoxi 20mm', ['epoxi 20'], 'barra', 'Caño epoxi de 20 milímetros para derivaciones a artefactos individuales.'],
    ['Codo gas 90° 25mm', ['codo gas'], 'unidad', 'Pieza epoxi que dobla la cañería de gas 90 grados. Se roscas y sella con teflón para gas.'],
    ['Tee gas 25mm', ['tee gas'], 'unidad', 'Pieza en T de cañería de gas para derivar el flujo hacia un artefacto nuevo.'],
    ['Llave de paso gas 1/2"', ['llave gas', 'llave artefacto'], 'unidad', 'Llave de rosca que corta el gas de cada artefacto. Es obligatoria poder cerrar el gas del calefón, horno y estufa por separado.'],
    ['Regulador de gas 10kg', ['regulador', 'regulador garrafa'], 'unidad', 'Pieza que reduce la presión del gas de garrafa al nivel seguro de los artefactos. Se conecta a la garrafa y de ahí sale la manguera.'],
    ['Manguera gas 1m', ['manguera gas'], 'unidad', 'Manguera reforzada homologada que une el artefacto a la llave o regulador de gas. Vence con los años y se reemplaza.'],
    ['Cinta teflón para gas', ['teflón gas', 'teflón amarillo'], 'unidad', 'Cinta selladora especial (gris o amarilla) para roscas de gas. No es la misma del agua: resiste el gas sin degradarse.'],
    ['Masilla epoxi', ['masilla epoxi', 'soldadura fría'], 'unidad', 'Pasta de dos componentes que endurece como metal. Tapaja fugas y fija piezas en instalaciones donde no se puede soldar.'],
    ['Horno empotrar a gas', ['horno gas', 'horno empotrar'], 'unidad', 'Horno que se embute en la pared o mueble de cocina y funciona a gas natural o garrafa. Requiere instalación por gasista matriculado.'],
    ['Anafe 4 hornallas', ['anafe', 'hornallas'], 'unidad', 'Repisa de hornallas de gas que se instala sobre la mesada. Puede ir con horno debajo o sin él.'],
    ['Calefón a gas 14L', ['calefón', 'calefón 14 litros'], 'unidad', 'Calefón de paso que calienta el agua al momento. La instalación debe hacerla un gasista matriculado con tiro bien evacuado.'],
    ['Estufa tiro balanceado 5000 kcal', ['estufa balanceada', 'TBC'], 'unidad', 'Estufa a gas sellada que toma aire y expulsa por un solo tubo al exterior. La más segura para ambientes: no quema oxígeno interior.'],
    ['Estufa tiro natural', ['estufa tiro natural', 'TN'], 'unidad', 'Estufa a gas que evacúa por tiro vertical al techo. Requiere buena ventilación del ambiente.'],
    ['Salamandra a leña', ['salamandra', 'estufa leña'], 'unidad', 'Estufa metálica de hierro fundido o chapa que calienta quemando leña. Sirve también de horno y da calor rápido en invierno.'],
    ['Tubo evacuación gas 90cm', ['tubo tiro', 'caño evacuación'], 'unidad', 'Tubo galvanizado que lleva los gases quemados al exterior. Obligatorio en toda estufa o calefón a gas.'],
  ],
},
{
  slug: 'electricistas', name: 'Electricidad', icon: 'zap', items: [
    ['Cable unipolar 1.5mm x100m', ['cable 1.5', 'unipolar 1 y medio'], 'bobina', 'Rollo de cien metros de cable flexible de 1.5 mm² para circuitos de iluminación. El cable rojo o negro lleva corriente, el celeste es neutro.'],
    ['Cable unipolar 2.5mm x100m', ['cable 2.5', 'unipolar'], 'bobina', 'Cable de 2.5 mm² para tomas de uso general. Es el cable más usado en una casa: alimenta enchufes y equipos livianos.'],
    ['Cable unipolar 4mm x100m', ['cable 4'], 'bobina', 'Cable de 4 mm² para líneas de mayor consumo: cocinas, lavarropas, aires de tamaño medio.'],
    ['Cable unipolar 6mm x100m', ['cable 6'], 'bobina', 'Cable de 6 mm² para aires acondicionados grandes, hornos eléctricos y duchas eléctricas.'],
    ['Cable unipolar 10mm x100m', ['cable 10'], 'bobina', 'Cable de 10 mm² para la línea principal del medidor al tablero de una vivienda.'],
    ['Cable U-1000 3x2.5mm', ['cable 3x2.5', 'cable subterráneo'], 'bobina', 'Cable tripolar con doble aislación para alimentar subtableros, bombas y líneas exteriores, incluso enterradas con protección.'],
    ['Cable trenzado paralelo', ['cable paralelo', 'trenzado'], 'metro', 'Cable plano doble para extensiones y artefactos livianos. El clásico de las zapatillas y veladores.'],
    ['Térmica bipolar 25A', ['térmica 25', 'llave térmica'], 'unidad', 'Llave que corta la electricidad cuando un circuito consume de más. La de 25 amperes protege la línea de tomas generales.'],
    ['Térmica bipolar 40A', ['térmica 40'], 'unidad', 'Térmica de 40 amperes para el circuito principal del tablero de una casa.'],
    ['Térmica bipolar 16A', ['térmica 16'], 'unidad', 'Térmica de 16 amperes para circuitos específicos: iluminación o un artefacto liviano dedicado.'],
    ['Diferencial 2x30mA', ['diferencial', 'salva vidas'], 'unidad', 'Interruptor que corta la luz al detectar una fuga a tierra: el que salva vidas ante un contacto accidental. Obligatorio en todo tablero.'],
    ['Tablero embutir 12 módulos', ['tablero', 'llavero eléctrico'], 'unidad', 'Caja donde se agrupan térmicas y diferenciales de la casa. Doce módulos alcanzan para una vivienda estándar.'],
    ['Tablero embutir 24 módulos', ['tablero 24'], 'unidad', 'Tablero grande para casas con muchos circuitos: aires, bombas, exterior, cocina y tomas por separado.'],
    ['Toma corriente doble blanca', ['toma', 'enchufe doble', 'toma doble'], 'unidad', 'Enchufe doble empotrado de pared, el más común de la casa. Se instala a 40-50 centímetros del piso como mínimo.'],
    ['Toma corriente con tapa', ['toma estanca', 'toma exterior'], 'unidad', 'Toma con tapa protectora para exteriores, garajes y zonas húmedas. Evita que el polvo y el agua entren al enchufe.'],
    ['Llave interruptor simple', ['llave luz', 'interruptor', 'llave simple'], 'unidad', 'Llave de pared que enciende un punto de luz. La más común del hogar.'],
    ['Llave conmutada doble', ['llave paralela', 'conmutada'], 'unidad', 'Par de llaves que encienden la misma luz desde dos lados del ambiente, como al pie y arriba de una escalera.'],
    ['Llave doble de pared', ['llave doble'], 'unidad', 'Llave con dos botones independientes en una sola placa: enciende dos luces del mismo ambiente.'],
    ['Timbre eléctrico campanilla', ['timbre', 'campanilla'], 'unidad', 'Timbre de pared que suena al presionar el botón de la entrada. Hay modelos con armonías y sin cables.'],
    ['Botón timbre exterior', ['botón timbre', 'pulsador puerta'], 'unidad', 'Botón resistente a la intemperie que se instala en la puerta de entrada y activa el timbre interior.'],
    ['Tubo corrugado 20mm x100m', ['corrugado 20', 'caño luz'], 'bobina', 'Tubo plástico flexible dentro del cual corren los cables empotrados en la pared. Todo cableado embutido va por dentro de este caño.'],
    ['Tubo corrugado 25mm x100m', ['corrugado 25'], 'bobina', 'Corrugado de 25 milímetros para tramos con muchos cables o líneas principales enterradas.'],
    ['Caja de luz embutir', ['caja luz', 'caja embutir'], 'unidad', 'Caja plástica que se empotra en la pared y aloja las llaves y tomas, y el empalme de los cables.'],
    ['Caja de paso', ['caja de paso', 'caja octogonal'], 'unidad', 'Caja donde se hacen empalmes o derivaciones de cables en el cielorraso o pared, tapada con placa.'],
    ['Zócalo portátil 3x2.5', ['zócalo portátil', 'zócalo eléctrico'], 'metro', 'Canal plástico de superficie con compartimentos para cables y tomas: instala la electricidad sin romper la pared, ideal en locales.'],
    ['Cinta aisladora', ['cinta aislante', 'cinta negra'], 'unidad', 'Cinta plástica aislante que envuelve empalmes y reparaciones eléctricas. No puede faltar en ninguna caja de herramientas.'],
    ['Prensacable', ['prensacable', 'tuerca plástica'], 'unidad', 'Pieza que sujeta el cable en la entrada de tomas, llaves y cajas para que el tirón no haga fuerza sobre el empalme.'],
    ['Barra común neutra', ['barra común', 'barra neutra'], 'unidad', 'Barra metálica dentro del tablero donde se conectan todos los neutros del circuito. Pieza básica de todo tablero.'],
    ['Lámpara LED 9W E27', ['led 9w', 'bombillo led', 'foco led'], 'unidad', 'Bombillo LED de bajo consumo, rosca gruesa estándar. Reemplaza al foco incandescente gastando el 10% de la energía.'],
    ['Lámpara LED 15W E27', ['led 15w'], 'unidad', 'LED de mayor potencia para ambientes grandes: garage, patio o cocina.'],
    ['Tubo LED 120cm', ['tubo led', 'tubo fluorescente led'], 'unidad', 'Tubo de luz LED de 1.20 metros para cocinas, garajes y oficinas. Ilumina parejo y no parpadea.'],
    ['Dicroica LED GU10 7W', ['dicroica', 'led GU10'], 'unidad', 'Bombillo LED de encastrar para cielorrasos con falso techo. Da una luz dirigida y moderna.'],
    ['Proyector LED 50W exterior', ['proyector led', 'reflector exterior'], 'unidad', 'Reflector LED potente para patios, frentes y entradas. Ilumina como una farola gastando poco.'],
    ['Velador exterior pared', ['velador exterior', 'aplique exterior'], 'unidad', 'Aplique de pared cerrado y a prueba de agua para iluminar entradas y patios.'],
    ['Medidor monofásico', ['medidor luz', 'medidor'], 'unidad', 'Medidor de consumo eléctrico que se instala en la entrada de la casa. La pieza de arranque de toda conexión nueva.'],
    ['Llave térmica caja exterior', ['caja medidor', 'gabinete medidor'], 'unidad', 'Gabinete exterior que aloja medidor y térmica principal en la fachada, como exigen las distribuidoras.'],
  ],
},
{
  slug: 'iluminacion', name: 'Iluminación', icon: 'lightbulb', items: [
    ['Panel LED 36W embutir', ['panel led', 'panel embutir'], 'unidad', 'Panel cuadrado de luz LED que se embute en el cielorraso de durlock. Ilumina todo el ambiente con luz pareja y moderna.'],
    ['Panel LED superficie', ['panel superficie'], 'unidad', 'Panel LED que se monta sobre el cielorraso sin embutir, ideal cuando no hay falso techo.'],
    ['Péndulo LED cocina', ['péndulo', 'pendulo led'], 'unidad', 'Luminaria alargada que cuelga sobre la mesada o la mesa de cocina. Da luz directa donde se trabaja.'],
    ['Colgante comedor', ['colgante', 'colgante comedor'], 'unidad', 'Luminaria decorativa que cuelga sobre la mesa del comedor. Combina iluminación y diseño.'],
    ['Aplique de pared interior', ['aplique', 'aplique pared'], 'unidad', 'Luminaria fija a la pared para pasillos, dormitorios y respaldos de cama.'],
    ['Aplique exterior estanco', ['aplique exterior', 'aplique estanco'], 'unidad', 'Aplique sellado contra agua y polvo para frentes, galerías y patios.'],
    ['Tira LED 5m con fuente', ['tira led', 'cinta led'], 'unidad', 'Cinta adhesiva con LED que ilumina detrás de muebles, estanterías y cielorrasos. Viene con fuente de alimentación.'],
    ['Guirnalda LED exterior', ['guirnalda', 'luces patio'], 'unidad', 'Cadena de bombillos decorativos para patios, galerías y festejos. Da ambiente cálido al aire libre.'],
    ['Dicroica LED GU10 7W', ['dicroica', 'GU10'], 'unidad', 'Bombillo LED de encastrar en falso techo. La más elegida para iluminación moderna dirigida.'],
    ['Reflector LED con sensor', ['reflector sensor', 'proyector con sensor'], 'unidad', 'Proyector que enciende solo al detectar movimiento. Seguridad y luz instantánea en entradas y patios.'],
    ['Farola jardín 80cm', ['farola jardín', 'farol exterior'], 'unidad', 'Farol de pie para senderos y jardines. Ilumina y decora el exterior de la casa.'],
    ['Luz de emergencia LED', ['luz emergencia', 'baliza emergencia'], 'unidad', 'Luminaria con batería que enciende sola cuando se corta la luz. Obligatoria en escaleras y pasillos de edificios.'],
    ['Regulador de luz', ['regulador', 'dimmer'], 'unidad', 'Llave que sube y baja la intensidad de la luz para crear ambiente. Ideal en comedores y dormitorios.'],
    ['Lámpara velador mesa', ['velador', 'lámpara mesa'], 'unidad', 'Lámpara de mesa para mesas de luz y escritorios. Luz cálida para leer y descansar.'],
    ['Globo exterior macetero', ['globo exterior', 'luz jardín'], 'unidad', 'Luz cerrada de vidrio o policarbonato para patios, resistente a la lluvia.'],
    ['Foco LED color RGB', ['led RGB', 'foco color'], 'unidad', 'Bombillo LED que cambia de color con control remoto. Para ambientes festivos y decolorados modernos.'],
  ],
},
{
  slug: 'pintura', name: 'Pinturería', icon: 'paint-roller', items: [
    ['Látex interior 20L blanco', ['látex interior', 'látex 20l'], 'bidón', 'Pintura al agua para paredes internas, de secado rápido y sin olor fuerte. Veinte litros alcanzan para unos 80 m² por mano.'],
    ['Látex exterior 20L', ['látex exterior'], 'bidón', 'Látex reforzado contra sol y lluvia para fachadas y muros exteriores. Resiste la intemperie sin descascararse.'],
    ['Látex color por 4L', ['látex color', 'látex 4 litros'], 'bidón', 'Látex ya pigmentado en colores para ambientes internos. Práctico para pintar una habitación sin mezclar colores.'],
    ['Esmalte sintético 4L', ['esmalte', 'sintético'], 'lata', 'Pintura al solvente brillante y dura para madera y hierro: aberturas, rejas y muebles exteriores.'],
    ['Esmalte agua 4L', ['esmalte agua', 'esmalte al agua'], 'lata', 'Esmalte de secado rápido y bajo olor para madera y metal. Menos tóxico que el sintético y limpio con agua.'],
    ['Anticorrosivo 4L', ['anticorrosivo', 'fondo anticorrosivo'], 'lata', 'Pintura base de óxido que protege el hierro antes del esmalte. Primera capa de toda reja, portón o techo de chapa.'],
    ['Membrana líquida 20kg', ['membrana líquida', 'impermeabilizante'], 'tambor', 'Pintura elástica espesa que impermeabiliza techos, terrazas y muros húmedos. Se aplica con rodillo en capas cruzadas.'],
    ['Enduido plástico 20kg', ['enduido', 'enduido plástico'], 'bolsa', 'Pasta que nivela paredes antes de pintar: tapa poros, grietas y marcas. Se lija y queda lisa lista para el látex.'],
    ['Enduido interior lista', ['enduido lista', 'pasta pared'], 'lata', 'Enduido ya preparado en balde, listo para aplicar con espátula sin mezclar.'],
    ['Fijador sellador 4L', ['fijador', 'sellador'], 'lata', 'Líquido que se aplica antes de pintar para sellar y endurecer paredes porosas o con revoque viejo. Hace que la pintura rinda más.'],
    ['Imprimación al agua', ['imprimación', 'primer'], 'lata', 'Capa base para superficies nuevas o lisas (yeso, durlock) que ayuda a que la pintura agarre parejo.'],
    ['Barniz poliuretánico 4L', ['barniz', 'PU'], 'lata', 'Barniz duro y brillante que protege pisos de madera, escaleras y mesadas. Aguanta el tránsito y el agua.'],
    ['Barniz madera al agua', ['barniz agua'], 'lata', 'Barniz de bajo olor para maderas interiores y exteriores, mantiene el color natural.'],
    ['Pigmento color al agua', ['pigmento', 'tonalizante'], 'litro', 'Color concentrado que se mezcla en el látex blanco para conseguir el tono exacto que se busca.'],
    ['Texturado plástico', ['texturado', 'revestimiento texturado'], 'tambor', 'Pintura gruesa con grano que se aplica en exteriores para cubrir grietas finas y dar terminación rústica.'],
    ['Rodillo lana 22cm', ['rodillo', 'rodillo lana'], 'unidad', 'Rodillo de lana para pintar paredes y techos con látex. La herramienta de pintura más usada.'],
    ['Rodillo espuma esmalte', ['rodillo espuma', 'rodillo esmalte'], 'unidad', 'Rodillo de espuma para esmaltes y barnices, deja terminación lisa sin vellitos.'],
    ['Pincel 2"', ['pincel', 'brocha 2'], 'unidad', 'Pincel de dos pulgadas para bordes, molduras y detalles que el rodillo no llega.'],
    ['Brocha 3"', ['brocha 3', 'brocha ancha'], 'unidad', 'Brocha ancha para encolar y pintar superficies grandes a mano.'],
    ['Cinta de pintor 24mm', ['cinta pintor', 'cinta azul'], 'rollo', 'Cinta que protege zócalos, vidrios y marcos mientras se pinta. Se saca sin dejar rastro.'],
    ['Lija al agua #400', ['lija 400', 'lija agua'], 'paquete', 'Lija fina para lijar enduido y barniz entre manos con agua. Da la terminación final lisa.'],
    ['Lija madera #80', ['lija 80', 'lija gruesa'], 'paquete', 'Lija gruesa para desbastar madera y sacar pintura vieja antes de volver a pintar.'],
    ['Bandeja pintor', ['bandeja', 'cubeta pintura'], 'unidad', 'Bandeja plástica donde se vierte la pintura y se carga el rodillo parejo.'],
    ['Espátula acero', ['espátula', 'espátula enduido'], 'unidad', 'Hoja flexible para aplicar enduido, sacar pintura floja y emparchar grietas.'],
    ['Diluyente sintético 1L', ['diluyente', 'thinner'], 'litro', 'Solvente que aligera esmaltes y limpia pinceles y brochas de pintura sintética.'],
    ['Aguarrás 1L', ['aguarrás', 'trementina'], 'litro', 'Solvente para diluir y limpiar pinturas al óleo y esmaltes, con menos olor que el diluyente común.'],
    ['Quitapinturas', ['quitapinturas'], 'litro', 'Producto que ablanda pinturas viejas para sacarlas sin tanto lija. Se usa en restauraciones de aberturas.'],
    ['Roller techo con mango', ['mango rodillo', 'extensor rodillo'], 'unidad', 'Mango extensible que permite pintar el techo desde el piso sin escalera ni banqueta.'],
  ],
},
{
  slug: 'herreria', name: 'Ferretería · Herrería', icon: 'wrench', items: [
    ['Tornillo autoperforante 6x1"', ['autoperforante', 'tornillo sheet'], 'caja', 'Tornillo punta mecha que perfora metal fino y madera sin taladrar antes. Se compra por caja para durlock y chapas.'],
    ['Tornillo woods 8x2"', ['tornillo madera', 'woods'], 'caja', 'Tornillo de rosca gruesa para madera: une listones, bisagras y herrajes de carpintería.'],
    ['Tirafondo 8x3"', ['tirafondo', 'tirafondos'], 'paquete', 'Tornillo grueso de cabeza hexagonal que fija piezas pesadas a mampostería con taco. Soporta estanterías, portones y climatizadores.'],
    ['Bulón 3/8 x2"', ['bulón', 'perno'], 'paquete', 'Perno con tuerca que une piezas metálicas desmontables: estructuras, bisagras grandes y valvuladas.'],
    ['Tuerca 3/8', ['tuerca'], 'paquete', 'Rosca metálica que ajusta el bulón. Se compra siempre junto al perno.'],
    ['Arandela 3/8', ['arandela'], 'paquete', 'Disco metálico que reparte la fuerza de la tuerca y evita que se afloje con la vibración.'],
    ['Clavo 2" x1kg', ['clavo', 'clavos 2'], 'kg', 'Clavos de acero de dos pulgadas por kilo. El consumible de toda carpintería y encofrado.'],
    ['Clavo con cabeza 3" x1kg', ['clavo 3', 'clavo grueso'], 'kg', 'Clavo de tres pulgadas para estructuras de madera más pesadas y encofrados.'],
    ['Grampa 1kg', ['grampa', 'grampas'], 'kg', 'Clavos en U para fijar alambre de púas, mallas y cercos de madera.'],
    ['Taco expandido 8mm', ['tacos', 'tarugos', 'taco plástico'], 'paquete', 'Taco plástico que se perfora en el muro y recibe el tornillo: lo que sostiene cuadros, estanterías y vanidades.'],
    ['Buje autoperforante', ['bujes', 'pasamuro'], 'paquete', 'Casquillo que protege el paso de cables y caños por chapas y paredes delgadas.'],
    ['Candado 50mm', ['candado'], 'unidad', 'Candado de acero de 50 milímetros para portones, depósitos y medidores. Reforzado y resistente a la intemperie.'],
    ['Candado marina', ['candado marina', 'candado acero'], 'unidad', 'Candado reforzado con coraza de acero: el más seguro para el portón del frente o galpones.'],
    ['Bisagra puerta hierro 4"', ['bisagra hierro', 'bisagra puerta'], 'par', 'Bisagra pesada de hierro para puertas de chapa reforzada y portones. Se vende por par.'],
    ['Bisagra bronce puerta placa', ['bisagra bronce'], 'par', 'Bisagra de bronce para puertas internas de placa. Funciona silenciosa y no se oxida.'],
    ['Cerrojo de seguridad', ['cerrojo', 'tranca'], 'unidad', 'Traba de acero que se instala en puertas y portones como refuerzo de cierre. Se coloca del lado interior.'],
    ['Cadena de seguridad 1m', ['cadena seguridad', 'cadena candado'], 'unidad', 'Cadena de acero para asegurar portones, bicicletas y depósitos junto al candado.'],
    ['Alambre galvanizado 17', ['alambre galvanizado', 'alambre 17'], 'kg', 'Alambre de acero protegido contra óxido: cerca, soporte de plantas y atados de obra.'],
    ['Malla soldada 2x2', ['malla soldada 2x2'], 'rollo', 'Malla de acero soldado para cercos, jaulas y cerramientos de patios y quintas.'],
    ['Chapa acanalada 1.10x2.50', ['chapa acanalada', 'sinusoidal'], 'unidad', 'Chapa ondulada para cierres, portones y techos livianos. Se corta a medida en el corralón.'],
    ['Perfil C 100x50 x6m', ['perfil C', 'C 100'], 'barra', 'Perfil de acero en C de seis metros para estructuras: portones, techos y marcos de trabajo pesado.'],
    ['Tubo estructural 40x40', ['tubo 40', 'cuadrado 40'], 'barra', 'Tubo de acero cuadrado para armar portones, rejas, mesas y estructuras en general.'],
    ['Tubo estructural 25x25', ['tubo 25', 'caño 25'], 'barra', 'Tubo cuadrado liviano para rejas, repisas y marcos de chapa.'],
    ['Electrodo arco 2.5mm', ['soldadura arco', 'electrodos'], 'kg', 'Electrodos para soldadora de arco: unen piezas de hierro en estructuras, rejas y reparaciones.'],
    ['Disco corte 4.5"', ['disco corte'], 'unidad', 'Disco de corte para amoladora que corta hierro, chapa y acero. Consumible básico de herrería.'],
    ['Disco desbaste 4.5"', ['disco desbaste', 'disco lija'], 'unidad', 'Disco grueso que rebaja y empareja soldaduras y óxido antes de pintar.'],
    ['Pintura anticorrosiva 4L', ['anticorrosivo pintura'], 'lata', 'Pintura base que protege el metal del óxido antes del esmalte de terminación.'],
    ['Aceite desatascador 400ml', ['WD', 'desatascador', 'aceite multiuso'], 'unidad', 'Spray lubricante que destraba tuercas oxidadas, bisagras y cierres. Protege metal y saca la humedad.'],
    ['Cinta teflón industrial', ['teflón industrial'], 'unidad', 'Cinta selladora reforzada para roscas de agua y gas de mayor presión.'],
    ['Pinza de caño', ['pinza caño', 'tenaza'], 'unidad', 'Herramienta de agarre que aprieta caños y piezas redondas mientras se roscan o ajustan.'],
  ],
},
{
  slug: 'herramientas', name: 'Herramientas', icon: 'hammer', items: [
    ['Martillo de carpintero 27mm', ['martillo'], 'unidad', 'Martillo de mango de madera o fibra para clavar y sacar clavos. La herramienta número uno de cualquier caja.'],
    ['Destornillador Phillips 6x150', ['destornillador estrella', 'phillips'], 'unidad', 'Destornillador de punta estrella para tornillos de cruz. El más usado en electrodomésticos y herrajes.'],
    ['Destornillador plano 6x150', ['destornillador plano', 'pala'], 'unidad', 'Destornillador de punta plana para tornillos ranurados. Clásico de cañerías y griferías.'],
    ['Juego destornilladores x8', ['juego destornilladores'], 'juego', 'Set de destornilladores planos y de cruz en varios tamaños, a veces con aislación eléctrica. Cubre casi todo el trabajo de la casa.'],
    ['Pinza universal 8"', ['pinza', 'pinza universal'], 'unidad', 'Pinza de agarre con corte lateral: sujeta, dobla alambre y corta. La herramienta de mano más versátil.'],
    ['Pinza de corte diagonal', ['pinza corte', 'cortadora alambre'], 'unidad', 'Pinza de filo que corta alambres y cables limpiamente, en electricidad y herrería.'],
    ['Llave ajustable 10"', ['llave ajustable', 'inglesa'], 'unidad', 'Llave de boca regulable que ajusta tuercas y roscas de varios tamaños. La llave "inglesa" de toda la vida.'],
    ['Juego llaves combinadas x12', ['juego llaves', 'llaves combinadas'], 'juego', 'Set de llaves de boca y estrella de 8 a 19 milímetros para mecánica, plomería y armado de estructuras.'],
    ['Llave stilson 14"', ['stilson', 'llave caño'], 'unidad', 'Llave de mordaza dentada que agarra caños y accesorios roscados. La herramienta básica del plomero.'],
    ['Arco de sierra con hoja', ['arco sierra'], 'unidad', 'Arco metálico con hoja de dientes finos que corta metales, caños y PVC.'],
    ['Sierra de mano 22"', ['sierra mano', 'sierra'], 'unidad', 'Sierra de hoja ancha para cortar madera: listones, tableros y machimbre.'],
    ['Taladro percutor 650W', ['taladro', 'percutor'], 'unidad', 'Taladro eléctrico con función percusión para perforar muros con broca widia, además de madera y metal. La herramienta eléctrica más comprada.'],
    ['Atornilladora inalámbrica', ['atornilladora', 'tornilladora'], 'unidad', 'Atornilladora a batería de 12 o 18 voltios que arma muebles, fija herrajes y perfila sin cables. Viene con juego de puntas.'],
    ['Amoladora angular 4.5"', ['amoladora', 'angular'], 'unidad', 'Amoladora de 4 pulgadas y media que corta y desbasta metales con discos. Imprescindible en herrería.'],
    ['Caladora 550W', ['caladora'], 'unidad', 'Sierra eléctrica de hoja fina que hace cortes curvos en madera, durlock y plástico.'],
    ['Sierra circular 7.25"', ['sierra circular'], 'unidad', 'Sierra eléctrica de disco para cortes rectos y rápidos en tableros y listones de madera.'],
    ['Nivel de aluminio 60cm', ['nivel', 'nivel 60'], 'unidad', 'Regla con burbujas para verificar horizontal y vertical en montajes, revoques y aberturas.'],
    ['Nivel láser cruz', ['nivel láser', 'láser'], 'unidad', 'Proyector que marca líneas horizontales y verticales con láser: nivelar todo el ambiente en segundos.'],
    ['Cinta métrica 5m', ['cinta métrica', 'huincha'], 'unidad', 'Cinta retráctil de cinco metros para medir todo en obra y en la casa.'],
    ['Escuadra metálica 25cm', ['escuadra'], 'unidad', 'Regla en L que marca ángulos rectos exactos al cortar y armar.'],
    ['Trinquete 3/8 con dados', ['trinquete', 'juego dados'], 'juego', 'Llave de carraca con tubos intercambiables que ajusta tuercas rápido sin reposicionar la mano.'],
    ['Carretilla 70L', ['carretilla'], 'unidad', 'Carrito de una rueda para llevar arena, escombros y cemento por la obra.'],
    ['Pala ancha', ['pala', 'pala ancha'], 'unidad', 'Pala de hoja ancha para mezclar, cargar arena y nivelar.'],
    ['Pala de punta', ['pala punta'], 'unidad', 'Pala de punta para cavar zanjas y mover tierra firme.'],
    ['Pico y pala', ['pico'], 'unidad', 'Herramienta de dos puntas para romper suelo duro y cavar en terreno compacto.'],
    ['Escalera tijera aluminio 3 escalones', ['escalera tijera', 'escalera 3'], 'unidad', 'Escalera plegable de aluminio para trabajo doméstico: cambiar focos, pintar y arreglar repisas.'],
    ['Escalera extensible 6m', ['escalera extensible', 'escalera 6m'], 'unidad', 'Escalera telescópica de aluminio que alcanza techos y entrepisos. Para exteriores y obras.'],
    ['Anda de andamio plegable', ['anda', 'andamio plegable'], 'unidad', 'Plataforma plegable de aluminio de 1 a 2 metros para pintar y emparchar techos con seguridad.'],
    ['Broca widia 8mm', ['broca widia', 'broca muro'], 'unidad', 'Broca de punta de carburo para perforar muros y hormigón con taladro percutor.'],
    ['Broca HSS 8mm', ['broca HSS', 'broca metal'], 'unidad', 'Broca de acero rápido para metal, plástico y madera.'],
    ['Sierra copa 40mm', ['sierra copa'], 'unidad', 'Broca circular que perfora agujeros grandes en madera y durlock para tomas y caños.'],
    ['Guantes de trabajo par', ['guantes trabajo', 'guantes cuero'], 'par', 'Guantes resistentes para manipular materiales, cemento y herramientas sin lastimarse.'],
  ],
},
{
  slug: 'maderera', name: 'Maderera', icon: 'tree-pine', items: [
    ['Pino cepillado 2x4 x3m', ['pino 2x4', 'tirante pino'], 'barra', 'Listón de pino seco y cepillado de 2 por 4 pulgadas. El listón más usado en armados, quinchos y estructuras livianas.'],
    ['Pino cepillado 1x4 x3m', ['pino 1x4', 'tabla pino'], 'barra', 'Tabla fina de pino cepillado para estanterías, zapateros y armados de interior.'],
    ['Pino cepillado 1x6 x3m', ['pino 1x6'], 'barra', 'Tabla de pino de seis pulgadas para mesas de trabajo, tapas y estantes anchos.'],
    ['Tabla machimbre pino', ['machimbre', 'machimbre pino'], 'm2', 'Tablas con ranura y lengua que encajan entre sí para cielorrasos y revestimientos de madera.'],
    ['Deck madera 2.5x14', ['deck', 'tablón deck'], 'metro', 'Tablón ranurado resistente a la intemperie para pisos de madera en patios, galerías y piletas.'],
    ['Tablón pino 2x6 x4m', ['tablón pino', '2x6'], 'barra', 'Tablón grueso para estructuras vistas, escaleras y mobiliario de obra.'],
    ['Tirante eucalipto 3x4', ['eucalipto', 'tirante eucalipto'], 'barra', 'Listón de eucalipto tratado, más duro que el pino: tirantería de techos y estructuras que cargan peso.'],
    ['Quebracho blanco', ['quebracho'], 'barra', 'Madera dura argentina para tirantería y estructuras de techo de máxima resistencia.'],
    ['MDF 18mm 1.83x2.44', ['mdf 18', 'fibrofácil grueso'], 'placa', 'Tablero de fibra de madera de 18 milímetros para muebles, placards y puertas. Se corta y pinta fácil.'],
    ['MDF 3mm 1.83x2.44', ['mdf 3', 'fibrofácil'], 'placa', 'Tablero delgado de fibra para fondos de muebles, placards y paneles decorativos.'],
    ['Melamina blanca 18mm', ['melamina', 'melamina blanca'], 'placa', 'Tablero de partículas enchapado en blanco para muebles listos: placards, bajomesadas y estanterías.'],
    ['Melamina color 18mm', ['melamina color'], 'placa', 'Melamina enchapada en colores y maderas: muebles sin pintar con terminación de fábrica.'],
    ['OSB 11mm 1.22x2.44', ['OSB', 'osb 11'], 'placa', 'Tablero de virutas prensadas para techos, pisos y cerramientos rústicos. Aguanta la intemperie mejor que el MDF.'],
    ['Fibrocemento 4mm', ['fibrocemento'], 'placa', 'Placa de cemento y fibra para cielorrasos y paredes exteriores: no se quema ni se pudre.'],
    ['Moldura bastidor 2x1', ['moldura', 'bastidor'], 'metro', 'Moldura de madera que enmarca cuadros, espejos y puertas decorativas.'],
    ['Moldura marco puerta 7x3.5', ['marco moldura', 'moldura puerta'], 'metro', 'Moldura gruesa que termina el contorno de las puertas por dentro de la casa.'],
    ['Zócalo madera 2x1', ['zócalo madera'], 'metro', 'Listón que cubre la unión entre el piso y la pared: remate prolijo de todo piso de madera.'],
    ['Madera dura para piso', ['madera piso', 'entablerado'], 'm2', 'Tablas de madera dura para pisos interiores, se lijan y lacan una vez instaladas.'],
    ['Poste treatedo 10x10', ['poste', 'poste treatedo'], 'unidad', 'Poste de madera tratada para cercos, quinchos y pérgolas: aguanta la humedad enterrado.'],
    ['Listón para enmarcar 2x3', ['listón 2x3'], 'barra', 'Listón económico para bastidores, contrapisos de techo y armados internos.'],
    ['Trupán fenólico 18mm', ['trupán', 'tablero fenólico'], 'placa', 'Tablero estructural con chape fenólico para encofrados y muebles de obra resistentes.'],
    ['Woodfix adhesivo', ['woodfix', 'adhesivo madera'], 'unidad', 'Adhesivo potente de montaje para madera que reemplaza clavos en muchos armados.'],
  ],
},
{
  slug: 'carpinteria', name: 'Carpintería · Herrajes', icon: 'ruler', items: [
    ['Bisagra cazoleta 35mm', ['bisagra cazoleta', 'bisagra mueble'], 'par', 'Bisagra oculta para puertas de muebles de cocina y placard: se ve limpia desde afuera y regula en tres ejes.'],
    ['Corredera metálica 45cm', ['corredera', 'raíl cajón'], 'par', 'Rieles metálicos que permiten que el cajón deslice suavemente. El par va en cada cajón de cocina o escritorio.'],
    ['Corredera cierre suave 50cm', ['corredera blum', 'cierre suave'], 'par', 'Corredera con amortiguación que cierra el cajón sola y sin golpe. La más pedida en cocinas modernas.'],
    ['Rueda puerta placard', ['ruedas placard', 'rueda corrediza'], 'par', 'Ruedas que corren sobre el riel para puertas corredizas de placard y guardarropas.'],
    ['Guía placard inferior', ['guía placard', 'riel placard'], 'metro', 'Riel inferior donde corren las ruedas de las puertas corredizas del placard.'],
    ['Tirador cocina aluminio', ['tirador', 'tirador mueble'], 'unidad', 'Manija de aluminio para puertas y cajones de muebles: se atornilla desde adentro.'],
    ['Pata silla regulable', ['pata mueble', 'pata regulable'], 'unidad', 'Pata metálica con nivel regulable para muebles bajos de cocina y baño. Compensa pisos desparejos.'],
    ['Cantonera plástica', ['cantonera'], 'paquete', 'Esquinera plástica que protege y refuerza los cantos de los muebles.'],
    ['Tapacantos melamina', ['tapacantos'], 'metro', 'Cinta de melamina que cubre el canto cortado de las placas de muebles. Se pega con plancha o hierro.'],
    ['Adhesivo vinílico 1L', ['cola vinílica', 'colapebo'], 'lata', 'Cola blanca para unir maderas: la cola de carpintería clásica. Seca transparente y muy fuerte.'],
    ['Cola de contacto 1L', ['cola contacto', 'pegamento contacto'], 'lata', 'Adhesivo instantáneo que pega al juntar las piezas: para chapas, formica y hules de mesa.'],
    ['Cierre de placard golondrina', ['cierre placard', 'golondrina'], 'unidad', 'Cierre doble puerta para placards y muebles, con llave o sin ella.'],
    ['Picaporte esférico', ['picaporte', 'pomo'], 'unidad', 'Manija esférica de puerta interna con o sin cerradura. Se instala sobre la placa.'],
    ['Manijón palanca', ['manijón', 'manija puerta'], 'unidad', 'Manija de palanca para puertas de entrada e interiores, con rosca o embutida según el modelo.'],
    ['Barniz laca satinada 1L', ['laca', 'laca satinada'], 'lata', 'Laca que da terminación satinada a muebles de madera: protege y decora.'],
    ['Pasador bisagra 3mm', ['pasador bisagra', 'eje bisagra'], 'paquete', 'Pasadores que reparan bisagras desgastadas sin cambiar la pieza completa.'],
  ],
},
{
  slug: 'techos', name: 'Techos · Impermeabilización', icon: 'house', items: [
    ['Chapa sinusoidal 1.10x4m', ['chapa sinusoidal', 'chapa 4m'], 'unidad', 'Chapa galvanizada ondulada de cuatro metros para techos y galpones. La chapa de techo clásica y económica.'],
    ['Chapa sinusoidal pintada 4m', ['chapa pintada', 'chapa color'], 'unidad', 'Chapa ondulada con pintura preformada que resiste el sol sin oxidarse: techo listo sin pintar.'],
    ['Chapa lisa galvanizada', ['chapa lisa', 'galvanizada'], 'unidad', 'Chapa plana para canaletas, zinguería, flashings y reparaciones de techo.'],
    ['Cenefa cumbrera 2m', ['cumbrera', 'cenefa'], 'unidad', 'Pieza que tapa el encuentro de las chapas en la cima del techo. Impide que el agua entre por la cumbre.'],
    ['Flashings de chapa', ['flashing', 'bavetas'], 'unidad', 'Piezas de chapa doblada a medida que sellan el techo contra muros, chimeneas y salidas.'],
    ['Aislante telgopor 5mm', ['aislante', 'telgopor'], 'rollo', 'Placa o rollo de poliestireno que va bajo la chapa para bajar el calor y el ruido del techo.'],
    ['Lana de vidrio 50mm', ['lana vidrio'], 'rollo', 'Manta fibrosa aislante térmica y acústica para techos y paredes. Baja el calor del techo de chapa notablemente.'],
    ['Film barrera de vapor', ['barrera vapor', 'film'], 'rollo', 'Lámina plástica que va bajo el aislante para que la humedad del ambiente no moje la lana de vidrio.'],
    ['Membrana asfáltica rollo 10m', ['membrana rollo', 'membrana asfáltica'], 'rollo', 'Rollo asfáltico con aluminio o poliéster que se sopretea sobre la terraza: impermeabilización definitiva de techos.'],
    ['Membrana líquida 20kg', ['membrana líquida'], 'tambor', 'Emulsión elástica que se pinta en techos y terrazas para impermeabilizar sin soplete.'],
    ['Canaleta galvanizada 2m', ['canaleta', 'canaleta galvanizada'], 'unidad', 'Canaleta de chapa que recoge el agua del techo y la manda a la bajada. Se apoya en el borde del techo.'],
    ['Canaleta PVC 2m', ['canaleta PVC'], 'unidad', 'Canaleta de plástico liviana que no se oxida, con uniones y boquillas de bajada.'],
    ['Bajada de lluvia 2m', ['bajada', 'caño bajada'], 'unidad', 'Tubo vertical que lleva el agua de la canleta al piso o al desagüe pluvial.'],
    ['Bufarrón plástico', ['bufarrón'], 'unidad', 'Pieza que recoge el agua de varias canaletas y la envía a una sola bajada.'],
    ['Tornillo autoperforante techo', ['tornillo techo', 'puntera'], 'caja', 'Tornillo con arandela de goma que fija la chapa a la estructura sin dejar entrar agua.'],
    ['Cinta butílica', ['cinta butílica'], 'rollo', 'Cinta adhesiva asfáltica que sella juntas y superposiciones de chapas y membranas.'],
    ['Sellador acrílico techo', ['sellador acrílico'], 'lata', 'Masilla elástica para sellar rajaduras, juntas y detalles de techos antes o junto con la membrana.'],
    ['Zinc cromato', ['zinc cromato', 'fondo zinc'], 'lata', 'Pintura base para chapa galvanizada antes del esmalte: hace que la pintura agarre sobre el zinc.'],
  ],
},
{
  slug: 'cerramientos', name: 'Aberturas · Cerramientos', icon: 'door-open', items: [
    ['Puerta placa 0.80', ['puerta placa', 'puerta interior'], 'unidad', 'Puerta lisa interna de 80 centímetros de ancho, sin marco ni herrajes: la más común en dormitorios y baños.'],
    ['Puerta placa 0.70', ['puerta 070'], 'unidad', 'Puerta interna de 70 centímetros para baños, lavaderos y ambientes chicos.'],
    ['Marco puerta chapa 0.80', ['marco puerta', 'premarco'], 'unidad', 'Marco de chapa que se pega al muro y recibe la puerta placa. Vende por separado de la puerta.'],
    ['Puerta chapa reforzada 0.90', ['puerta reforzada', 'puerta entrada'], 'unidad', 'Puerta de chapa reforzada con cerradura de seguridad para entradas de casas y departamentos.'],
    ['Puerta aluminio 1x2.05', ['puerta aluminio'], 'unidad', 'Puerta de aluminio con vidrio para entradas y frentes: no se oxida y no necesita pintura.'],
    ['Ventana aluminio 1.2x1.1', ['ventana aluminio'], 'unidad', 'Ventana corrediza de aluminio con vidrio flotado. La medida más vendida para dormitorios.'],
    ['Ventana aluminio 1.5x1.1', ['ventana 15'], 'unidad', 'Ventana corrediza de aluminio de metro y medio para living y comedor.'],
    ['Ventana PVC doble vidrio', ['ventana PVC', 'DVH'], 'unidad', 'Ventana de PVC con doble vidrio hermético: aísla del ruido y el frío mucho mejor que el aluminio simple.'],
    ['Puerta balcón aluminio', ['puerta balcón'], 'unidad', 'Abertura corrediza grande de aluminio que conecta el living con el balcón o la galería.'],
    ['Portón corredizo chapa', ['portón', 'portón corredizo'], 'unidad', 'Portón de chapa para entradas de autos, deslizable sobre riel. Se fabrica a medida en herrería.'],
    ['Reja de protección', ['reja'], 'unidad', 'Reja de hierro que protege ventanas bajas y entradas sin quitar luz ni aire.'],
    ['Mosquitero corredizo', ['mosquitero'], 'unidad', 'Malla con marco de aluminio que impide mosquitos sin cerrar la ventana. Se corre junto a la abertura.'],
    ['Vidrio flotado 4mm m²', ['vidrio 4mm', 'vidrio común'], 'm2', 'Vidrio liso de cuatro milímetros para ventanas y espejos. Se vende por metro cuadrado cortado a medida.'],
    ['Vidrio laminado 5+5', ['vidrio laminado'], 'm2', 'Dos vidrios unidos con lámina de seguridad: si se rompe no salen pedazos. Ideal en puertas de vidrio y frentes.'],
    ['Vidrio templado 8mm', ['vidrio templado'], 'm2', 'Vidrio tratado al calor que resiste golpes y, si se rompe, se parte en pedacitos no cortantes. Para mamparas y mesadas.'],
    ['Espejo 4mm', ['espejo'], 'm2', 'Espejo cortado a medida para baños, placards y vestidores.'],
    ['Cerradura embutir código', ['cerradura embutir', 'cerradura código'], 'unidad', 'Cerradura de embutir con cierre por llave y picaporte. La estándar de las puertas de placa.'],
    ['Cerradura sobreponer', ['cerradura sobreponer'], 'unidad', 'Cerradura que se instala sobre la puerta sin embutir, típica de puertas de madera maciza y refuerzos.'],
    ['Cilindro de seguridad', ['cilindro', 'bombín'], 'unidad', 'Cilindro con llave de puntos que se cambia sin tocar la cerradura: más seguridad sin cambiar toda la puerta.'],
    ['Ojo mágico', ['ojo mágico'], 'unidad', 'Lente de visión que permite ver quién está afuera de la puerta sin abrir.'],
    ['Borroa puerta', ['borroa', 'felpa puerta'], 'metro', 'Felpa que se pega al borde de la puerta para que no pase polvo, luz ni agua debajo.'],
    ['Motor portón corredizo', ['motor portón', 'automatismo'], 'unidad', 'Motor con control remoto que abre y cierra el portón de la casa. Incluye riel y fotocélulas.'],
  ],
},
{
  slug: 'pisos', name: 'Pisos · Revestimientos', icon: 'layout-grid', items: [
    ['Cerámico m²', ['cerámico', 'cerámica piso'], 'm2', 'Piso cerámico esmaltado que se vende por metro cuadrado: el piso de por vida más económico para cocina, baño y lavadero.'],
    ['Porcelanato m²', ['porcelanato'], 'm2', 'Piso de porcelana de alta resistencia y diseño moderno, imita maderas, piedras y cemento. No absorbe agua y se usa en toda la casa.'],
    ['Ceramón 30x30', ['ceramón'], 'm2', 'Mosaico cerámico de 30 por 30 muy resistente, típico de patios, lavaderos y garajes.'],
    ['Granito pulido m²', ['granito'], 'm2', 'Piso de granito natural pulido para living y frentes: duro, brillante y eterno.'],
    ['Piso flotante m²', ['piso flotante'], 'm2', 'Piso de madera o laminado que se monta sin pegamento sobre una base: cálido, rápido de instalar y renovable.'],
    ['Piso vinílico click', ['vinílico', 'SPC'], 'm2', 'Piso vinílico rígido de encastrar: 100% resistente al agua, ideal para cocinas, baños y renovaciones sobre piso viejo.'],
    ['Alfombra sintética m²', ['alfombra'], 'm2', 'Alfombra de fibra sintética en rollo o placa para dormitorios. Cálida y silenciosa.'],
    ['Base piso flotante', ['base flotante', 'espuma base'], 'm2', 'Lámina de espuma que va bajo el piso flotante: nivel y aislación acústica.'],
    ['Adhesivo cerámico 30kg', ['pegamento cerámico', 'cemento pegamento'], 'bolsa', 'Bolsa de adhesivo en polvo que pega el cerámico o porcelanato al contrapiso. Se mezcla con agua y se aplica con peine.'],
    ['Pastina', ['pastina', 'junta cerámico'], 'kg', 'Polvo pigmentado que rellena las juntas entre cerámicos después de colocados. Da el color final al piso.'],
    ['Junta flexible siliconada', ['junta flexible'], 'unidad', 'Sellador elástico para juntas de dilatación de pisos y paredes: evita que el cerámico se levante.'],
    ['Contrapiso autonivelante', ['autonivelante', 'autolivellante'], 'bolsa', 'Mezcla que se vuelca sobre el piso y se nivela sola, dejando una superficie perfecta para colocar flotante o vinílico.'],
    ['Imprimación pisos', ['imprimación piso', 'primer piso'], 'lata', 'Líquido que sella el contrapiso antes de pegar cerámicos o volcar autonivelante. Mejora el agarre.'],
    ['Zócalo cerámico', ['zócalo cerámico'], 'metro', 'Cerámico de contorno que va pegado en la base de la pared a juego con el piso.'],
    ['Mosaico pegadizo baño', ['mosaico', 'pegadizo'], 'm2', 'Mosaicos pequeños en placas de malla o papel para paredes de baño y cocinas: diseños decorativos.'],
    ['Placa SPC refill', ['SPC refill', 'vinílico reposición'], 'm2', 'Repuesto de vinílico para reparar tablas dañadas sin rehacer todo el piso.'],
    ['Piso de cemento alisado', ['alisado', 'cemento alisado'], 'bolsa', 'Mezcla que se aplica como terminación final del piso en estilo industrial, sin cerámico encima.'],
    ['Tratamiento antihumedad piso', ['antihumedad piso'], 'litro', 'Producto que se aplica sobre el contrapiso para cortar la humedad de ascenso antes del piso final.'],
  ],
},
{
  slug: 'aislacion', name: 'Aislación', icon: 'layers', items: [
    ['Lana de vidrio 50mm rollo', ['lana vidrio rollo'], 'rollo', 'Rollo de manta fibrosa que aísla térmica y acústicamente techos y paredes. Baja el calor del verano y el ruido de la calle.'],
    ['Lana de roca 60mm', ['lana roca'], 'rollo', 'Aislante de fibra mineral más denso que el vidrio: aísla y además resiste el fuego. Ideal en parrillas y salas de máquinas.'],
    ['Poliestireno placa 2cm', ['telgopor placa', 'poliestireno'], 'placa', 'Placa de telgopor para aislar paredes y cielorrasos. Liviana y económica.'],
    ['Poliestireno placa 5cm', ['telgopor 5cm'], 'placa', 'Placa gruesa de poliestireno para techos y pisos con más demanda térmica.'],
    ['Espuma poliuretano aerosol', ['espuma PU', 'polyurethane spray'], 'unidad', 'Espuma en aerosol que se expande y rellena huecos, pasacables y juntas: aísla y fija al mismo tiempo.'],
    ['Film barrera de vapor', ['barrera vapor'], 'rollo', 'Lámina de polietileno que bloquea el vapor de agua hacia el aislante. Obligatoria en techos con lana.'],
    ['Geotextil 2m', ['geotextil', 'manta geomembrana'], 'metro', 'Manta tejida que separa tierra, piedra y agua en canteros, techos verdes y drenajes.'],
    ['Cinta aluminio 50mm', ['cinta aluminio'], 'rollo', 'Cinta metálica que sella juntas de aislantes y caños de aire acondicionado. Refleja el calor.'],
    ['Burlete espuma autoadhesivo', ['burlete', 'burlete puerta'], 'rollo', 'Cinta de espuma que se pega en marcos de ventanas y puertas para cortar el paso de aire y polvo.'],
    ['Burlete silicona puerta', ['burlete silicona'], 'unidad', 'Burlete flexible de silicona para la base de la puerta: corta la corriente de aire bajo la hoja.'],
    ['Aislante Celulosa soplado', ['celulosa'], 'kg', 'Aislante de celulosa reciclada que se sopla en cielorrasos y paredes: cubre todo sin juntas.'],
    ['Radier aislante 3cm', ['radier', 'aislante piso'], 'placa', 'Placa rígida que va bajo la losa o el piso para aislar la humedad y el frío del suelo.'],
  ],
},
{
  slug: 'climatizacion', name: 'Climatización', icon: 'air-vent', items: [
    ['Aire acondicionado 3000 frío/calor', ['split 3000', 'aire 3000'], 'unidad', 'Split de 3000 frigorías que enfría y calienta: alcanza para un living o dormitorio grande. Requiere instalación especializada.'],
    ['Aire acondicionado 4500 frío/calor', ['split 4500'], 'unidad', 'Split de 4500 frigorías para ambientes grandes o salas combinadas.'],
    ['Aire acondicionado 6000 frío/calor', ['split 6000'], 'unidad', 'Equipo de 6000 frigorías para plantas completas, locales y salones.'],
    ['Caña refrigerada 1/4"', ['caña aire', 'caña split'], 'metro', 'Caño de cobre aislado por donde circula el refrigerante entre la unidad interna y externa del split.'],
    ['Cable aire 2x1.5', ['cable split', 'cable aire'], 'metro', 'Cable específico para conectar el split a la térmica dedicada.'],
    ['Soporte aire pared', ['soporte split', 'soporte condensadora'], 'par', 'Soportes metálicos que sostienen la unidad exterior del aire en la fachada.'],
    ['Bomba condensado', ['bomba condensado'], 'unidad', 'Bomba chiquita que expulsa el agua que destila el aire hacia el desagüe cuando la gravedad no alcanza.'],
    ['Filtro aire split', ['filtro split'], 'unidad', 'Filtro interior del split que retiene polvo: se lava y se repone cada temporada.'],
    ['Estufa eléctrica 2000W', ['estufa eléctrica'], 'unidad', 'Estufa eléctrica portátil de dos mil vatios con termostato. Calor instantáneo sin instalación.'],
    ['Panel eléctrico 1000W', ['panel eléctrico', 'panel calórico'], 'unidad', 'Panel de pared que calienta por radiación natural: silencioso y sin viento, ideal para dormitorios.'],
    ['Radiador eléctrico de aceite', ['radiador aceite'], 'unidad', 'Radiador portátil de aceite que mantiene el calor horas después de apagarse.'],
    ['Calefactor TBC 5000', ['calefactor', 'TBC'], 'unidad', 'Estufa de gas sellada con tiro balanceado para ambientes cerrados: la calefacción más económica con gas natural.'],
    ['Ventilador de techo', ['ventilador techo'], 'unidad', 'Ventilador de techo con aspas y luces opcionales: renueva el aire y baja la sensación térmica en verano.'],
    ['Ventilador de pie 50cm', ['ventilador pie'], 'unidad', 'Ventilador de pie potente y regulable para el verano de toda casa.'],
    ['Turbo ventilador', ['turbo', 'turbo ventilador'], 'unidad', 'Ventilador de alta potencia con giro amplio que refresca salones y patios cubiertos.'],
    ['Extractor de aire', ['extractor'], 'unidad', 'Ventilador de pared o vidrio que saca el aire húmedo y con olor de baños, cocinas y lavaderos.'],
    ['Deshumidificador', ['deshumidificador'], 'unidad', 'Equipo que saca la humedad del ambiente: evita moho en cuartos húmedos y guardillas.'],
    ['Purificador de aire', ['purificador'], 'unidad', 'Equipo que filtra polvo y alérgenos del ambiente. Ideal para dormitorios y casas con mascotas.'],
    ['Funda exterior split', ['funda split'], 'unidad', 'Cubierta protectora para la unidad exterior del aire contra lluvia y hojas.'],
  ],
},
{
  slug: 'jardineria', name: 'Jardín y Exterior', icon: 'leaf', items: [
    ['Tierra fértil 40kg', ['tierra', 'black soil', 'tierra negra'], 'bolsa', 'Bolsa de tierra fértil para canteros, macetas y césped: la base de todo jardín.'],
    ['Humus lombriz 10kg', ['humus'], 'bolsa', 'Abono orgánico de lombriz que nutre la tierra naturalmente. Se mezcla en canteros y macetas.'],
    ['Sustrato para macetas', ['sustrato', 'tierra para macetas'], 'bolsa', 'Mezcla liviana especial para macetas: retiene agua sin encharcar y da aire a las raíces.'],
    ['Semilla césped 5kg', ['semilla césped', 'pasto'], 'bolsa', 'Semillas de pasto para sembrar o reponer el césped del jardín. Se siembra en otoño y primavera.'],
    ['Césped pan m²', ['pan de césped', 'césped en pan'], 'm2', 'Césped ya crecido en panes que se colocan y el jardín queda listo en un día.'],
    ['Césped artificial', ['pasto artificial'], 'm2', 'Pasto sintético para patios y balcones sin riego ni corte. Se coloca en m².'],
    ['Abono orgánico 5kg', ['abono', 'fertilizante'], 'bolsa', 'Fertilizante que se esparce sobre la tierra para que las plantas crezcan fuertes y verdes.'],
    ['Maceta 30cm', ['maceta'], 'unidad', 'Maceta plástica o cerámica de treinta centímetros para plantas de interior y balcón.'],
    ['Maceta gargantilla 12cm', ['maceta chica', 'gargantilla'], 'unidad', 'Maceta de doce centímetros para plantines y cactus.'],
    ['Manguera 15m', ['manguera'], 'unidad', 'Manguera de quince metros con conectores rápidos para regar el jardín o lavar el patio.'],
    ['Aspersor giratorio', ['aspersor', 'rociador'], 'unidad', 'Aspersor que se conecta a la manguera y riega en círculo automáticamente.'],
    ['Kit riego por goteo', ['goteo', 'riego goteo'], 'juego', 'Kit de cañitos y goteros que riegan las plantas de a poquito: ahorra agua y riega mientras no estás.'],
    ['Tijera podar', ['tijera podar'], 'unidad', 'Tijera de poda con resorte y hoja afilada para ramas finas y plantas.'],
    ['Sierra de poda', ['sierra poda'], 'unidad', 'Sierra curva para ramas gruesas que la tijera no corta.'],
    ['Cortacésped eléctrico', ['cortacésped', 'cortadora pasto'], 'unidad', 'Máquina eléctrica o a nafta que corta el césped parejo en minutos.'],
    ['Bordeadora', ['bordeadora', 'orilladora'], 'unidad', 'Máquina que corta el pasto en los bordes donde el cortacésped no llega: contra paredes y senderos.'],
    ['Desmalezadora', ['desmalezadora'], 'unidad', 'Máquina de hilo o disco que corta pasto alto y maleza en terrenos grandes.'],
    ['Sopladora hojas', ['sopladora'], 'unidad', 'Máquina que junta hojas y escombros con soplado de aire. Ordena el patio rápido.'],
    ['Rastrillo 14 dientes', ['rastrillo'], 'unidad', 'Peine de dientes metálicos que junta hojas y nivela la tierra antes de sembrar.'],
    ['Regadera 10L', ['regadera'], 'unidad', 'Recipiente con chorro difusor para regar plantas de cerca con cuidado.'],
    ['Pala de jardín', ['pala jardín'], 'unidad', 'Pala más chica y liviana que la de obra, para cavar en canteros.'],
    ['Tijera seto', ['tijera seto', 'tijera largo mango'], 'unidad', 'Tijera de mango largo para recortar cercos y arbustos parejos.'],
    ['Malla sombra 50%', ['malla sombra'], 'm2', 'Tela que filtra la mitad del sol para proteger plantas, galerías y autos.'],
    ['Piedra bolas decorativa', ['piedra bolas'], 'kg', 'Piedras redondeadas para canteros, frentes y drenajes decorativos.'],
    ['Grava partida', ['grava', 'piedra chica'], 'kg', 'Piedra partida chica para caminos, drenajes y decoración de jardín.'],
    ['Poste alambrado perimetral', ['poste alambrado'], 'unidad', 'Postes de madera o hormigón que sostienen el alambrado del perímetro del terreno.'],
    ['Alambrado de púas rollo', ['púas', 'alambre púa'], 'rollo', 'Rollo de alambre con púas para cerrar terrenos y quintas.'],
    ['Parrilla prefab hormigón', ['parrilla hormigón', 'horno barro'], 'unidad', 'Parrilla u horno preformado de hormigón refractario que se arma en el patio y queda fijo.'],
    ['Repisa exterior balcon', ['repisa exterior', 'estante balcón'], 'unidad', 'Estante de hierro o madera tratada para balcones y patios.'],
    ['Luz solar jardín', ['luces solares'], 'unidad', 'Farolas solares que cargan de día e iluminan el sendero de noche sin cableado.'],
  ],
},
{
  slug: 'limpieza', name: 'Limpieza · Mantenimiento', icon: 'spray-can', items: [
    ['Lavandina 5L', ['lavandina', 'cloro'], 'bidón', 'Blanqueador a base de cloro para pisos, baños y ropa. Desinfecta y mata el moho.'],
    ['Detergente 5L', ['detergente'], 'bidón', 'Jabón líquido concentrado para pisos, platos y superficies de uso diario.'],
    ['Desinfectante 5L', ['desinfectante', 'ayudín'], 'bidón', 'Desinfectante perfumado para pisos y baños que deja aroma por horas.'],
    ['Alcohol en gel 1L', ['alcohol gel'], 'unidad', 'Antiséptico en gel para manos y superficies sin agua.'],
    ['Limpiador multiuso 750ml', ['multiuso', 'limpiador'], 'unidad', 'Spray limpiador para cocina, baño y vidrios en un solo producto.'],
    ['Quitagrasa 750ml', ['quitagrasa'], 'unidad', 'Producto fuerte que disuelve grasa quemada de hornallas, campanas y parrillas.'],
    ['Ácido muriático 5L', ['ácido', 'muriático'], 'bidón', 'Ácido fuerte para limpiar cemento, cerámicos nuevos y desodorar cañerías. Se usa con guantes y con cuidado.'],
    ['Desengrasante industrial 5L', ['desengrasante'], 'bidón', 'Desengrasante concentrado para garajes, parrillas y máquinas.'],
    ['Escoba fibra', ['escoba'], 'unidad', 'Escoba de fibra plástica con mango largo para barrer pisos y patios.'],
    ['Secador piso 60cm', ['secador', 'jala piso'], 'unidad', 'Aparato de goma con mango que junta el agua y la suciedad mojada del piso.'],
    ['Trapo piso pack x3', ['trapo piso', 'trapos'], 'paquete', 'Trapos de microfibra o algodón para secar y lustrar el piso con el secador.'],
    ['Esponja doble uso x5', ['esponja'], 'paquete', 'Esponjas de una cara rugosa y otra suave para fregar platos y superficies.'],
    ['Guantes látex par', ['guantes'], 'par', 'Guantes de látex o nitrilo para proteger las manos al limpiar con químicos.'],
    ['Bolsa residuos x50', ['bolsas basura', 'bolsas residuos'], 'paquete', 'Rollo de bolsas plásticas reforzadas para la basura de la casa.'],
    ['Balde 12L con escurridor', ['balde'], 'unidad', 'Balde plástico con escurridor de trampa para lavar pisos cómodamente.'],
    ['Cera líquida pisos brillante', ['cera piso', 'cera líquida'], 'litro', 'Cera que se aplica sobre el piso limpio para dar brillo y proteger el material.'],
    ['Desodorante ambiente aerosol', ['desodorante ambiente'], 'unidad', 'Aerosol que perfuma y neutraliza olores de ambientes y baños.'],
    ['Jabón de lavar barra', ['jabón', 'jabón barra'], 'unidad', 'Jabón clásico en barra para lavar a mano ropa y superficies.'],
    ['Paño microfibra x3', ['microfibra', 'paños'], 'paquete', 'Paños de microfibra que sacan el polvo y limpian vidrios sin dejar pelusa.'],
    ['Vidriolimpiador 750ml', ['limpiavidrios'], 'unidad', 'Limpiador de vidrios y espejos que seca sin dejar marcas.'],
  ],
},
{
  slug: 'muebles', name: 'Muebles · Equipamiento', icon: 'armchair', items: [
    ['Cocina 4 hornallas acero', ['cocina', 'hornallas acero'], 'unidad', 'Cocina de acero inoxidable con horno y cuatro hornallas a gas. El equipamiento central de la cocina.'],
    ['Campana extractora', ['campana', 'extractor cocina'], 'unidad', 'Campana que extrae el humo y el olor de la cocina hacia afuera o con filtros de carbón.'],
    ['Mesada acero inox 1.20', ['mesada acero', 'mesada inox'], 'unidad', 'Mesada de acero inoxidable con bacha integrada para cocinas: higiénica y eterna.'],
    ['Mesada granito m²', ['mesada granito'], 'm2', 'Mesada de granito natural a medida con bacha y drenaje. Resiste calor y rayones.'],
    ['Bacha acero inoxidable', ['bacha', 'bacha cocina'], 'unidad', 'Bacha de acero de una o dos cubetas que se embute en la mesada.'],
    ['Bacha cerámica blanca', ['bacha cerámica'], 'unidad', 'Bacha de porcelana para lavatorio de baño, sobre mesada o embutida.'],
    ['Bajo mesada melamina', ['bajomesada', 'mueble cocina'], 'unidad', 'Mueble de melamina que va bajo la mesada con puertas y estantes. Organiza toda la cocina.'],
    ['Alacena cocina 2 puertas', ['alacena'], 'unidad', 'Mueble alto de cocina que se instala sobre la mesada: guardado extra a la vista.'],
    ['Placard 2 puertas', ['placard', 'guardarropa'], 'unidad', 'Placard de dos puertas corredizas con barra y estantes interiores para el dormitorio.'],
    ['Estantería rack metálica', ['rack', 'estantería'], 'unidad', 'Estantería metálica de cinco bandejas para garage, baulera y depósito. Sostiene cajas pesadas.'],
    ['Mueble de baño suspendido', ['mueble baño'], 'unidad', 'Mueble flotante con bacha integrada que deja el piso libre: moderno y fácil de limpiar.'],
    ['Biblioteca estantería 5 baldas', ['biblioteca'], 'unidad', 'Estantería abierta de cinco estantes para living, estudio o habitación.'],
    ['Escritorio 1.20', ['escritorio', 'mesa trabajo'], 'unidad', 'Mesa de trabajo de un metro veinte para home office y estudio.'],
    ['Silla de trabajo', ['silla', 'silla escritorio'], 'unidad', 'Silla ergonómica regulable para escritorio y home office.'],
    ['Mesada baranda cromo', ['baranda mesada', 'baranda cocina'], 'metro', 'Baranda de acero que se instala sobre la mesada para colgar utensilios.'],
    ['Puerta placard espejada', ['puerta espejo', 'placard espejo'], 'unidad', 'Puerta corrediza de placard con espejo integrado: viste y agranda el dormitorio.'],
  ],
},
{
  slug: 'seguridad', name: 'Seguridad · Protección', icon: 'shield-check', items: [
    ['Casco de obra', ['casco'], 'unidad', 'Casco plástico que protege la cabeza de golpes y caídas de material en obra.'],
    ['Antiparras claras', ['antiparras'], 'unidad', 'Antiparras de policarbonato que protegen los ojos al taladrar, amolar y lijarnos.'],
    ['Protector auditivo', ['auriculares protección', 'taponcitos'], 'unidad', 'Orejeras o tapones que bajan el ruido de amoladoras y perforadoras.'],
    ['Mascarilla P2 x10', ['mascarilla', 'P2', 'N95'], 'paquete', 'Mascarilla de partículas que filtra polvo de cemento, arena y madera al lijar y amolar.'],
    ['Guantes nylon con nitrilo', ['guantes nylon'], 'par', 'Guantes livianos con palma antideslizante para trabajos finos y carga de materiales.'],
    ['Guantes cuero soldador', ['guantes soldador'], 'par', 'Guantes de cuero grueso que protegen de chispas y calor al soldar y amolar.'],
    ['Calzado seguridad punta acero', ['botas seguridad', 'zapatillas seguridad'], 'par', 'Calzado con punta de acero que protege el pie de caídas de objetos pesados en obra.'],
    ['Arnés de seguridad con cinta', ['arnés', 'cintos seguridad'], 'unidad', 'Arnés completo con cabo de vida para trabajar en alturas: obligatorio en techos y andamios.'],
    ['Cinta señalización 200m', ['cinta peligro'], 'rollo', 'Cinta plástica llamativa que valla la zona de trabajo y advierte del peligro.'],
    ['Extintor ABC 2.5kg', ['extintor', 'matafuego'], 'unidad', 'Matafuego polivalente para casa y obra: apaga fuego de madera, líquidos y electricidad.'],
    ['Kit primeros auxilios', ['botiquín'], 'unidad', 'Botiquín con vendas, gasas, antisépticos y guantes para atender heridas menores.'],
    ['Alarma sensor movimiento', ['alarma movimiento'], 'unidad', 'Sensor que dispara una alarma sonora al detectar movimiento: disuade intrusos en obras y casas.'],
  ],
},
];

// Vocabulario de unidades de venta (para formularios y tooltips)
export const UNIT_LABELS = {
  unidad: 'unidad', par: 'par', juego: 'juego', pack: 'pack', millar: 'millar',
  metro: 'metro', m2: 'm²', m3: 'm³', kg: 'kg', litro: 'litro',
  bolsa: 'bolsa', paquete: 'paquete', caja: 'caja', rollo: 'rollo', placa: 'placa',
  tira: 'tira', tambor: 'tambor', barra: 'barra', bobina: 'bobina', lata: 'lata', bidón: 'bidón',
};

