// Expansión 2 del catálogo HomIA — parte D
// climatizacion · jardineria · limpieza · muebles · seguridad
// Formato: [nombre, [aliases], unidad, descripción natural]
export const CATALOG_EXP2_D = {
  climatizacion: [
    ['Aire acondicionado 7500 frío/calor', ['aire 7500', 'split 7500'], 'unidad', 'Split de siete mil quinientas para ambientes grandes: living comedor de casa grande o local comercial chico.'],
    ['Aire acondicionado 9000 frío/calor', ['aire 9000', 'split 9000'], 'unidad', 'Split de nueve mil para dobles alturas, salones y comercios: potencia de verdad con control inverter.'],
    ['Aire ventana 3000 frío/calor', ['aire de ventana', 'aire pared 3000'], 'unidad', 'Aire de ventana clásico que se monta en muro o ventana: sin instalador de split, calefacción y frío directo.'],
    ['Calefactor TBC 3000', ['calefactor tbc 3000', 'tiro balanceado 3000'], 'unidad', 'Tiro balanceado chico para dormitorios y oficinas: aire de afuera para la combustión, gases para afuera, seguridad total.'],
    ['Calefactor tiro balanceado 3000', ['tiro balanceado 3000', 'calefactor 3000'], 'unidad', 'Calefactor de tres mil calorías para ambientes medianos: calefacción limpia a gas con panel estético.'],
    ['Estufa encastre 5000 kcal', ['estufa encastre', 'estufa empotrable gas'], 'unidad', 'Estufa a gas que se empotra en el mueble o muro: calefacción potente invisible cuando no se usa.'],
    ['Chimenea eléctrica decorativa', ['chimenea electrica', 'estufa chimenea'], 'unidad', 'Chimenea con llama LED y calentador de aire: ambiente de hogar a leña sin humo ni leña.'],
    ['Caño espiral aluminio 6m', ['cano espiral 6', 'tubo flexible aire'], 'unidad', 'Caño flexible de aluminio de seis metros para conductos de aire y desagües de split: se estira y se curva donde haga falta.'],
    ['Extractor 250mm', ['extractor grande', 'extractor 25'], 'unidad', 'Extractor de aire de veinticinco centímetros con aletas regulables para baños, cocinas y talleres: saca el aire pesado de una vez.'],
    ['Extractor 150mm', ['extractor chico', 'extractor 15'], 'unidad', 'Extractor de quince centímetros para baño y lavadero: silencioso, ideal para uso permanente.'],
    ['Difusor de aire lineal', ['difusor lineal', 'rejilla difusora'], 'unidad', 'Rejilla de doble deflector que reparte el aire del split o canaleta sin tirar frío directo a la cabeza.'],
    ['Rejilla de retorno', ['rejilla retorno', 'rejilla plastica'], 'unidad', 'Rejilla de toma de aire para canaletas y conductos: con filtro lavable, mantiene el circuito limpio.'],
    ['Repuesto filtro carbón activado', ['filtro carbon', 'repuesto purificador'], 'unidad', 'Filtro de carbón activado para purificadores: absorbe olores de cocina, humo y mascotas. Cambiarlo cada seis meses.'],
    ['Kit instalación split 3m', ['kit split 3', 'caña preaislada 3m'], 'juego', 'Kit de caña preaislada de tres metros con cable y dren: todo lo que necesita el instalador para montar el split chico.'],
    ['Kit instalación split 5m', ['kit split 5', 'caña preaislada 5m'], 'juego', 'Kit de caña de cinco metros para instalaciones donde la condensadora queda lejos: aislación continua sin juntas.'],
    ['Manguera drenaje 5m', ['manguera condensado', 'manguera desague split'], 'unidad', 'Manguera flexible de cinco metros para llevar el agua del condensado al desagüe: el detalle que evita la mancha en la pared.'],
    ['Control remoto repuesto split', ['control aire', 'comando split'], 'unidad', 'Control universal compatible con las principales marcas de split: el reemplazo del control que quedó debajo del sillón.'],
    ['Ventilador de mesa 30cm', ['ventilador mesa', 'ventilador chico'], 'unidad', 'Ventilador de mesa con cabeza oscilante para escritorio y mesada de cocina: brisa personal en los días de horno.'],
    ['Ventilador de techo con luz', ['ventilador luz', 'fan luz'], 'unidad', 'Ventilador con luminaria central integrada: refresca e ilumina en un solo punto del techo.'],
    ['Ventilador recargable USB', ['ventilador usb', 'ventilador portatil'], 'unidad', 'Ventilador chico con batería recargable: funciona enchufado o a pila, para la playa, el auto y los cortes de luz.'],
    ['Bomba condensado con flotador', ['bomba condensado flotador', 'mini bomba split'], 'unidad', 'Bomba chiquita que se monta junto al split y saca el agua de condensado cuando el drenaje no da la pendiente.'],
    ['Soporte antivibrante para condensadora', ['soporte antivibrante', 'patas aire'], 'juego', 'Patas de goma metálica que aíslan la vibración de la condensadora: se acabó el zumbido en la pared del dormitorio.'],
    ['Funda exterior para split con zipper', ['funda split zipper', 'cubre aire exterior'], 'unidad', 'Funda con cierre para proteger la condensadora en invierno: saca el polvo y las hojas sin desmontar nada.'],
    ['Termostato WiFi programable', ['termostato wifi', 'termostato inteligente'], 'unidad', 'Termostato que controla la calefacción desde el celular: la casa tibia cuando llegás, sin gastar todo el día.'],
    ['Panel eléctrico de vidrio 1500W', ['panel vidrio', 'panel electrico cristal'], 'unidad', 'Panel calefactor de vidrio templado con imagen: calienta y decora como cuadro. Perfecto para el cuarto del bebé.'],
    ['Termoventilador cerámico con termostato', ['termoventilador ceramico', 'calefactor aire'], 'unidad', 'Termoventilador de resistencia cerámica que corta al alcanzar la temperatura: aire caliente rápido y seguro.'],
    ['Deshumidificador con tanque 5L', ['deshumidificador grande', 'sacahumedad'], 'unidad', 'Deshumidificador con tanque de cinco litros para sótanos y cuartos húmedos: la humedad baja, el moho se rinde.'],
    ['Purificador con HEPA e ionizador', ['purificador hepa', 'purificador ionizador'], 'unidad', 'Purificador de doble filtrado para alergias y polvo: el aire del cuarto como aire de montaña.'],
  ],

  jardineria: [
    ['Abonadora de empuje', ['esparcidora', 'abonadora ruedas'], 'unidad', 'Carrito con tolva que reparte fertilizante o semilla a medida que lo empujás: abonar el jardín deja de ser a mano.'],
    ['Borde plástico para canteros 10m', ['borde cantero', 'contencion jardin'], 'rollo', 'Cinta plástica flexible que se hunde en la tierra para separar canteros del césped: bordes prolijos y nada de pasto invasor.'],
    ['Cortacésped naftera 4HP', ['cortacesped naftera', 'cortadora pasto'], 'unidad', 'Cortacésped a nafta de cuatro caballos para lotes medianos: corta el pasto alto que el eléctrico no aguanta.'],
    ['Desmalezadora naftera 52cc', ['desmalezadora naftera', 'roza naftera'], 'unidad', 'Desmalezadora de motor naftera con hilo y disco: doma el pasto de terrenos grandes donde el eléctrico no llega.'],
    ['Film mulching negro 1.5x50m', ['mulching', 'film negro huerta'], 'rollo', 'Film negro que se tiende sobre el cantero: no sale pasto, la humedad queda adentro y la fruta no toca el barro.'],
    ['Fertilizante para flores 1kg', ['fertilizante flores', 'abono flores'], 'unidad', 'Fertilizante específico con fósforo y potasio para que las flores se den en serie: petunias, geranios y rosas felices.'],
    ['Fumigadora manual 5L', ['fumigadora 5l', 'pulverizadora manual'], 'unidad', 'Pulverizadora a presión de cinco litros con lanza y boquillas: insecticida, herbicida o fertilizante foliar con control fino.'],
    ['Fuente solar para jardín', ['fuente solar', 'fuente agua jardin'], 'unidad', 'Fuente con bomba solar que funciona con el sol: el agua circula, los pájaros llegan y la factura no sube.'],
    ['Hormiguicida granulado', ['hormiguicida', 'mata hormigas'], 'unidad', 'Granulado que las hormigas llevan al hormiguero: el nido entero se acaba en días, no solo la fila de arriba.'],
    ['Herbicida selectivo', ['herbicida', 'mata yuyos'], 'litro', 'Herbicida que mata los yuyos del césped sin dañar la grama: el jardín verde y uniforme que ves en las revistas.'],
    ['Kit herramientas jardín x5', ['kit jardin', 'herramientas jardin chica'], 'juego', 'Set de pala de mano, rastrillo, trasplantadora, tijera y desmalezadora chica con cinturón: el kit completo para la huerta del balcón.'],
    ['Malla antipájaros', ['red antipajaros', 'malla pájaros'], 'metro', 'Red liviana que se tensa sobre frutales y huertas: los pájaros miran las frutas pero no las comen.'],
    ['Manguera extensible 15m', ['manguera elastica', 'manguera extensible'], 'unidad', 'Manguera que se estira con el agua hasta quince metros y se guarda chica como una soga: fin de enredar veinte metros de goma.'],
    ['Maceta colgante 25cm', ['maceta colgante', 'jardinera colgante'], 'unidad', 'Maceta con cadenas para colgar del techo del balcón: petunias que caen en cascada.'],
    ['Maceta cemento 40cm', ['maceta 40', 'maceta grande'], 'unidad', 'Maceta de cemento de cuarenta centímetros para arbolitos y arbustos en maceta: peso que resiste el viento.'],
    ['Piedra volcánica', ['piedra lava', 'piedra volcanica roja'], 'bolsa', 'Piedra porosa roja para cubrir canteros y filtros: decorativa, liviana y deja respirar la tierra.'],
    ['Semilla de flores variadas', ['semillas flores', 'semilla floral'], 'paquete', 'Mezcla de semillas de flores para pradera colorida: sembrás, regás y en dos meses el jardín parece postcard.'],
    ['Soporte para enredadera', ['tutor enredadera', 'rejilla trepadora'], 'unidad', 'Rejilla vertical para que el jazmín, la madreselva o la enredadera trepe ordenada: pared verde sin sostener nada a mano.'],
    ['Sustrato para cactus 5L', ['tierra cactus', 'sustrato cactus'], 'bolsa', 'Mezcla drenante con arena y perlita para cactus y suculentas: el exceso de agua se va, la raíz queda feliz.'],
    ['Trampa para mosquitos', ['antimosquitos jardin', 'trampa mosquitos'], 'unidad', 'Trampa con luz UV y colector para patios y parrillas: caza mosquitos sin espirales ni aerosoles.'],
    ['Valla de madera para jardín', ['cerca madera', 'valla jardin'], 'rollo', 'Cerco de listones de madera tratada para delimitar el jardín o proteger las plantas del perro.'],
    ['Riego por goteo 20m extra', ['cinta goteo 20', 'extensión goteo'], 'paquete', 'Extensión de cinta de goteo de veinte metros con conectores: llevás el riego a la huerta que quedó lejos de la canilla.'],
    ['Regadera metálica 5L', ['regadera chapa', 'regadera 5 litros'], 'unidad', 'Regadera de chapa galvanizada con rosa extraíble: regado suave para plantines y presión fuerte para el patio.'],
  ],

  limpieza: [
    ['Aromatizador de ambientes con palitos', ['aromatizador palitos', 'difusor ambiente'], 'unidad', 'Difusor con varillas que absorben el aroma del aceite: perfume continuo sin prender ni enchufar nada.'],
    ['Aromatizador de pisos concentrado', ['aroma pisos', 'perfume piso'], 'litro', 'Concentrado que se agrega al agua del mopa: la casa limpia y con olor a lavanda o mentol durante horas.'],
    ['Bicarbonato 1kg', ['bicarbonato sodio', 'bicarbonato limpieza'], 'paquete', 'Multiuso natural: limpia y blanquea la bacha, mata olores de la heladera y refuerza el detergente.'],
    ['Crema limpiadora abrasiva 750ml', ['cif', 'limpiador abrasivo'], 'unidad', 'Crema con microabrasivos para hornallas, bachas y azulejos manchados: saca lo que el líquido común no mueve.'],
    ['Cera en aerosol para muebles', ['cera spray muebles', 'lustra muebles spray'], 'unidad', 'Aerosol que pule la madera del living en una pasada: saca polvo y deja olor a casa recién limpia.'],
    ['Destapacaños a pistón', ['sopapa', 'destapador desague'], 'unidad', 'Sopapa de goma con mango para destapar desagües con presión: el primer recurso antes de llamar al plomero.'],
    ['Detergente en polvo 1kg', ['detergente polvo', 'detergente lavarropa'], 'unidad', 'Detergente en polvo para lavarropas y limpieza general: rinde lavadas y no se derrama como el líquido.'],
    ['Esponja metálica x3', ['virulana', 'esponja acero'], 'paquete', 'Virulanas de acero para quemar grasa quemada de hornallas y parrillas: con guante, por favor.'],
    ['Guantes de nitrilo x10', ['guantes descartables', 'guantes nitrilo'], 'paquete', 'Guantes descartables de nitrilo para limpieza con químicos, pintura y comidas: aguantan más que el látex.'],
    ['Limpiador de horno en gel', ['limpiador horno', 'quitagrasa horno'], 'unidad', 'Gel que se adhiere a las paredes del horno y disuelve la grasa quemada: se aplica, se espera, se pasa el trapo.'],
    ['Limpiador de inodoros en gel', ['limpiador inodoro', 'gel sanitario'], 'unidad', 'Gel espeso que se queda pegado bajo el borde de la inodoro desinfectando donde importa.'],
    ['Limpiador de tapizados y alfombras', ['limpiador tapizados', 'shampoo alfombras'], 'unidad', 'Espuma que limpia sillones y alfombras sin remojar: la mancha de mate sale sin que el sofá quede mojado tres días.'],
    ['Limpiador de parrillas en gel', ['limpiador parrilla', 'quitagrasa parrilla'], 'unidad', 'Gel industrial para rejas y planchas de parrilla: disuelve la grasa carbonizada del domingo anterior.'],
    ['Lustra metales', ['limpiador metales', 'brillador metales'], 'unidad', 'Crema que saca el óxido y el mateo de cromo, acero y bronce: griferías, canillas y rejas brillando como el primer día.'],
    ['Paño chamois', ['chamois', 'paño auto'], 'unidad', 'Paño tipo ante que seca autos y vidrios sin dejar marcas de agua: el aliado del lavado de domingo.'],
    ['Papel toalla industrial rollo', ['papel toalla', 'rollos cocina industrial'], 'paquete', 'Rollo de papel toalla de gramaje industrial para cocinas y talleres: absorbe más, se usa menos.'],
    ['Papel higiénico jumbo x6', ['papel jumbo', 'papel higienico rollo grande'], 'paquete', 'Pack de rollos jumbo de larga duración para baños de tráfico intenso: menos cambios, menos faltantes.'],
    ['Quitamoho en gel 750ml', ['quitamoho gel', 'sacamoho'], 'unidad', 'Gel que se aplica sobre el moho de juntas y plásticos del baño: en minutos el negro se va sin cepillar.'],
    ['Tacho con pedal 12L', ['tacho pedal', 'tacho cocina 12l'], 'unidad', 'Tacho chico con pedal y tapa hermética para la cocina: abrís con el pie, no soltás el cuchillo con la mano empapada.'],
    ['Vinagre de limpieza 1L', ['vinagre blanco', 'vinagre limpieza'], 'unidad', 'Vinagre blanco para descalcificar pava y canilla, limpiar vidrios y neutralizar olores: el limpiador de la abuela que funciona.'],
    ['Balde 30L para obra', ['balde grande', 'balde 30 litros'], 'unidad', 'Balde reforzado de treinta litros con asas laterales para mezclas, escombros y lavado de herramientas.'],
    ['Wachupata 60cm', ['secador de agua', 'wachupata'], 'unidad', 'Limpiador de goma para secar pisos, vidrios y patios de una pasada: el agua se junta y sale limpia.'],
  ],

  muebles: [
    ['Aparador buffet 1.40m', ['aparador', 'buffet'], 'unidad', 'Mueble bajo con puertas y estantes que vive en el living: guarda la vajilla entera y encima queda perfecto el marco de fotos.'],
    ['Baúl de guardado', ['baul guardado', 'baul madera'], 'unidad', 'Baúl con tapa abatible para frazadas, juguetes y zapatos: almacenaje que además sirve de banco o mesa.'],
    ['Cajonera plástica x5', ['cajonera plastica', 'organizador cajones'], 'unidad', 'Torre de cinco cajones plásticos para ropa, juguetes y herramientas: se arma en diez minutos y se limpia con trapo.'],
    ['Cama de 1 plaza', ['cama 1 plaza', 'cama individual'], 'unidad', 'Cama de una plaza con laterales de madera o metal: la del cuarto de chico, la del huesped.'],
    ['Cama de 2 plazas', ['cama 2 plazas', 'cama matrimonial'], 'unidad', 'Cama de dos plazas reforzada con listones centrales: base firme para el colchón que quieras.'],
    ['Carrito de cocina con ruedas', ['carrito cocina', 'isleta movil'], 'unidad', 'Carrito con tablero de madera, rejillas y ruedas: mesa extra cuando cocinás y se esconde en el rincón cuando no.'],
    ['Cesto de ropa plegable', ['cesto ropa', 'canasto ropa'], 'unidad', 'Canasto de tela con marco que se plega plano: se cuelga en la puerta y desaparece cuando está vacío.'],
    ['Escritorio esquinero', ['escritorio esquina', 'mesa pc esquinero'], 'unidad', 'Escritorio en L que aprovecha la esquina del cuarto: compu, papeles y espacio para lo que estés armando.'],
    ['Mesa de comedor 1.60', ['mesa comedor 1.6', 'mesa 6 sillas'], 'unidad', 'Mesa de un metro sesenta para seis sillas: el tamaño que resuelve cenas de familia y de amigos sin arrimar.'],
    ['Mesa de cocina 1.40', ['mesa cocina 1.4', 'mesa 4 sillas'], 'unidad', 'Mesa de un metro cuarenta con estructura reforzada para uso diario: la que aguanta el desayuno, la tarea y el mate.'],
    ['Mesa de luz 0.40', ['mesa luz', 'mesita de noche'], 'unidad', 'Mesita de cuarenta por cuarenta con cajón para la mesita de noche: el despertador, el libro y el vaso de agua.'],
    ['Mesa extensible 1.60', ['mesa extensible', 'mesa con alas'], 'unidad', 'Mesa que corre y agrega tablero central: seis personas los días comunes, doce en Navidad.'],
    ['Silla de comedor tapizada', ['silla comedor', 'silla tapizada'], 'unidad', 'Silla con respaldo alto y asiento tapizado para comedor: cómoda para la sobremesa larga.'],
    ['Silla plegable de madera', ['silla plegable', 'silla plegar'], 'unidad', 'Silla que se cierra en un gesto y se cuelga de la pared o guarda detrás de la puerta: asientos extras sin ocupar lugar.'],
    ['Sillón de 2 cuerpos tapizado', ['sillon 2 cuerpos', 'sillon living'], 'unidad', 'Sillón de dos cuerpos con espuma de alta densidad: el asiento principal del living para dos adultos cómodos.'],
    ['Sofá cama 2 plazas', ['sofa cama', 'divan cama'], 'unidad', 'Sofá que se despliega en cama de dos plazas: el huesped resuelto sin cuarto de invitados.'],
    ['Tocador con espejo', ['tocador', 'vanitory con espejo'], 'unidad', 'Mueble con espejo y cajoncito para maquillaje y peinado: el rincón de la mañana bien organizado.'],
    ['Vitrina dos puertas', ['vitrina', 'mueble exhibidor'], 'unidad', 'Vitrina con vidrios y estantes de vidrio para lo que se guarda y se muestra: vajilla, trofeos y recuerdos.'],
    ['Banco de jardín de plástico', ['banco jardin', 'banco patio'], 'unidad', 'Banco de resina que aguanta sol y lluvia sin pintura: para el patio, la pileta y el fondo.'],
  ],

  seguridad: [
    ['Alarma GSM con llamadas', ['alarma gsm', 'alarma celular'], 'juego', 'Central de alarma con chip que llama y manda mensajes al detectar movimiento: te enterás adonde estés.'],
    ['Batería 12V para alarma', ['bateria 12v', 'bateria respaldo'], 'unidad', 'Batería sellada que mantiene la alarma viva cuando cortan la luz: el corte de energía es el momento preferido del ladrón.'],
    ['Botón de pánico', ['boton panico', 'botoera alarma'], 'unidad', 'Botón grande que dispara la alarma de un toque: para emergencias donde no hay tiempo de buscar el control.'],
    ['Cinta antiderrapante para escalones', ['cinta antideslizante', 'antiderrapante escalon'], 'rollo', 'Cinta rugosa autoadhesiva para el canto de escalones y bordes húmedos: el resbalón prevenido por veinte centavos.'],
    ['Detector de monóxido de carbono', ['detector co', 'alarma monoxido'], 'unidad', 'Alarma que detecta el gas que no se ve ni se huele: calefones, estufas y brasas lo emiten. Para dormitorios y zonas de gas.'],
    ['Extintor ABC 1kg', ['matafuego 1kg', 'extintor chico'], 'unidad', 'Extintor de un kilo para cocina y auto: chico, accesible y suficiente para el fuego de arranque.'],
    ['Extintor BC 6kg', ['extintor bc', 'matafuego bc'], 'unidad', 'Extintor para fuegos de líquidos y gases: el del garage y el taller donde hay nafta y solventes.'],
    ['Guantes anticorte', ['guantes anticorte nivel 5', 'guantes seguridad corte'], 'par', 'Guantes con fibra de alta resistencia para manipular chapa, vidrio y sierra: la mano entera sale del trabajo.'],
    ['Guantes de vaqueta', ['guantes cuero', 'guantes trabajo cuero'], 'par', 'Guantes de cuero para demoliciones, poda y manejo de materiales ásperos: aguantan espinas, astillas y calor.'],
    ['Guarda de escalera para bebés', ['guarda escalera', 'red escalera bebe'], 'unidad', 'Red o barrera plástica que se coloca en la baranda de la escalera: los chicos exploran, vos respirás.'],
    ['Impermeable de obra', ['capa de agua', 'impermeable trabajo'], 'unidad', 'Capa de agua con capucha para trabajar bajo la lluvia: la obra no para porque llueve, el cuerpo tampoco se moja.'],
    ['Kit DVR 4 cámaras', ['kit cctv', 'dvr 4 camaras'], 'juego', 'Sistema de cuatro cámaras con grabador y vista desde el celular: la casa vigilada las veinticuatro horas.'],
    ['Linterna de trabajo LED', ['linterna imantada', 'lampara trabajo led'], 'unidad', 'Linterna con imán y gancho para el taller y el motor del auto: ilumina donde las manos están ocupadas.'],
    ['Protección para enchufes bebés x10', ['tapa enchufes', 'proteccion tomas'], 'paquete', 'Tapitas que se encastran en las tomas y solo se sacan con truco: los dedos curiosos no entran.'],
    ['Red de protección para balcones', ['red balcon', 'red seguridad mascotas'], 'metro', 'Red de nylon reforzada que se tensa en balcones y ventanas: chicos y mascotas seguros con la ventana abierta.'],
    ['Rodilleras de trabajo', ['rodilleras espuma', 'proteccion rodillas'], 'par', 'Rodilleras de espuma alta densidad para colocadores y hasta pisos: las rodillas de los cuarenta te van a agradecer.'],
    ['Cinturón lumbar de obra', ['faja lumbar', 'cinturon carga'], 'unidad', 'Faja de apoyo lumbar para levantar peso todo el día: la espalda del albañil y del mudador, protegidas.'],
    ['Sirena exterior con flash', ['sirena flash', 'sirena alarma exterior'], 'unidad', 'Sirena de alta potencia con luz estroboscópica para fachadas: asusta al intruso y avisa al vecino.'],
    ['Sensor de agua con alarma', ['alarma inundacion', 'sensor agua'], 'unidad', 'Sensor que se coloca junto al lavarropas o bajo la bacha y suena al detectar agua: la inundación se corta en el minuto uno.'],
    ['Baliza LED de emergencia', ['baliza emergencia', 'baliza recargable'], 'unidad', 'Baliza recargable con luz giratoria para cortes de luz, obra en la calle y auto detenido: se te ve desde cuadras.'],
    ['Pantalón de obra con bolsillos', ['pantalon trabajo', 'pantalon cargo obra'], 'unidad', 'Pantalón reforzado con bolsillos para herramientas y rodilleras integradas: el uniforme de todo oficio.'],
    ['Botas de goma con casco', ['botas seguridad goma', 'bota obrera'], 'par', 'Botas de goma con puntera de acero para barro, agua y obra: pie seco y protegido aunque caiga algo pesado.'],
  ],
}
