// Expansión 2 del catálogo HomIA — parte C
// techos · cerramientos · pisos · aislacion · iluminacion
// Formato: [nombre, [aliases], unidad, descripción natural]
export const CATALOG_EXP2_C = {
  techos: [
    ['Boca de tormenta PVC 110', ['boca tormenta', 'sumidero 110'], 'unidad', 'Sumidero de techo con colador para recevoir el agua de la cubierta y llevarla al bajón. La boca que salva de la inundación.'],
    ['Cámara de inspección PVC 60cm', ['camara inspeccion', 'registro cloacal'], 'unidad', 'Cámara prefabricada con tapa para inspeccionar y desatascar la cloaca sin romper el jardín.'],
    ['Canaleta de zinc 3m', ['canal zinc 3m', 'canaleta galvanizada 3m'], 'unidad', 'Canaleta metálica de tres metros para recogida de lluvia en frentes y galpones. Más largo, menos juntas.'],
    ['Canaleta PVC 3m', ['canaleta plastica 3m', 'canal pvc 3'], 'unidad', 'Canaleta de PVC de tres metros con juntas que no se oxidan nunca. La favorita de las casas modernas.'],
    ['Codo de bajada 65°', ['codo bajada inclinado', 'codo canaleta'], 'unidad', 'Codo angosto que acomoda la bajada de lluvia contra el muro sin perder caudal.'],
    ['Colador para canaleta', ['protector canaleta', 'colador lluvia'], 'unidad', 'Rejilla que va sobre la canaleta para que las hojas no la tapen. Cinco minutos de limpieza ahorrados cada tormenta.'],
    ['Chapa PVC translúcida 1.10x2m', ['chapa plastica transparente', 'chapa luz 2m'], 'placa', 'Placa plástica transparente para tejados de patios, parrillas e invernáculos: deja pasar la luz y no deja pasar el agua.'],
    ['Chapa sinusoidal 1.10x6m', ['chapa 6 metros', 'chapa sinusoidal larga'], 'placa', 'Placa de seis metros para techos sin juntas intermedias: menos clavos, menos goteos, colocación más rápida.'],
    ['Flashing de silicona para tubos', ['flash silicona', 'campana tubos techo'], 'unidad', 'Manga elástica que se adapta a cualquier caño o tubo que atraviesa el techo: sella la salida de humos y ventilaciones.'],
    ['Ganchos de aluminio para canaleta', ['soporte canaleta', 'gancho canaleta'], 'paquete', 'Soportes que sostienen la canaleta cada sesenta centímetros. Sin ellos, la canaleta se pandea y desborda.'],
    ['Gárgola de desagüe', ['gargola', 'desague techo'], 'unidad', 'Salida decorativa que lanza el agua del techo lejos del muro: funcional y con estilo antiguo.'],
    ['Lámina policarbonato alveolar 8mm', ['poli alveolar', 'policarbonato techo'], 'placa', 'Placa alveolar de policarbonato para tejados de quinchos y galerías: transmite luz, filtra UV y resiste granizo.'],
    ['Lana de vidrio 100mm', ['lana 100', 'aislante lana gruesa'], 'rollo', 'Lana de vidrio de diez centímetros para techos con exigencia térmica alta: veranos menos calientes, inviernos menos fríos.'],
    ['Ojota de techo 1m', ['ojota techo', 'apoyo chapa'], 'unidad', 'Almohadilla que se coloca bajo la chapa sobre la viga: amortigua el ruido de la lluvia y evita el contacto metal-metal.'],
    ['Perfil de cierre para chapa', ['perfil cierre chapa', 'espuma cierre chapa'], 'paquete', 'Perfiles de espuma con forma de onda que tapan el hueco entre chapa y solera: cortan el viento, el polvo y los bichos.'],
    ['Pintura aluminio para chapa', ['pintura aluminio', 'esmalte aluminio'], 'litro', 'Esmalte aluminizado que refleja el sol y protege la chapa del óxido. Pinta y refresca el techo de una vez.'],
    ['Pintura reflectiva para membrana', ['pintura membrana', 'blanco reflectivo'], 'litro', 'Pintura blanca elastomérica que refleja el sol sobre membranas y techos: baja la temperatura interior y alarga la vida del impermeabilizante.'],
    ['Placa sandwich 50mm', ['placa sandwich', 'techo aislado'], 'placa', 'Panel de chapa con núcleo de espuma aislante: techo terminado con aislación incluida, en una sola colocación.'],
    ['Rejilla de ventilación de cumbrera', ['ventilador techo pasivo', 'rejilla cumbrera'], 'unidad', 'Salida giratoria o fija que monta en la cumbrera y saca el aire caliente del techo sin consumir nada.'],
    ['Rollo de aluminio 0.5mm x10m', ['chapa aluminio rollo', 'aluminio 0.5'], 'rollo', 'Rollo de aluminio para recubrir bajadas, frentes de canaletas y remates: no se oxida nunca y da terminación prolija.'],
    ['Silicona neutra transparente', ['silicona policarbonato', 'sellador neutro'], 'unidad', 'Sellador neutro que no ataca plásticos ni metales: ideal para policarbonato, aluminio y vidrio.'],
    ['Teja colonial de acero', ['teja colonial', 'teja acero'], 'm²', 'Teja de acero prepintada con forma colonial: liviana como chapa, elegante como teja, colocación rápida.'],
    ['Tela de refuerzo para membrana', ['tela membrana', 'malla poliester'], 'metro', 'Tela de poliéster que se embebe en el líquido impermeabilizante para reforzar juntas y grietas.'],
    ['Cenefa de chapa galvanizada 2m', ['cenefa galvanizada', 'remate cumbrera'], 'unidad', 'Remate galvanizado que tapa la cumbre del techo a dos aguas: sella la unión de las chapas contra el viento.'],
  ],

  cerramientos: [
    ['Barra de seguridad para ventana', ['barra ventana', 'proteccion ventana'], 'unidad', 'Barra de acero que se coloca en la ventana como protección parcial: seguridad sin cerrar la vista como una reja.'],
    ['Bisagra de portón reforzada 6"', ['bisagra porton 6', 'bisagra pesada'], 'unidad', 'Bisagra de seis pulgadas de acero macizo para portones de chapa pesados: perno grueso y púa reforzada.'],
    ['Burlete cepillo para portones', ['cepillo puerta', 'burlete porton'], 'unidad', 'Cepillo continuo que va en la base del portón corredizo: corta polvo, viento e insectos sin frenar el deslizamiento.'],
    ['Cerradura portón doble paleta', ['cerradura porton', 'cerradura doble paleta'], 'unidad', 'Cerradura de dos paletas para portones y tranqueras: se abre con llave de paleta y aguanta el uso rudo.'],
    ['Chapa de refuerzo para cerradura', ['chapa refuerzo', 'blindaje cerradura'], 'unidad', 'Placa de acero que envuelve la cerradura y el bombín: hace que la palanca no abra la puerta de una patada.'],
    ['Motor para persiana con comando', ['motor persiana', 'motorizacion persiana'], 'juego', 'Motor tubular con control remoto para persianas: subís y bajás la persiana sin jugarse la espalda.'],
    ['Mosquitero adhesivo velcro', ['mosquitero velcro', 'tela velcro puerta'], 'unidad', 'Tela de mosquitero que se pega al marco con velcro: se instala en minutos y deja pasar el aire, no los mosquitos.'],
    ['Pasador embutir 15cm', ['pasador puerta 15', 'pasador seguridad'], 'unidad', 'Pasador largo de embutir para puertas dobles y de servicio: el refuerzo del lado donde no hay cerradura.'],
    ['Persiana de madera 1.00', ['persiana madera', 'persiana 1 metro'], 'unidad', 'Persiana de madera natural para ventanas de un metro: aislante, clásica y reparables listón por listón.'],
    ['Persiana plástica 0.70', ['persiana chica', 'persiana 70'], 'unidad', 'Persiana de PVC de setenta centímetros para baños y ventanas chicas: no se pudre ni necesita pintura.'],
    ['Portón levadizo de chapa', ['porton levadizo', 'porton chapa'], 'unidad', 'Portón de una pieza que levanta hacia adelante: para garajes donde no hay lugar para que corra a los costados.'],
    ['Puerta aluminio corrediza 2 hojas', ['puerta corrediza aluminio', 'door corrediza'], 'unidad', 'Puerta de dos hojas que corre sobre riel: abre el living al balcón sin invadir el espacio.'],
    ['Puerta bathroom PVC blanca', ['puerta pvc baño', 'puerta bano'], 'unidad', 'Puerta de PVC de bathroom: no se hincha con la humedad, no se pinta, no se pudre. Fin de la puerta ampollada.'],
    ['Riel para portón corredizo', ['riel porton', 'carril porton'], 'metro', 'Riel reforzado que recibe las ruedas del portón: la parte del portón que se pisa y se desgasta. Cambiala antes de que se descarrile todo.'],
    ['Rueda portón 150mm', ['rueda porton', 'rueda garganta'], 'unidad', 'Rueda de acero con garganta de quince centímetros para portones pesados: rueda sobre el riel sin saltarse.'],
    ['Tope de pared para portón', ['tope porton', 'freno porton'], 'unidad', 'Tope de goma o acero que frena el portón antes de golpear el muro. Protege la pared y las ruedas.'],
    ['Tope de piso portón', ['tope piso porton', 'traba porton'], 'unidad', 'Cuña o perno que traba el portón en su posición abierta o cerrada: evita que el viento lo arrastre.'],
    ['Traba de seguridad para ventanas', ['traba ventana', 'cierre ventana'], 'unidad', 'Dispositivo que limita la apertura de la ventana: ventila seguro y no deja que entren por ahí.'],
    ['Vidrio flotado 6mm m²', ['vidrio 6 mm', 'vidrio ventana 6'], 'm²', 'Vidrio de seis milímetros para ventanas grandes y mamparas: más aislación sonora que el de 4 y más difícil de romper.'],
    ['Vidrio templado 10mm', ['vidrio templado 10', 'vidrio seguridad 10'], 'm²', 'Vidrio templado de diez milímetros para escaleras, barandas y puertas: al romperse se granula, no corta.'],
    ['Visera para puerta', ['visera entrada', 'toldo puerta'], 'unidad', 'Techo chico sobre la puerta que corta la lluvia antes de que llegue al picaporte. Cada entrada lo merece.'],
    ['Marco de puerta madera 0.70', ['marco 70', 'marco madera chico'], 'unidad', 'Marco de madera para puertas de setenta centímetros: baños, dormitorios y rooms de servicio.'],
    ['Cerradura electrónica con huella', ['cerradura huella', 'cerradura biometrica'], 'unidad', 'Cerradura que abre con la huella, código o llave: sin llaves que se pierdan ni bombines que se cambien.'],
    ['Felpa autoadhesiva 9mm', ['felpa adhesiva', 'burlete felpa'], 'rollo', 'Cinta de felpa con pegamento integrado para tapar el hueco entre puerta y marco: adiós al viento que silba de noche.'],
    ['Espejo biselado 60x80', ['espejo biselado', 'espejo living'], 'unidad', 'Espejo con borde biselado que multiplica la luz del ambiente. Se fija a la pared con clips o silicona.'],
    ['Cierrapuertas de piso', ['cierrapuertas piso', 'freno piso puerta'], 'unidad', 'Mecanismo de piso que cierra y frena la puerta del local: invisible, elegante y regulable.'],
    ['Ojo mágico digital con pantalla', ['ojo magico digital', 'mirilla pantalla'], 'unidad', 'Mirilla con cámara y pantalla interna: ves quién está en la puerta sin acercarte al ojo.'],
  ],

  pisos: [
    ['Adhesivo porcelanato flexible 30kg', ['adhesivo flexible', 'pegamento porcelanato'], 'bolsa', 'Adhesivo cementicio con polímeros para porcelanatos grandes y exteriores: agarra más fuerte y tolera la dilatación.'],
    ['Aditivo para pastina', ['latex pastina', 'aditivo juntas'], 'frasco', 'Líquido que reemplaza al agua en la pastina: juntas más duras, sin manchas y que no se desprenden al lavar.'],
    ['Adhesivo para alfombra 4L', ['pegamento alfombra', 'adhesivo alfombra'], 'lata', 'Adhesivo en base solvente para pegar alfombras y molduras de piso: agarra de verdad y se extiende con llana dentada.'],
    ['Baldosas vinílicas x10', ['baldosas plasticas', 'piso vinilico baldo'], 'paquete', 'Pack de baldosas vinílicas autoadhesivas para renovar pisos sin obra: se cortan con tijera y pegan solas.'],
    ['Borde de goma para escalones', ['borde escalon', 'goma escalon'], 'metro', 'Perfil de goma antideslizante que va en el canto del escalón: protege la nariz del escalón y evita resbalones.'],
    ['Fieltros autoadhesivos x24', ['fieltros patas', 'almohadillas muebles'], 'paquete', 'Almohadillas de fieltro para las patas de sillas y mesas: mueves el mueble sin rayar el piso nuevo.'],
    ['Espaciadores para cerámico x100', ['crucetas ceramico', 'separadores ceramico'], 'paquete', 'Crucetas plásticas que mantienen la junta pareja mientras seca el adhesivo. El secreto de un piso bien colocado.'],
    ['Impermeabilizante bajo cerámico', ['membrana bajo ceramico', 'liquid rubber'], 'litro', 'Membrana líquida que se aplica antes de colocar cerámico en duchas y baños: si el agua pasa, la mampara no salva.'],
    ['Junquillo aluminio para pisos', ['perfil transicion', 'junquillo piso aluminio'], 'metro', 'Perfil de aluminio que une dos pisos de distinto material: la transición prolija entre cerámico y madera.'],
    ['Junquillo PVC 2.5m', ['junquillo piso pvc', 'perfil pvc piso'], 'unidad', 'Junquillo plástico económico para tapar juntas y dilataciones de pisos. Se corta y se pega.'],
    ['Junta de dilatación PVC 10m', ['perfil dilatacion', 'junta pvc'], 'rollo', 'Perfil en T que absorbe el movimiento del piso en superficies grandes: evita que el cerámico se levante con el calor.'],
    ['Losa de hormigón 40x40', ['baldosa cemento 40', 'adoquin 40x40'], 'unidad', 'Baldosa de hormigón lisa de cuarenta por cuarenta para veredas y patios: la eterna losa de toda la vida.'],
    ['Pastina epoxi', ['junta epoxi', 'pastina antihongo'], 'kg', 'Pastina de resina epoxi para juntas de baño y cocina: no absorbe agua, no se pone negra, se limpia con lo que sea.'],
    ['Piedra Bangkok m²', ['piedra bangkok', 'piedra partida mosaico'], 'm²', 'Piedra partida en malla para frentes y paredes decorativas: textura natural que convierte una pared en paisaje.'],
    ['Placa corcho 2mm', ['corcho bajo piso', 'bajo piso corcho'], 'rollo', 'Lámina de corcho que se coloca bajo piso flotante: amortigua el ruido de pasos y nivela pequeñas irregularidades.'],
    ['Porcelanato 45x45 m²', ['porcelanato 45', 'porcelanato piso'], 'm²', 'Porcelanato de cuarenta y cinco por cuarenta: resiste tránsito, humedad y moda, porque el gris neutro no pasa.'],
    ['Porcelanato rectificado 60x60 m²', ['porcelanato 60', 'porcelanato grande'], 'm²', 'Placa grande rectificada con juntas mínimas: sensación de piso continuo, moderno y fácil de limpiar.'],
    ['Porcelanato efecto madera m²', ['porcelanato madera', 'porcelanato lena'], 'm²', 'Porcelanato con textura de madera: lo mejor de los dos mundos, sin lijar ni barnizar nunca.'],
    ['Cerámico tipo cemento m²', ['ceramico cemento', 'ceramico estilo industrial'], 'm²', 'Cerámico con terminación tipo cemento alisado: estética industrial sin sacrificar el lavado con mopa.'],
    ['Revestimiento PVC pared m²', ['pvc pared', 'revestimiento plastico'], 'm²', 'Panel de PVC de encastre para paredes de baño, lavadero y comercio: se limpia con trapo y no requiere obra.'],
    ['Tratamiento antideslizante para baños', ['antideslizante piso', 'tratamiento resbalones'], 'litro', 'Líquido que se aplica sobre el cerámico y crea microagarre invisible: la ducha deja de ser pista de patinaje.'],
    ['Tratamiento cristalizador mármol', ['cristalizado marmol', 'abrillantador marmol'], 'litro', 'Producto que se pule sobre el mármol y lo devuelve a su brillo de fábrica: para pisos nobles maltratados.'],
    ['Escalón de granito 1.20m', ['escalon granito', 'escalera granito'], 'unidad', 'Escalón de granito pulido de un metro veinte para escaleras de entrada: pesado, eterno y elegante.'],
    ['Escalón de hormigón 1.20m', ['escalon hormigon', 'escalera cemento'], 'unidad', 'Escalón prefabricado de hormigón para escaleras exteriores y entradas: se coloca y ya está.'],
    ['Zócalo aluminio 8cm', ['zócalo aluminio', 'zócalo metal'], 'metro', 'Zócalo de aluminio cepillado para pisos modernos: recto, resistente y sin pintar nunca.'],
    ['Borde de pileta granito', ['borde pileta', 'borde piscina'], 'metro', 'Borde de granito para piletas: canto redondeado que no corta, material que no le teme al cloro.'],
    ['Estera de coco 60x40', ['felpudo coco', 'estera entrada'], 'unidad', 'Estera natural de fibra de coco para la entrada: trae el barro de afuera y se sacudida al revés.'],
  ],

  aislacion: [
    ['Adhesivo para telgopor', ['pegamento telgopor', 'adhesivo poliestireno'], 'unidad', 'Adhesivo en cartucho formulado para placas de poliestireno: no lo derrite como el silicona común.'],
    ['Burlete goma D para puerta', ['burlete puerta', 'goma puerta D'], 'metro', 'Burlete de goma con perfil en D que se clava en el marco: corta el viento, el polvo y el ruido de la calle.'],
    ['Burlete EPDM para vidrio', ['burlete vidrio', 'goma vidrio ventanas'], 'metro', 'Goma EPDM que recibe el vidrio en ventanas y mamparas: sella al agua y no se seca con el sol.'],
    ['Cinta aluminio 75mm', ['cinta aluminio ancha', 'cinta aluminio 75'], 'rollo', 'Cinta de aluminio de siete centímetros para sellar juntas de aislación y reparar caños de aire.'],
    ['Cinta aluminio 100mm', ['cinta aluminio 100', 'cinta ancha aluminio'], 'rollo', 'Versión ancha para sellar rápido placas grandes y conductos de aire.'],
    ['Cinta de espuma para ventanas', ['cinta espuma ventana', 'burlete cinta'], 'rollo', 'Cinta de espuma comprimible que se coloca entre vidrio y marco: corta el silbido del viento en ventanas viejas.'],
    ['Cinta doble cara espuma 19mm', ['cinta doble cara', 'cinta adhesiva doble'], 'rollo', 'Cinta de doble cara de espuma para montar molduras, tiradores y placas livianas sin taladrar.'],
    ['Espuma PU de pistola 750ml', ['espuma pistola', 'poliuretano pistola'], 'unidad', 'Espuma expansiva para pistola profesional: rellena huecos grandes con control y sin desperdicio.'],
    ['Fieltro rollo 1x10m', ['fieltro piso', 'fieltro rollo'], 'rollo', 'Rollo de fieltro para colocar bajo piso flotante y alfombras: amortigua ruidos y nivela el contrapiso.'],
    ['Felpa ventana aluminio rollo', ['felpa aluminio', 'felpa ventanas'], 'rollo', 'Felpa gris con respaldo adhesivo para ventanas de aluminio: repone el sellado original que se aplastó con los años.'],
    ['Lana de vidrio 25mm', ['lana fina', 'lana vidrio 25'], 'rollo', 'Lana de vidrio delgada para cielorrasos y espacios cortos: aísla donde la de 50 no entra.'],
    ['Lana de roca 100mm', ['lana roca 100', 'lana roca gruesa'], 'placa', 'Planchuela de lana de roca de diez centímetros: máxima resistencia térmica y al fuego para techos y calderas.'],
    ['Planchuela lana vidrio 50mm', ['lana vidrio planchuela', 'placa lana vidrio'], 'placa', 'Placa semirrígida de lana de vidrio con foil para techos: se apoya, no se hunda y corta el calor de entrada.'],
    ['Placa acústica perforada 60x60', ['placa acustica', 'cielorraso acustico'], 'unidad', 'Panel perforado para cielorrasos que necesitan bajar el eco: oficinas, aulas y salas de música.'],
    ['Placa corcho 2cm', ['corcho 2cm', 'placa corcho pared'], 'unidad', 'Placa de corcho natural para paredes: aísla, decora y hasta sirve para clavar alfileres.'],
    ['Placa goma espuma 1cm', ['goma espuma placa', 'placa esponja'], 'unidad', 'Lámina de goma espuma para tapizados, protección de cajones y sellos de maquinaria.'],
    ['Placa poliuretano 3cm', ['placa poliuretano', 'PUR 3cm'], 'placa', 'Placa rígida de poliuretano de tres centímetros: máxima aislación en mínimo espesor, ideal bajo techo.'],
    ['Placa poliestireno 3cm', ['telgopor 3cm', 'poliestireno 3'], 'placa', 'Placa de poliestireno de tres centímetros para techos y paredes: la aislación económica de siempre.'],
    ['Placa poliestireno 10cm', ['telgopor 10cm', 'poliestireno grueso'], 'placa', 'Placa de diez centímetros para techos sin aislación previa y cámaras frigoríficas caseras.'],
    ['Radier aislante 5cm', ['radier 5cm', 'placa radier'], 'placa', 'Placa rígida de radier de cinco centímetros para pisos radiantes y contrapisos aislados.'],
    ['Radier aislante 2cm', ['radier 2cm', 'radier fino'], 'placa', 'Radier de dos centímetros para pisos flotantes sobre contrapisos ya térmicos.'],
    ['Lámina de burbuja 1.2x50m', ['film burbuja', 'plastico burbuja'], 'rollo', 'Rollo de burbuja para proteger muebles en la mudanza, vidrios en obra y plantas en invierno.'],
    ['Geotextil 200g x2m', ['geotextil pesado', 'tela geotextil'], 'metro', 'Geotextil de gramaje alto para separar suelos, filtrar y proteger membranas enterradas.'],
    ['Neopreno placa 5mm', ['placa neopreno', 'goma neopreno'], 'unidad', 'Placa de neopreno para sellos antivibrantes, apoyos de maquinaria y juntas de vidrio.'],
    ['Caño preformado 3/4"', ['aislante caño 3/4', 'tubo aislante 3/4'], 'metro', 'Aislante de espuma preformado que se embute en caños de agua caliente: menos pérdidas, agua más caliente.'],
    ['Tubo preformado 2"', ['aislante caño 2', 'tubo aislante 2'], 'metro', 'Aislante para caños gruesos de calefacción y agua caliente central.'],
  ],

  iluminacion: [
    ['Aplique exterior con fotocélula', ['aplique con fotocelula', 'luz automatica exterior'], 'unidad', 'Aplique estanco que se enciende solo al anochecer: luz de entrada sin tocar un interruptor nunca más.'],
    ['Araña de cristal 6 luces', ['araña cristal', 'araña living'], 'unidad', 'Araña con colgantes de cristal para comedor: la que convierte una cena cualquiera en ocasión especial.'],
    ['Baliza LED de pared', ['baliza led', 'luz baliza'], 'unidad', 'Aplique chico de LED con luz indirecta para escaleras, pasillos y exteriores: marca el camino sin encandilar.'],
    ['Campana LED alta bahía 150W', ['campana alta bahia', 'campana 150w'], 'unidad', 'Luminaria industrial de alta potencia para galpones y talleres de doble altura: luz como estadio, consumo razonable.'],
    ['Colgante industrial negro', ['colgante industrial', 'pendant negro'], 'unidad', 'Colgante de chapa negra estilo fábrica para barras y mesadas: el look de cafeteria que todos quieren copiar.'],
    ['Dicroica halógena GU10 50W', ['halogena gu10', 'dicroica halogena'], 'unidad', 'Lámpara halógena de recambio para dicroicas viejas: luz cálida intensa mientras no se cambia a LED.'],
    ['Lámpara filamento LED E27', ['lampara filamento', 'led vintage'], 'unidad', 'LED con forma de filamento antiguo: calidez de lámpara de bar, consumo de LED moderno.'],
    ['Lámpara LED 5W E27', ['led 5w', 'lampara led chica'], 'unidad', 'LED de cinco watts para veladores y apliques: suficiente luz cálida, factura mínima.'],
    ['Lámpara LED 30W E27', ['led 30w', 'led alta potencia'], 'unidad', 'LED de treinta watts que reemplaza a las viejas de 200: ilumina patios, garajes y talleres.'],
    ['Lámpara LED 40W E27', ['led 40w', 'led exterior grande'], 'unidad', 'LED de máxima potencia en rosca común para patios y accesos: poca cosa que ilumina como un proyector.'],
    ['Lámpara LED dimerizable 12W', ['led dimerizable', 'led con regulador'], 'unidad', 'LED que baja de intensidad con el regulador de pared: cena a la luz de las velas sin velas.'],
    ['Luminaria mesada con sensor', ['luz mesada sensor', 'led bajo mueble'], 'unidad', 'Tira o barra LED con sensor de movimiento que se prende al acercar la mano: cocina moderna de verdad.'],
    ['Luminaria oficina 4 tubos', ['luminaria oficina', 'luminaria 4 tubos'], 'unidad', 'Luminaria rectangular de cuatro tubos LED para escritorios y talleres: luz pareja, sin sombras ni parpadeo.'],
    ['Luz de vitrina LED', ['luz vitrina', 'led vitrina'], 'unidad', 'Mini luminaria para interiores de muebles y vitrinas: hace que lo exhibido parezca más caro.'],
    ['Luz nocturna LED enchufe', ['luz nocturna', 'guia luz'], 'unidad', 'Lamparita que se enchufa y guía el camino al baño de noche: luz suave sin encender la habitación entera.'],
    ['Panel LED 18W', ['panel 18w', 'panel chico'], 'unidad', 'Panel de techo de dieciocho watts para baños, pasillos y roperos: luz difusa sin sombras.'],
    ['Panel LED 60x60 40W', ['panel 60x60', 'panel 40w'], 'unidad', 'Panel cuadrado estándar de oficina para cielorrasos de durlock: encastra en la trama y baja el consumo al mínimo.'],
    ['Plafón LED 12W', ['plafon chico', 'plafon 12'], 'unidad', 'Plafón circular chico para baño, pasillo y balcón: barato, luminoso y se instala en diez minutos.'],
    ['Proyector LED 200W', ['proyector 200w', 'reflector grande'], 'unidad', 'Proyector de doscientos watts para canchas, frentes de casa y áreas de trabajo amplias: ilumina todo el cuadro.'],
    ['Spot LED superficie cuadrado', ['spot superficie', 'spot cuadrado'], 'unidad', 'Spot que monta en superficie sin abrir el techo: la solución de iluminación para cuando no se puede embutir.'],
    ['Tubo LED 30cm', ['tubo led chico', 'tubo 30'], 'unidad', 'Tubo LED corto para muebles, placares y pasamanos: luz localizada donde el plafón no llega.'],
    ['Tubo LED 90cm', ['tubo led 90', 'tubo mediano'], 'unidad', 'Tubo LED de noventa centímetros para cocinas, lavaderos y comercios: reemplaza al fluorescente con la mitad del consumo.'],
    ['Velas LED x6', ['velas led', 'luz vela'], 'paquete', 'Set de seis velas LED con llama móvil: ambiente de noche sin riesgo ni cera derretida.'],
    ['Araña de hierro forjado', ['araña forjada', 'araña hierro'], 'unidad', 'Araña de hierro forjado estilo campo para quinchos y comedores: rústica de verdad, no rústica de plástico.'],
    ['Regulador LED de pared', ['dimmer led', 'regulador intensidad'], 'unidad', 'Regulador específico para LED: baja la luz sin parpadeos ni zumbidos.'],
  ],
}
