// Expansión 2 del catálogo HomIA — parte A
// plomeria · gasistas · electricistas · albanileria · durlock
// Formato: [nombre, [aliases], unidad, descripción natural]
export const CATALOG_EXP2_A = {
  plomeria: [
    ['Adaptador macho termofusión 25mm', ['macho termofusion', 'adaptador 25'], 'unidad', 'Pieza con rosca metal de un lado y termofusión del otro: conecta el caño plástico a las llaves y griferías. Lo usás en cada arranque de agua.'],
    ['Aireador para grifería', ['aireador canilla', 'filtro griferia'], 'unidad', 'Piecita roscada que va en la boca de la canilla: mezcla aire con el agua para que rinda más y no salpique. Se enrosca a mano.'],
    ['Asiento inodoro con tapa', ['tapa inodoro', 'asiento madera', 'tapa baño'], 'unidad', 'Asiento con tapa para inodoro estándar, con herrajes incluidos. Lo que más se cambia en un baño porque se rompe con los años.'],
    ['Bomba achique 1/3 HP', ['bomba desague', 'bomba cloacal', 'bomba achique'], 'unidad', 'Bomba de eje vertical que saca agua de sótanos, cisternas y sumideros. Pasa pelotitas y suciedad liviana sin taparse.'],
    ['Cinta autovulcanizante', ['cinta autosoldante', 'cinta silicona'], 'unidad', 'Cinta de silicona que se estira y se pega sobre sí misma sin pegamento: arregla pérdidas de agua en caños y mangueras como parche de emergencia.'],
    ['Codo 45° PVC 110mm', ['codo 45 desague', 'codo pvc 45'], 'unidad', 'Curva de 45 grados para desagües cloacales: gira menos brusco que el de 90 y se atasca menos. Pegamento para PVC y listo.'],
    ['Codo latón comprimido 1/2"', ['codo bronce', 'codo rosca media'], 'unidad', 'Codo de bronce con rosca 1/2 para empalmes de agua fría y caliente. El clásico de la plomería tradicional, se sella con teflón.'],
    ['Colador de tanque', ['filtro tanque', 'colador agua'], 'unidad', 'Rejilla que va en la boca del tanque para que no entren hojas ni bichos al agua. Se lava cada tanto y evita que se tapen las cañerías.'],
    ['Ducha telefónica completa', ['ducha con manguera', 'manguera ducha', 'telefono ducha'], 'unidad', 'Kit con manguera flexible, jabonera deslizante y baja con gomas: convertís la ducha fija en desmontable para orientar el agua donde querés.'],
    ['Electrobomba 1 HP con presorcontrol', ['bomba 1 hp', 'bomba con presorcontrol'], 'unidad', 'Bomba centrífuga con control electrónico de arranque: abre la canilla y arranca sola, la cerrás y para. Sin tanque, presión constante.'],
    ['Flotante mecánica 2"', ['valvula flotante', 'flotante tanque'], 'unidad', 'Válvula con brazo y flotador plástico que corta la entrada de agua cuando el tanque llenó. La clásica de toda cisterna.'],
    ['Grifería fija cocina', ['griferia cocina simple', 'canilla cocina'], 'unidad', 'Canilla de cocina de un solo cuerpo, sin monocomando: barata, dura años y se repone con teflón. Ideal lavaderos y quarters.'],
    ['Kit reparación cisterna', ['kit cisterna', 'reparacion deposito'], 'juego', 'Set con clencher, diafragma y gomas para reparar el depósito del inodoro sin cambiarlo todo. Cuesta lo mismo que una visita del plomero.'],
    ['Llave de paso angular 1/2"', ['llave angular', 'llave esquina'], 'unidad', 'Llave chica en L que va detrás de la inodoro o del lavatorio: corta el agua de ese artefacto sin dejar a la casa entera sin agua.'],
    ['Niple doble 1/2"', ['niple galvanizado', 'niple media'], 'unidad', 'Tubo corto roscado de los dos lados para unir llaves, codos y griferías. Es el tornillito de la plomería: siempre hace falta.'],
    ['Precinto metálico x100', ['abrazadera caño', 'precinto abrazadera'], 'caja', 'Abrazaderas de acero ajustables para fijar mangueras, caños y flexibles. Se aprietan con destornillador y no se sueltan con la vibración.'],
    ['Presorcontrol', ['presostato', 'controlador presion'], 'unidad', 'Caja que enciende la bomba cuando baja la presión y la apaga al cortar el flujo. Se coloca en la cañería y protege al motor.'],
    ['Rejilla lineal de ducha', ['desague lineal', 'rejilla ducha'], 'unidad', 'Canal de desagüe angosto que va a ras del piso de la ducha: moderno, discreto y perfecta para baños con piso a nivel.'],
    ['Sellador de rosca líquido', ['sellador roscas', 'anaerobico'], 'frasco', 'Líquido que reemplaza al teflón en roscas metálicas: seca, endurece y no permite que la junta se afloje con la vibración.'],
    ['Sifón trampa de piso', ['sifon piso', 'trampa sifonica'], 'unidad', 'Pieza con cebado de agua que se instala bajo la rejilla del piso: corta olores de la cloaca antes de que entren al baño.'],
    ['Abrazadera goma 40mm', ['abrazadera desague', 'precinto goma'], 'unidad', 'Abrazadera de goma con tornillos laterales que fija caños de desagüe a la pared sin estrangularlos. Para PVC cloacal y ventilaciones.'],
    ['Tacón de apoyo para tanque', ['base tanque', 'apoyo tanque', 'tacos tanque'], 'paquete', 'Bases plásticas o de hormigón que apoyan el tanque a nivel y distribuyen el peso. Evitan que el fondo se deforme con los años.'],
    ['Tanque cisterna 500L', ['tanque 500 litros', 'cisterna 500'], 'unidad', 'Tanque tricapa de 500 litros para casas medianas: guarda agua potable, la protege del sol y tiene tapa con cierre.'],
    ['Termotanque eléctrico 30L', ['termotanque chico', 'termotanque 30 litros'], 'unidad', 'Termotanque eléctrico compacto para departamentos o un solo baño: calienta rápido y ocupa poco espacio bajo el techo.'],
    ['Tubo cloacal PVC 200mm x4m', ['cano cloacal 200', 'tubo 200'], 'barra', 'Caño grande de PVC para colector principal y conexiones a cámara séptica. Es la "madre" del desagüe de toda la casa.'],
    ['Válvula de retención 1"', ['valvula antirretorno', 'check 1 pulgada'], 'unidad', 'Válvula que deja pasar el agua en un solo sentido: evita que la bomba gire al revés y que el agua vuelva al pozo.'],
    ['Válvula de seguridad termotanque', ['valvula termotanque', 'valvula alivio'], 'unidad', 'Válvula que suelta presión y agua caliente cuando el termotanque se sobrecalienta. Si gotea de vez en cuando, está haciendo su trabajo.'],
    ['Canilla de espera 1/2"', ['canilla lavadero', 'griferia espera'], 'unidad', 'Canilla simple con pico corto para lavaderos y patios: aguantan intemperie y se cambia en cinco minutos con teflón.'],
    ['Goma de conexión 3/4"', ['goma conexion', 'goma termotanque'], 'unidad', 'Manguita flexible reforzada que conecta el termotanque o el lavarropas a la cañería: absorbe vibraciones y se instala sin herramientas.'],
    ['Barra de ducha cromada', ['barra deslizante', 'barra ducha'], 'unidad', 'Tubo cromado que se fija a la pared y permite subir o bajar la ducha telefónica. Ideal cuando conviven grandes y chicos.'],
    ['Manguera reforzada 20m', ['manguera riego reforzada', 'manguera 20 metros'], 'unidad', 'Manguera de jardín de tres capas con conector rápido: aguanta el sol y los roces del patio. Largo suficiente para dar la vuelta a la casa.'],
    ['Bomba autocebante 3/4 HP', ['bomba autocebante', 'bomba aspira'], 'unidad', 'Bomba que aspira el agua de pozo o tanque bajo sin cebado previo: presión firme en toda la casa desde la primer apertura.'],
    ['Codo 45° termofusión 25mm', ['codo termofusion 45', 'curva 45 termo'], 'unidad', 'Curva de cuarenta y cinco grados para caños de agua: giros suaves que cuidan la presión y se termofusionan en segundos.'],
    ['Tee 45° PVC 110mm', ['tee 45 desague', 'tres 45 pvc'], 'unidad', 'Derivación diagonal para desagües: incorpora una rama con pendiente ideal para que la cloaca corra sola.'],
    ['Llave de paso esférica 3/8"', ['llave paso chica', 'llave 3/8'], 'unidad', 'Llave chica para aparatos de pocos litros: filtros, bidets y arranques de grifería con rosca fina.'],
    ['Codo termofusión 40mm', ['codo termo 40', 'codo agua 40'], 'unidad', 'Curva de cuarenta milímetros para líneas principales de agua fría y caliente.'],
    ['Tee termofusión 40mm', ['tee termo 40', 'tres agua 40'], 'unidad', 'Derivación para caños de cuarenta milímetros: de acá sale la rama que alimenta un baño nuevo.'],
    ['Unión universal 40mm', ['union 40', 'deshice union 40'], 'unidad', 'Unión desmontable para caños de cuarenta: permite reparar tramos sin cortar la cañería entera.'],
    ['Llave global 1/2"', ['llave global media', 'llave lavatorio'], 'unidad', 'Llave de cierre global para lavatorios y bidets: la clásica con volante de bronce que corta el agua del aparato.'],
    ['Reducción termofusión 32x25', ['reduccion termo', 'reduccion 32 a 25'], 'unidad', 'Pieza que une caños de distinto diámetro en la misma línea: baja de treinta y dos a veinticinco sin rosca ni teflón.'],
    ['Caño termofusión 40mm', ['cano termo 40', 'cano agua 40'], 'barra', 'Caño de cuarenta milímetros para entradas de agua y líneas principales donde el diámetro importa.'],
  ],

  gasistas: [
    ['Adaptador de rosca gas 1/2"', ['adaptador gas', 'niple gas media'], 'unidad', 'Fitting roscado para unir mangueras, llaves y artefactos a gas. Se arma con teflón especial para gas, nunca el común.'],
    ['Anafe de 1 hornalla portátil', ['anafe portatil', 'hornalla unica'], 'unidad', 'Hornalla individual de mesa para gas de tubo: ideal para garajes, fondas y cuando se corta la luz y hay que cocinar igual.'],
    ['Base para tanque 45kg', ['base tanque gas', 'base garrafa'], 'unidad', 'Base plástica reforzada que separa el tanque del suelo: evita humedad, corrosión y lo mantiene nivelado.'],
    ['Calefón a gas 10L', ['calefon 10 litros', 'calefon chico'], 'unidad', 'Calefón de 10 litros para departamentos y casas chicas: agua caliente a demanda sin tanque de reserva.'],
    ['Calefón a gas 18L', ['calefon 18 litros', 'calefon grande'], 'unidad', 'Calefón de 18 litros para casas con dos o más baños: da agua caliente a varios puntos a la vez sin enfriarse.'],
    ['Caño gas epoxi 50mm', ['cano epoxi 50', 'cano gas 50'], 'barra', 'Caño de polietileno con capa epoxi para líneas principales de gas. Para instalaciones que alimentan varios artefactos.'],
    ['Casucha para tanque de gas', ['casucha gas', 'gabinete tanque'], 'unidad', 'Gabinete ventilado que protege el tanque del sol, la lluvia y las manos ajenas, cumpliendo la norma de instalación.'],
    ['Codo gas epoxi 20mm', ['codo epoxi 20', 'codo gas 20'], 'unidad', 'Curva de 90 grados para caño de gas de 20 milímetros: se termofusiona o se rosquea según la línea.'],
    ['Codo gas epoxi 32mm', ['codo epoxi 32', 'codo gas 32'], 'unidad', 'Codo para línea de gas de 32 milímetros, la medida de instalaciones con varios artefactos o distancias largas.'],
    ['Codo gas epoxi 40mm', ['codo epoxi 40', 'codo gas 40'], 'unidad', 'Fitting de 40 milímetros para la columna principal de gas de un edificio o un comercio.'],
    ['Codo 45° gas epoxi 25mm', ['codo 45 gas', 'codo epoxi 45'], 'unidad', 'Curva de 45 grados para caños de gas: permite esquivar columnas y esquinas sin hacer dos codos seguidos.'],
    ['Estufa de gas 3 llamas vidrio', ['estufa vidrio', 'estufa 3 llamas'], 'unidad', 'Estufa decorativa con frente de vidrio templado y tres quemadores: calienta como tiro balanceado y queda bien a la vista.'],
    ['Garrafa de gas 10kg', ['tanque 10kg', 'garrafa 10'], 'unidad', 'Envase de gas licuado de 10 kilos para cocinas de casas y departamentos. Se conecta con regulador y manguera homologada.'],
    ['Hogar leñero de chapa', ['hogar a lena', 'fogonero', 'hogar chapa'], 'unidad', 'Estufa a leña cerrada de chapa negra con puerta de vidrio: calienta mucho y poca leña, con salida de humo al exterior.'],
    ['Horno pizzero a gas', ['horno pizzero', 'horno profesional gas'], 'unidad', 'Horno de gas de alta temperatura para pizza, pan y empanadas: llega a 400 grados y reparte el calor parejo.'],
    ['Kit conversión GLP a natural', ['kit conversion gas', 'inyectores natural'], 'juego', 'Set de inyectores para pasar un artefacto de gas de tubo (GLP) a gas de red natural. Lo cambia el gasista matriculado.'],
    ['Llave de paso gas 1"', ['llave gas 1 pulgada', 'llave esferica gas'], 'unidad', 'Llave de bola para la entrada principal de gas de la casa. De cierre firme y palanca que no se mueve sola.'],
    ['Manguera gas 1.5m con terminales', ['manguera gas 1.5', 'manguera con tuercas'], 'unidad', 'Manguera homologada con tuercas fijas en las puntas para conectar estufas y calefactores. Cambiarla cada pocos años salva vidas.'],
    ['Manguera gas reforzada 3m', ['manguera gas 3 metros', 'manguera larga gas'], 'unidad', 'Manguera de gas de tres metros para instalaciones donde el artefacto queda lejos del tomador. Con doble refuerzo textil.'],
    ['Niple epoxi 25mm', ['niple gas epoxi', 'niple 25'], 'unidad', 'Tramo corto roscado de caño epoxi para extender o reparar líneas de gas sin cambiar tramos largos.'],
    ['Pasta sellante roscas gas', ['pasta junta gas', 'sellador gas'], 'pote', 'Pasta blanca que acompaña al teflón en roscas de gas: lubrica al apretar y sella los microespacios que el teflón no cubre.'],
    ['Rejilla ventilación 20x20', ['rejilla ventilacion', 'parrilla ventilacion'], 'unidad', 'Rejilla con malla antipájaros para el hueco de ventilación permanente que exige toda instalación de gas. La vida de la casa depende de que no la tape nadie.'],
    ['Regulador 10kg con manómetro', ['regulador con manometro', 'regulador gas tubo'], 'unidad', 'Regulador para tubo de 10kg con manómetro visible: ves la presión y te enterás cuando el gas se está terminando.'],
    ['Tanque de gas 45kg', ['tanque 45', 'garrafa grande'], 'unidad', 'Tanque grande de gas licuado para casas con calefacción y agua caliente a gas. Rinde meses y lo recarga el camión de la marca.'],
    ['Termotanque a gas 120L', ['termotanque 120 litros', 'termotanque gas grande'], 'unidad', 'Termotanque de gas de 120 litros con quemador atmosférico: agua caliente abundante para familia grande, sin gasto eléctrico.'],
    ['Termotanque solar 150L', ['termotanque solar', 'calefaccion solar'], 'unidad', 'Sistema solar con colectores y tanque de 150 litros: el sol calienta el agua y el gas solo acompaña en días nublados. La factura baja en serio.'],
    ['Toma exterior de gas con llave', ['toma gas exterior', 'salida gas jardin'], 'unidad', 'Salida de gas estanca con llave para parrillas, hornos de patio y garrafas exteriores. Cierre de bola y tapa protectora.'],
    ['Tee gas epoxi 20mm', ['tee epoxi 20', 'tres gas 20'], 'unidad', 'Derivación en T para líneas de gas de 20 milímetros: de acá sale la rama que alimenta a otro artefacto.'],
    ['Tee gas epoxi 32mm', ['tee epoxi 32', 'tres gas 32'], 'unidad', 'Derivación para línea de gas de 32 milímetros, típica de instalaciones con estufas y calefacción juntas.'],
    ['Tubo evacuación calefón 60cm', ['tubo evacuacion 60', 'salida humo 60'], 'unidad', 'Tramo de caño evacuador de gases de 60 centímetros para calefones y termotanques. Los gases quemados van afuera, siempre.'],
    ['Tubo evacuación calefón 120cm', ['tubo evacuacion 120', 'salida humo 120'], 'unidad', 'Tramo de un metro para llevar la evacuación del artefacto hasta el exterior cuando el techo queda lejos. Se une con abrazadera.'],
    ['Cruce gas epoxi 25mm', ['cruce epoxi', 'cruz gas 25'], 'unidad', 'Pieza de cuatro bocas para cruces de líneas de gas donde dos ramas se cruzan. Menos codos, menos pérdidas.'],
    ['Caño gas epoxi 63mm', ['cano epoxi 63', 'cano gas 63'], 'barra', 'Caño de sesenta y tres milímetros para líneas maestras de gas de edificios y comercios.'],
    ['Manguera gas 5m', ['manguera gas 5 metros', 'manguera larga'], 'unidad', 'Manguera homologada de cinco metros para instalaciones donde el tubo queda lejos del artefacto.'],
    ['Garrafa de gas 15kg', ['tanque 15kg', 'garrafa 15'], 'unidad', 'Envase intermedio de quince kilos para casas de consumo medio: rinde el doble que la de 10 sin cambiar el regulador.'],
    ['Tomador de gas simple', ['tomador gas', 'toma manguera gas'], 'unidad', 'Toma única para conectar una manguera al caño de gas: el arranque de toda instalación doméstica.'],
  ],

  electricistas: [
    ['Antena TV interior', ['antena television', 'antena de mesa'], 'unidad', 'Antena plana para televisor con ganancia alta: capta señal de aire sin instalación en el techo. Viene con cable y conector.'],
    ['Bornera de pared', ['bornera', 'conector pared'], 'unidad', 'Regla con bornes a tornillo para empalmar cables de forma prolija y segura dentro de la caja. Nada de vueltas con cinta.'],
    ['Buscapolos digital', ['tester tomas', 'chequeador tomas'], 'unidad', 'Aparatito que se enchufa y te dice si la toma está bien cableada, si falta tierra o si está invertida. Cuesta poco y evita sustos.'],
    ['Cable prensado bipolar 2x1', ['cable prensado 2x1', 'cable bipolar'], 'metro', 'Cable plano de dos conductores para luminarias y artefactos livianos. Es el cable del velador y del aplique de pared.'],
    ['Cable prensado bipolar 2x2.5', ['cable prensado 2.5', 'cable plano 2.5'], 'metro', 'Cable plano reforzado para zapatillas, extensiones y artefactos de más consumo. No se calienta si le respetás el amperaje.'],
    ['Cable prensado tripolar 3x2.5', ['cable tripolar 2.5', 'cable con tierra'], 'metro', 'Cable plano de tres conductores con tierra para estufas, hornos eléctricos y equipos con carcasa metálica. La tierra salva vidas.'],
    ['Cable subsuelo 2x2.5', ['cable subterraneo', 'cable para enterrar'], 'metro', 'Cable con aislación reforzada para enterrar directamente: alimenta portones, bombas y luminarias de jardín sin cañería.'],
    ['Cable unipolar 16mm x100m', ['cable 16 mm', 'unipolar 16'], 'rollo', 'Cable de sección grande para entradas de medidor y alimentadores de tablero. Lo usa el electricista en la acometida.'],
    ['Caja octogonal superficial', ['caja octogonal superf', 'caja de paso superficie'], 'unidad', 'Caja de paso plástica que va montada en la pared: empalmes, derivaciones y soporte de portalámparas sin picar.'],
    ['Conector rápido x10', ['conector wago', 'conector rapido'], 'paquete', 'Conectores de palanca que unen cables sin soldar ni tornillos: levantás la palanca, metés el cable y listo. Imposible de aflojar.'],
    ['Curva 90° corrugado', ['curva corrugado', 'codo corrugado'], 'unidad', 'Accesorio flexible que acompaña al caño corrugado en las esquinas: el cable entra y sale sin forzarse.'],
    ['Diferencial 2x25mA', ['diferencial 25 ma', 'disyuntor 2x25'], 'unidad', 'Interruptor que corta la corriente en milisegundos si detecta una fuga mínima. Es el que salva cuando alguien toca un cable pelado.'],
    ['Ficha macho 25A', ['ficha 25 amperios', 'enchufe industrial macho'], 'unidad', 'Clavija industrial de 25 amperios para equipos de mucho consumo: soldadoras, motores y hornos. Rosca antitracción.'],
    ['Gabinete tablero exterior 24 módulos', ['gabinete exterior', 'tablero ip65'], 'unidad', 'Caja estanca con puerta transparente para montar el tablero en el exterior o en lugares con humedad. Con cierres y prensacables.'],
    ['Llave bipolar 2x16', ['llave doble polo', 'llave bipolar'], 'unidad', 'Llave que corta fase y neutro a la vez: obligatoria para termotanques, estufas y artefactos fijos de consumo.'],
    ['Llave conmutada simple', ['llave intermedia', 'llave escalera'], 'unidad', 'Llave que permite prender y apagar una luz desde tres lugares cuando se combina con conmutadas. La escalera de dos plantas la pide siempre.'],
    ['Peine de conexión', ['peine tablero', 'peine termicas'], 'unidad', 'Barra preformada que alimenta en bloque todas las térmicas del tablero: reemplaza los puentes de cable y queda prolijo y seguro.'],
    ['Pinza amperométrica', ['pinza amperometrica', 'pinza voltiamperometrica'], 'unidad', 'Pinza que mide la corriente sin cortar el cable: la abrazás y el display te dice cuántos amperios circulan. Imprescindible para diagnosticar.'],
    ['Portalámparas E27 cerámico', ['portalampara', 'portalamparas ceramico'], 'unidad', 'Soporte cerámico para lámparas de rosca grande: aguanta calor alto en talleres, galpones y baños.'],
    ['Precinto nylon x100', ['precintos nylon', 'fajas plasticas'], 'caja', 'Fajitas plásticas de cierre irreversible para ordenar cables y fijarlos al corrugado. Cualquier electricista las usa al montón.'],
    ['Termica unipolar 10A', ['termica 10 amperios', 'llave termica 10'], 'unidad', 'Térmica de un módulo para circuitos livianos: iluminación y veladores. La chiquita de la familia, pero igual de necesaria.'],
    ['Termica unipolar 16A', ['termica 16 amperios', 'llave termica 16'], 'unidad', 'Térmica para circuitos de tomas de uso general. Salta antes de que el cable se caliente, y eso es justo lo que buscás.'],
    ['Termica unipolar 20A', ['termica 20 amperios', 'llave termica 20'], 'unidad', 'Térmica para circuitos de consumo mediano: aires chicos, estufas eléctricas de ambiente.'],
    ['Termica bipolar 10A', ['termica 2x10', 'termica bipolar 10'], 'unidad', 'Térmica de dos polos para circuitos que exigen corte simultáneo de fase y neutro.'],
    ['Termica bipolar 20A', ['termica 2x20', 'termica bipolar 20'], 'unidad', 'Térmica de dos polos de 20 amperios para aires de 3000 y estufas eléctricas de ambiente.'],
    ['Termica tetrapolar 40A', ['termica 4x40', 'termica tetrafasica'], 'unidad', 'Térmica de cuatro polos para tableros trifásicos: protege la entrada completa de una casa grande o un taller.'],
    ['Timbre inalámbrico con melodías', ['timbre inalambrico', 'timbre sin cable'], 'juego', 'Timbre a pila con receptor enchufable: suena en cualquier habitación sin tirar cables ni picar paredes.'],
    ['Toma corriente triple con llave', ['toma triple con llave', 'toma 3 salidas'], 'unidad', 'Toma de pared con tres bocas y llave de corte: ideal para el escritorio y el living donde se enchufa todo junto.'],
    ['Toma industrial 25A', ['toma 25 amperios', 'toma industrial'], 'unidad', 'Receptáculo reforzado de 25 amperios con traba de rosca para equipos de taller y máquinas. Aguanta consumo y vibración.'],
    ['Terminal para cable x20', ['terminales cable', 'bornes aislados'], 'paquete', 'Bornes aislados que se pinzan en la punta del cable para atornillar prolijo y sin pelar hilos. Kit de electricista básico.'],
    ['Timer digital enchufe', ['temporizador digital', 'timer de enchufe'], 'unidad', 'Enchufe con horario programable: prende y apaga luces, filtros de pileta o estufas a la hora que quieras. Ahorra y automatiza.'],
    ['Videoportero con pantalla', ['video portero', 'videportero hd'], 'juego', 'Portero con cámara y pantalla de color: ves quién toca antes de abrir, hablás y hasta le sacás foto al visitante.'],
    ['Cable U-1000 3x10mm', ['cable 3x10', 'cable blindado 10'], 'metro', 'Cable de tres conductores de diez milímetros para alimentadores de tablero con cargas grandes: cocina más aire juntas.'],
    ['Térmica tetrapolar 63A', ['termica 4x63', 'termica tetra 63'], 'unidad', 'Térmica de cuatro polos de sesenta y tres amperios para entradas trifásicas de casas y talleres.'],
    ['Caja 4x4 embutir', ['caja cuatro por cuatro', 'caja embutir grande'], 'unidad', 'Caja profunda para tomas dobles, controles y puntos donde se necesita lugar para los cables.'],
    ['Zapatilla con USB 3 tomas', ['zapatilla usb', 'zapatilla cargador'], 'unidad', 'Zapatilla con tomas más puertos USB integrados: cargás el celular sin el cargador de pared ocupando una boca.'],
    ['Cable unipolar 0.75mm x100m', ['cable 0.75', 'unipolar fino'], 'rollo', 'Cable fino para circuitos de timbre, portero y señalización: baja tensión, instalación prolija.'],
    ['Lámpara LED 18W E27', ['led 18w', 'lampara led 18'], 'unidad', 'LED de dieciocho watts para living y cocina: luz plena con el consumo de una vieja de 100.'],
  ],

  albanileria: [
    ['Adhesivo para bloques', ['pegamento ladrillos', 'adhesivo bloques'], 'bolsa', 'Adhesivo cementicio en polvo para pegar bloques de hormigón y ladrillos sin mortero grueso: muros prolijos, rápidos y con menos junta.'],
    ['Alambre recocido 17', ['alambre negro', 'alambre recocido'], 'kg', 'Alambre negro blando para atar hierro de armaduras, colgar plomadas y mil cosas en la obra. Se dobla con la mano.'],
    ['Balde plástico 20L', ['balde 20 litros', 'balde obra'], 'unidad', 'Balde reforzado con asa metálica: para agua, mezcla, escombros o lavar herramientas. El caddie del albañil.'],
    ['Boquillero de mortero', ['boquillero', 'bolsa boquillero'], 'unidad', 'Bolsa cónica con boquilla para rellenar juntas de ladrillos, piedras y adoquines con mortero fluido. Como una manga pastelera de obra.'],
    ['Cal hidratada 5kg', ['cal 5 kilos', 'cal bolsa chica'], 'bolsa', 'Bolsa chica de cal para revoques finos y mezclas artesanales: plasticidad al mortero y blanco natural para pintar muros.'],
    ['Cemento Portland 25kg', ['cemento bolsa chica', 'cemento 25'], 'bolsa', 'Bolsa de 25 kilos para trabajos chicos: un pisito, arreglos de vereda, bases de lavarropas. Se termina antes de que se humedezca.'],
    ['Cemento de fragua rápida 5kg', ['cemento rapido', 'cement fragua corto'], 'bolsa', 'Cemento de endurecimiento en minutos para tapar pérdidas, anclar perfiles y arreglos urgentes que no pueden esperar.'],
    ['Cornisa de yeso 2m', ['cornisa', 'moldura techo'], 'unidad', 'Moldura de yeso para el encuentro entre pared y techo: da altura visual y el toque de terminación elegante del living.'],
    ['Hilo nylon para hilada', ['hilo albañil', 'hilo nylon'], 'rollo', 'Hilo nylon que se tensa entre las esquinas para levantar muros parejos y a plomo. Sin hilo, la pared baila.'],
    ['Hormigonera 120L', ['mezcladora 120', 'hormigonera electrica'], 'unidad', 'Mezcladora eléctrica de 120 litros con motor y ruedas: prepara hormigón y mortero sin martirizar la espalda. Alquilable o comprable para obras medianas.'],
    ['Hormigón premix H-21', ['hormigon premezclado', 'premix'], 'bolsa', 'Mezcla lista de cemento, arena y piedra: sumás agua y tenés hormigón dosificado correcto para bases y pavimentos chicos.'],
    ['Huinchas plásticas x10', ['huincha albañil', 'flejes'], 'paquete', 'Tiras plásticas flexibles para tensionar y sostener el hilo de hilada en las esquinas. Baratas y eternas.'],
    ['Junquillo esquinero PVC 2.5m', ['junquillo pvc', 'esquinero pvc'], 'unidad', 'Perfilete plástico que se embute en las esquinas del revoque: garantiza aristas rectas y las protege de los golpes.'],
    ['Ladrillo hueco 12cm', ['ladrillo 12', 'bloque hueco 12'], 'unidad', 'Ladrillo hueco de doce centímetros para muros de división con buen aislamiento y poco peso. El estándar de las medianeras.'],
    ['Ladrillo de vidrio 19x19', ['ladrillo vidrio', 'bloque vidrio'], 'unidad', 'Bloque translúcido de vidrio para muros que dejan pasar la luz: baños, oficinas y cocinas con privacidad sin oscuridad.'],
    ['Laja basáltica m²', ['laja', 'piedra laja'], 'm²', 'Piedra partida en lajas irregulares para pisos de galería, frentes y caminos de jardín. Rusticidad natural que no pasa de moda.'],
    ['Llana dentada 30cm', ['llana dentada', 'peine para adhesivo'], 'unidad', 'Llana con dientes para extender adhesivo cerámico en camas parejas: el tamaño de diente define cuánta pasta queda atrás de la pieza.'],
    ['Llana de acero 28cm', ['llana de acero', 'llana albañil'], 'unidad', 'Llana rígida para revoques finos y enduido: superficie lisa como un espejo si la mano está afinada.'],
    ['Mortero de cemento 25kg', ['mortero', 'mezcla cemento'], 'bolsa', 'Mezcla seca de cemento y arena dosificada: solo agregás agua para pegar ladrillos, rellenar y revoques intermedios.'],
    ['Regla de aluminio 2m', ['regla albañil', 'regla enrasar'], 'unidad', 'Regla rígida de aluminio para enrasar revoques, verificar niveles y controlar planitud de pisos. Larga, recta y eterna.'],
    ['Retaco líquido 5L', ['retaco', 'endurecedor piso'], 'litro', 'Líquido cementicio que se mezcla con agua y se aplica sobre pisos: endurece, sella poros y evita el polvo del contrapiso.'],
    ['Revoque grueso 25kg', ['revoque grueso', 'bolsa revoco'], 'bolsa', 'Mezcla lista para la capa gruesa del revoque: corrige la planitud del muro antes del fino. La base de toda pared bien terminada.'],
    ['Tela fibra de vidrio 1m', ['tela fibra', 'malla fibra vidrio'], 'metro', 'Malla de tela de vidrio para reforzar juntas, fisuras y revoques finos: reparte la tensión y la fisura no vuelve a abrirse.'],
    ['Yeso cerámica 30kg', ['yeso ceramico', 'yeso para cerámica'], 'bolsa', 'Yeso especial para juntas de cerámicos y contrapisos livianos: fragua controlada y acabado duro para el taller del colocador.'],
    ['Yeso proyectado 30kg', ['yeso proyectado', 'yeso maquina'], 'bolsa', 'Yeso de grano fino para aplicación con máquina proyectora: techos y muros grandes terminados en horas en vez de días.'],
    ['Adoquín hormigón m²', ['adoquin', 'bloque intertrabado'], 'm²', 'Baldosas de hormigón intertrabadas para veredas y cocheras: aguantan autos y se levantan para reparar el caño de abajo.'],
    ['Arena lavada m³', ['arena lavada', 'arena de rio'], 'm³', 'Arena de río lavada sin arcilla para hormigones y revoques de calidad. Libre de barro: la mezcla rinde y no se agrieta.'],
    ['Escuadra de esquina 90°', ['escuadra esquina', 'cuadrante 90'], 'unidad', 'Molde metálico en escuadra para ejecutar esquinas de muros y columnas perfectas a 90 grados. Nivel de carpintero en el albañil.'],
    ['Mortero refractario 20kg', ['mortero refractario', 'mezcla horno'], 'bolsa', 'Mortero especial que aguanta altas temperaturas para asentar ladrillos refractarios en parrillas, hornos y salamandras.'],
    ['Desmoldante para encofrado 5L', ['desmoldante', 'aceite encofrado'], 'bidón', 'Líquido que se aplica a la madera del encofrado para que el hormigón no se pegue: el desmolde sale limpio y la vajilla del encofrado vive más.'],
    ['Bloque de hormigón 12x19x33', ['bloque 12', 'bloque hormigon 12'], 'unidad', 'Bloque de hormigón de doce centímetros para muros de cierre: más rápido que el ladrillo, menos juntas, buen aislamiento.'],
    ['Hierro cemento 25mm x12m', ['hierro 25', 'acero 25'], 'unidad', 'Barra de veinticinco milímetros para columnas y vigas de alta exigencia estructural.'],
    ['Arcilla común 40kg', ['arcilla', 'barro bolsa'], 'bolsa', 'Bolsa de arcilla para mezclas tradicionales de barro, hornos y revoques rústicos.'],
  ],

  durlock: [
    ['Adhesivo montaje placas 750g', ['adhesivo placas', 'pegamento durlock'], 'unidad', 'Adhesivo en cartucho para pegar placas de yeso y cornisas directamente al muro sin perfil: ahorra metros y deja menos polvo.'],
    ['Aleta de derivación durlock', ['aleta durlock', 'aleta derivacion'], 'unidad', 'Perfilete en T que se usa para empalmar un tabique nuevo contra uno existente sin abrir las juntas del viejo.'],
    ['Anclaje de derivación 30x20', ['anclaje durlock', 'marco derivacion'], 'unidad', 'Marco de chapa galvanizada que sostiene el extremo de un tabique derivado. Chiquito pero clave para que no se mueva.'],
    ['Barra de refuerzo junta', ['barra junta durlock', 'refuerzo placas'], 'unidad', 'Lámina perforada que se embebe en la masilla sobre cada junta: refuerza por dentro lo que la cinta reforza por fuera.'],
    ['Banda perforada 30x30', ['banda perforada', 'olla 30x30'], 'barra', 'Cinta metálica con agujeritos que se dobla y atornilla para fijar soleras a cielorrasos y anclar perfiles donde no llega el tornillo.'],
    ['Champas 6x3/8 x100', ['champas', 'tornillo chapa 6'], 'caja', 'Tornillos autoperforantes cortos para fijar perfiles a soleras y a structures livianos. El tornillo de jerarquía menor pero más usado.'],
    ['Clavo solera 2.1/2 x1kg', ['clavo solera', 'clavos durlock'], 'kg', 'Clavos largos para fijar la solera al cielorraso o al entrepiso: son la ancla de todo el tabique.'],
    ['Colgador cielorraso x50', ['colgador techo', 'hanger durlock'], 'paquete', 'Anclajes expansivos que se clavan en el entrepiso y sostienen el alambre del cielorraso suspendido. Cincuenta a la vez, trabajo rápido.'],
    ['Cupla 6x1" x100', ['cuplas 6x1', 'tornillo cupla'], 'caja', 'Tornillos autoperforantes de una pulgada para placas de 12.7 sobre perfil: el largo justo que no atraviesa el caño del otro lado.'],
    ['Cupla 6x3/4" x100', ['cuplas 6x3/4', 'tornillo placas 9.5'], 'caja', 'Tornillos de tres cuartos para placas de 9.5 milímetros: cielorrasos y tabiques livianos.'],
    ['Cuchilla trapezoidal x10', ['cuchilla durlock', 'hoja trapezoidal'], 'paquete', 'Hojas de repuesto para cutter con forma trapezoidal: cortan placa de yeso limpia y profunda.'],
    ['Dowel expansivo x50', ['dowel durlock', 'taco cielorraso'], 'paquete', 'Anclajes metálicos de expansión para colgar cargas medianas del entrepiso: soportes de cielorraso y luminarias.'],
    ['Felpa de junta acústica', ['felpa junta', 'cinta acustica junta'], 'rollo', 'Cinta de espuma que se coloca entre solera y estructura para desacoplar el tabique: mejora el aislamiento de ruido aéreo.'],
    ['Junquillo durlock 3m', ['junquillo remate', 'cantonera durlock'], 'unidad', 'Moldura liviana para rematar encuentros entre placas y techos, reemplaza al guardapolvo en cielorrasos modernos.'],
    ['Masilla elástica juntas 1kg', ['masilla elastica', 'sellador junta'], 'unidad', 'Masilla flexible para juntas de dilatación entre placas y marcos: se mueve con el edificio y no se agrieta como el enduido duro.'],
    ['Ménsula suspendida durlock', ['mensula durlock', 'mensula cielorraso'], 'unidad', 'Soporte metálico regulable que cuelga el perfil del entrepiso en cielorrasos suspendidos: nivelas girando la tuerca y listo.'],
    ['Perfil durlock 70mm', ['perfil 70', 'cano durlock 70'], 'barra', 'Perfil galvanizado de setenta milímetros para tabiques de mayor espesor y mejor aislamiento acústico que el de 70 clásico.'],
    ['Perfil durlock 100mm', ['perfil 100', 'cano durlock 100'], 'barra', 'Perfil de cien milímetros para tabiques altos o con cañerías de gran diámetro. Toda la instalación cabe adentro.'],
    ['Placa anti-impacto', ['placa antiimpacto', 'placa amarilla'], 'placa', 'Placa de yeso de alta dureza para paredes que reciben golpes: hall de entrada, colegios, pasillos. Resiste el carrito y la pelota.'],
    ['Placa cementicia 8mm', ['placa cementicia', 'fibrocemento 8'], 'placa', 'Placa de cemento sobre malla para zonas húmedas: mamparas, revestimientos exteriores y asientos de cerámico en duchas.'],
    ['Placa RF 15mm', ['placa resistencia fuego 15', 'placa rf gruesa'], 'placa', 'Placa de yeso reforzada con fibras de quince milímetros: resistencia al fuego extendida para cocheras, talleres y compartimientos.'],
    ['Plato de luz embutir durlock', ['plato luz', 'roseta embutir'], 'unidad', 'Caja redonda con orejas para instalar llaves y tomas en tabiques de placa. Se fija desde atrás con tornillo de expansión.'],
    ['Solera durlock 75mm', ['solera 75', 'canal durlock 75'], 'barra', 'Canal en U de setenta y cinco milímetros que acompaña al perfil 70: va arriba y abajo cerrando la estructura.'],
    ['Solera durlock 100mm', ['solera 100', 'canal durlock 100'], 'barra', 'Solera para perfiles de cien milímetros: tabiques gruesos, montantes de edificios y tabiques de cocina con ductos.'],
    ['Tijera suspendida cielorraso', ['tijera cielorraso', 'perfil tijera'], 'unidad', 'Perfil preformado que arma la retícula del cielorraso suspendido sin cortar ni doblar nada: montás la trama en la mitad del tiempo.'],
    ['Tornillo autoperforante 6x1.1/4"', ['autoperforante largo', 'cupla 6x1 1/4'], 'caja', 'Tornillos largos para fijar placas dobles o componentes a perfiles profundos. La medida cuando la de una pulgada no alcanza.'],
    ['Tornillo autoperforante 8x1"', ['autoperforante 8', 'punta broca 8x1'], 'caja', 'Tornillo grueso con punta broca que taladra chapa gruesa sin previo perforado: estructuras de metalcon y fijaciones de solera a acero.'],
    ['Tornillo autoperforante 8x2"', ['autoperforante 8x2', 'tornillo estructura'], 'caja', 'Tornillo de dos pulgadas para unir perfiles gruesos entre sí y anclar ménsulas a estructuras metálicas.'],
    ['Tornillo punta aguja 6x1"', ['punta aguja 6x1', 'tornillo durlock 1'], 'caja', 'Tornillo de punta afilada para placas de yeso sobre perfil de chapa liviana: entra rápido y no rompe el papel de la placa.'],
    ['Tornillo punta broca 8x1.1/2"', ['punta broca 8x1.5', 'autoperforante chapa'], 'caja', 'Tornillo con broca integrada para fijar soleras a losas de hormigón con tarugo o directamente a perfiles gruesos.'],
    ['Tira LED para durlock', ['led cielorraso', 'tira led embutir'], 'metro', 'Tira LED de bajo perfil para perlines de cielorraso suspendido: luz indirecta que reemplaza a la lámpara central en living y comedor.'],
    ['Bujes para perfil', ['buje perfil', 'anclaje buje'], 'paquete', 'Piezas que permiten fijar perfiles a muros y columnas de hormigón donde no se puede atornillar directo.'],
    ['Curva de cielorraso', ['curva durlock', 'perfil curvo'], 'unidad', 'Perfil flexible precurvado para cielorrasos con diseño ondulado o caídas suaves sobre mesadas y camas.'],
    ['Tornillo punta aguja 6x2"', ['punta aguja 6x2', 'tornillo largo durlock'], 'caja', 'Tornillo de dos pulgadas para placas dobles y fijaciones donde el perfil queda profundo.'],
  ],
}
