// Expansión 2 del catálogo HomIA — parte B
// pintura · herreria · herramientas · maderera · carpinteria
// Formato: [nombre, [aliases], unidad, descripción natural]
export const CATALOG_EXP2_B = {
  pintura: [
    ['Acelerador de secado esmalte', ['secante esmalte', 'secante sintetico'], 'frasco', 'Gotas que se agregan al esmalte sintético para que seque en horas en vez de días. Útil cuando hay que dar segunda mano el mismo día.'],
    ['Aditivo antihongos para pintura', ['antihongos pintura', 'aditivo fungicida'], 'frasco', 'Concentrado que se mezcla en el látex para que las paredes húmedas no vuelvan a criar manchas negras. Ideal baños y lavaderos.'],
    ['Barniz marino para piletas', ['barniz piscina', 'esmalte cloro'], 'litro', 'Esmalte especial que resiste el cloro y el agua de piletas y tanques. Se aplica sobre fondo limpio y seco.'],
    ['Barniz zap satinado 4L', ['zap', 'barniz pisos', 'laca pisos'], 'lata', 'Barniz de curado rápido para pisos de madera: resiste el tránsito y queda satinado. Se lava la brocha con agua.'],
    ['Brocha 4"', ['brocha grande', 'brocha ancha'], 'unidad', 'Brocha de cerda natural de cuatro pulgadas para esmalte y latex en superficies grandes. Carga mucha pintura de una sola pasada.'],
    ['Brocha angulosa 2"', ['brocha angular', 'brocha recorte'], 'unidad', 'Brocha de punta al sesgo para recortar bordes, marcos y molduras: llega justo a la esquina sin manchar el otro muro.'],
    ['Cera en pasta para muebles', ['cera pasta', 'cera muebles'], 'pote', 'Cera de abeja en pasta que se aplica con trapo y se lustra: nutre la madera y le da brillo profundo a muebles y puertas.'],
    ['Cera en spray para muebles', ['cera spray', 'cera muebles spray', 'lustra muebles'], 'unidad', 'Aerosol que limpia y pule muebles de madera de una pasada. Perfuma y saca las marcas de dedos del living.'],
    ['Colorante para esmalte sintético', ['colorante sintetico', 'toner esmalte'], 'frasco', 'Pigmento concentrado que se mezcla en el esmalte blanco para lograr cualquier color. Se colorean litros a la vez.'],
    ['Cinta de pintor 18mm', ['cinta pintor fina', 'cinta enmascarar 18'], 'unidad', 'Cinta de papel adhesiva angosta para rayas finas y bordes chicos: marcos, zócalos y detalles que la de 24 no alcanza.'],
    ['Cinta de pintor 36mm', ['cinta pintor ancha', 'cinta enmascarar 36'], 'unidad', 'Cinta ancha para enmascarar zócalos, ventanas y pisos antes de pintar. Sale limpia si la retiras antes de que seque del todo.'],
    ['Decapante en gel', ['decapante', 'quitabarniz', 'sacapintura gel'], 'litro', 'Gel que reblandece pinturas y barnices viejos sin lijar: se aplica, se espera y la capa vieja sale con la espátula.'],
    ['Diluyente sintético 5L', ['diluyente 5 litros', 'thinner'], 'lata', 'Bidón de diluyente para esmaltes, lacas y limpieza de brochas y pistolas. El clásico del taller de pintura.'],
    ['Enduido al agua 1kg', ['enduido chico', 'enduido 1 kilo'], 'pote', 'Pote chico de enduido listo para arreglos: tapa clavos, fisuras y golpes antes de pintar. Seca rápido y se lija suave.'],
    ['Estopilla para vidrios y barnices', ['estopa', 'estopilla'], 'paquete', 'Fibra natural para aplicar barnices y pulir vidrios sin dejar pelusas. La usan los vidrieros de toda la vida.'],
    ['Film para enmascarar 1.4x20m', ['film enmascarar', 'polyfan'], 'unidad', 'Plástico desplegable que protege muebles y pisos al pintar. Se adhiere a la cinta y baja como cortina sobre lo que no se pinta.'],
    ['Juego lijas surtidas x10', ['kit lijas', 'lija surtida'], 'paquete', 'Pack de diez hojas de lija de distintos grados para madera, metal y pared. El kit que soluciona cualquier lijada de la casa.'],
    ['Látex blanco 1L', ['latex chico', 'latex 1 litro'], 'lata', 'Lata chica de látex blanco interior para retoques y habitaciones pequeñas. Rinde más de lo que parece.'],
    ['Látex lavable interior 4L', ['latex lavable', 'latex 4 litros'], 'lata', 'Látex de paredes que se pueden limpiar con trapo húmedo sin que se levante la pintura. Ideal cocinas, pasillos y cuartos de chicos.'],
    ['Látex color 1L', ['latex color chico', 'latex colorido'], 'lata', 'Látex de color en lata chica para paredes de acento: verde, azul, terracota. Cambia el living por menos de lo que cuesta el rodillo.'],
    ['Lija al agua #600', ['lija fina', 'lija pulir'], 'unidad', 'Lija de grano muy fino para pulir esmaltes y madera entre manos de barniz. Deja la superficie como espejo.'],
    ['Lija al agua #1000', ['lija ultrafina', 'lija pulido final'], 'unidad', 'Lija de pulido final para quitar el último salvado del barniz. La usa quien busca terminación profesional.'],
    ['Lija esponja', ['esponja lijadora', 'lija flexible'], 'unidad', 'Bloque de espuma con lija integrada para perfiles, molduras y esquinas: se curva con la mano y no se rompe.'],
    ['Mango extensión para rodillo', ['mango extension', 'palo para roller', 'mango telescopico'], 'unidad', 'Mango telescópico que convierte el rodillo en herramienta para techos y muros altos. Te ahorra la escalera media obra.'],
    ['Pincel 1"', ['pincel chico', 'pincel 1 pulgada'], 'unidad', 'Pincel angosto para detalles, rejillas y bordes chicos. El que usás para pintar radiadores y barandas.'],
    ['Pintura epoxi para pisos 4L', ['pintura epoxi piso', 'esmalte epoxi', 'pintura garage'], 'lata', 'Esmalte epoxi de dos componentes para pisos de cemento: garage, lavadero y taller. Aguanta auto, aceite y lavado con manguera.'],
    ['Pintura para piletas cementicia', ['pintura pileta', 'pintura cementicia pileta'], 'lata', 'Pintura cementicia para piletas de material: sella poros, resiste el cloro y se pinta con rodillo.'],
    ['Pintura pizarra 1L', ['pintura pizarra', 'esmalte pizarra'], 'lata', 'Pintura que convierte cualquier pared en pizarra: se escribe con tiza y se borra con trapo. Los chicos la agradecen.'],
    ['Pistola aerográfica HVLP', ['pistola hvlp', 'pistola aerografica'], 'unidad', 'Pistola de baja presión para acabados finos con compresor: esmalte sin marcas de brocha en muebles y puertas.'],
    ['Pintura en aerosol 400ml', ['spray pintura', 'aerosol pintura'], 'unidad', 'Aerosol de pintura para retoques, bici, hierro y decoración. Colores vivos, seca en minutos.'],
    ['Rejilla de pintor', ['rejilla rodillo', 'secador de roller'], 'unidad', 'Rejilla metálica que va dentro de la bandeja para quitar el exceso de pintura del rodillo. Carga pareja, menos gotas.'],
    ['Rodillo esponja para texturado', ['rodillo textura', 'rodillo esponja'], 'unidad', 'Rodillo de esponja tallada que imprime texturas de estuco y enduido. Crea terminaciones decorativas en una pasada.'],
    ['Rodillo microfibra 18cm', ['rodillo microfibra', 'roller 18'], 'unidad', 'Rodillo de microfibra de baja salpicadura para látex en interiores: suelta la pintura parejo y limpia fácil.'],
    ['Sellador de manchas 4L', ['sellador manchas', 'tapamanchas'], 'lata', 'Fondo que bloquea manchas de humedad, humo y marcadores antes de pintar. Si no lo usás, la mancha atraviesa el látex nuevo.'],
  ],

  herreria: [
    ['Anclaje expansión M8', ['anclaje 8mm', 'tornillo expansivo 8'], 'unidad', 'Anclaje metálico de expansión para fijar a hormigón: rejas, aberturas y estructuras medianas. La chiquita del anclaje profesional.'],
    ['Angulo de acero 1.1/2" x6m', ['angulo hierro 1.5', 'perfil angulo 1.5'], 'barra', 'Barra en L de hierro de seis metros para marcos, rejas y refuerzos. La medida más usada en herrería de obra.'],
    ['Angulo de acero 2" x6m', ['angulo hierro 2', 'perfil angulo 2'], 'barra', 'Angulo grueso para estructuras que cargan peso: portones,.techos y escaleras metálicas.'],
    ['Bisagra de púa 5"', ['bisagra pua', 'bisagra porton pesada'], 'unidad', 'Bisagra de púa con chapa reforzada para portones y tranqueras: gira sobre perno y aguanta el peso sin colgarse.'],
    ['Bisagra de caño 3"', ['bisagra cano', 'bisagra tubular'], 'unidad', 'Bisagra tubular para puertas de chapa y portones livianos: se suelda directo al marco y queda prolija.'],
    ['Bisagra portón 6"', ['bisagra pesada 6', 'bisagra reja'], 'unidad', 'Bisagra de acero reforzada de seis pulgadas para portones de dos hojas y rejas de entrada.'],
    ['Bulón 1/2" x3"', ['bulon media pulgada', 'bulon 1/2'], 'unidad', 'Bulón roscado de media pulgada con tuerca para uniones de estructura: muelle, pérgolas y portones.'],
    ['Bulón 5/8" x3"', ['bulon 5/8', 'bulon grueso'], 'unidad', 'Bulón grueso para estructuras pesadas y anclajes de maquinaria. Con su tuerca y arandela aguanta lo que sea.'],
    ['Cadena eslabón 10mm x2m', ['cadena pesada', 'cadena hierro'], 'unidad', 'Cadena de acero de eslabón grueso para portones, candados de seguridad y traba de maquinaria.'],
    ['Candado de acero 70mm', ['candado grande', 'candado refuerzo'], 'unidad', 'Candado de arco grueso y cuerpo blindado para portones y depósitos. El que de verdad resiste la palanca.'],
    ['Candado de latón 40mm', ['candado chico', 'candado laton'], 'unidad', 'Candado liviano para casilleros, cajas de herramientas y puertas interiores. Chico, confiable y barato.'],
    ['Chapa acanalada galvanizada 1.10x4m', ['chapa acanalada 4m', 'chapa galvanizada 4'], 'placa', 'Placa acanalada galvanizada de cuatro metros para cerramientos, techos y frentes. Se superpone y se clava directo.'],
    ['Terminal de guaya', ['uracan', 'terminal guaya'], 'unidad', 'Terminal de aluminio o acero que fija la punta de la guaya al tensarla: el "huracán" de todo alambrado serio.'],
    ['Tensor para alambrado', ['tensor alambre', 'tensor alambrado'], 'unidad', 'Pieza que estira el alambre o la guaya girando su cuerpo: deja la línea tirante como cuerda de guitarra.'],
    ['Correa C 220x80 x6m', ['correa c', 'perfil correa 220'], 'barra', 'Perfil en C de gran canto para vigas de techos y entrepisos metálicos. La columna vertebral del techo industrial.'],
    ['Disco corte 9"', ['disco 9 pulgadas', 'disco corte grande'], 'unidad', 'Disco de corte para amoladora de nueve pulgadas: corta caños, perfiles y chapas gruesas de una pasada.'],
    ['Espárrago M12 x1m', ['esparrago 12', 'rosca sin fin'], 'barra', 'Barra roscada de doce milímetros para colgar, anclar y unir lo que sea. Con sus tuercas es el multiuso del taller.'],
    ['Gancho de seguridad 10mm', ['gancho seguro', 'mosqueton hierro'], 'unidad', 'Gancho forjado con seguro de resorte para grúas manuales, sogas y cadenas. No se abre solo.'],
    ['Grillete 12mm', ['grillete', 'grillete acero'], 'unidad', 'Grillete de acero forjado para uniones de cadenas y eslingas. Se abre con su perno roscado y aguanta toneladas.'],
    ['Guaya de acero 6mm x50m', ['guaya', 'cable de acero 6'], 'rollo', 'Rollo de cincuenta metros de guaya de acero para tensar portones, tender tendales y armar vallas.'],
    ['Jalador en U de acero', ['jalador u', 'tirador porton'], 'unidad', 'Manijón en U de acero macizo para portones y portones de depósito: agarradera firme que no se dobla.'],
    ['Malla hexagonal galvanizada 1m', ['malla hexagonal', 'gallinero galvanizado'], 'rollo', 'Malla tejida hexagonal para gallineros, protección de plantas y cercos livianos. Se corta con tijera y se arrolla.'],
    ['Malla tejido romboidal 2m', ['tejido romboidal', 'alambre tejido', 'malla perimetral'], 'rollo', 'Malla de alambre tejido en rombos para cercar terrenos y jardines. Con postes y tensores, el cerco de toda la vida.'],
    ['Manguito de rosca 3/4"', ['manguito', 'union roscada'], 'unidad', 'Pieza roscada interna en ambos extremos que une dos caños o llaves del mismo diámetro.'],
    ['Pasador de piso antipalanca', ['traba piso', 'antipalanca', 'pasador piso'], 'unidad', 'Pasador que se clava en el piso y traba la puerta por abajo: refuerzo clásico de puertas de entrada y comercios.'],
    ['Planchuela de acero 1.1/2" x6m', ['planchuela 1.5', 'hierro plano 1.5'], 'barra', 'Barra plana de hierro para marcos de rejas, tirantes y refuerzos. La planchuela de media obra.'],
    ['Planchuela de acero 2" x6m', ['planchuela 2', 'hierro plano 2'], 'barra', 'Planchuela ancha para estructuras que piden más sección: portones pesados y soportes de depósitos.'],
    ['Polea con gancho 100mm', ['polea', 'roldana'], 'unidad', 'Polea de acero con gancho y gancho de fijación para levantar baldes, motores y cargas livianas por la ventana del tapial.'],
    ['Puntilla 4" x1kg', ['clavo sin cabeza', 'puntillas 4'], 'kg', 'Clavos sin cabeza de cuatro pulgadas para fijaciones que quedan a la vista: molduras, machimbres y tapacantos.'],
    ['Remaches de aluminio x100', ['remaches', 'remaches pop'], 'caja', 'Remaches con pistola para unir chapas y perfiles sin soldar: se colocan en segundos y quedan firmes.'],
    ['Soldadura en frío bicomponente', ['epoxi metal', 'soldadura fria'], 'pote', 'Masilla epoxi que se amasa y endurece como el metal: repara caños, cárteres y piezas fundidas sin soldar.'],
    ['Tuerca autofrenante M10', ['tuerca lock', 'contratuerca'], 'unidad', 'Tuerca con inserto de nylon que no se afloja con la vibración: para bulones de maquinaria y estructuras en movimiento.'],
    ['Viga UPN 120 x6m', ['upn 120', 'viga upn'], 'barra', 'Viga en U de doce centímetros de canto para openings, vigas de techo y soportes de entrepiso.'],
    ['Viga IPN 100 x6m', ['ipn 100', 'viga ipn'], 'barra', 'Viga en I de diez centímetros para aperturas grandes y vigas maestras. La clásica del reforzamiento estructural.'],
    ['Barra maciza 20mm x6m', ['barra maciza', 'hierro macizo 20'], 'barra', 'Barra de acero maciza de veinte milímetros para ejes, pernos y piezas torneadas. Acero de verdad.'],
    ['Tubo estructural 20x20 x6m', ['tubo 20x20', 'cano estructural 20'], 'barra', 'Tubo cuadrado fino para estructuras livianas: mesas de taller, rejas finas y soportes de placa.'],
    ['Tubo estructural 60x40 x6m', ['tubo 60x40', 'cano estructural 60'], 'barra', 'Tubo rectangular robusto para portones, estructuras de techos y marcos pesados.'],
  ],

  herramientas: [
    ['Alargue exterior 20m', ['prolongador 20 metros', 'alargue reforzado'], 'unidad', 'Cordón prolongador reforzado de veinte metros con protección IP44: para la hidrolavadora, la bordeadora y el taller del patio.'],
    ['Amoladora angular 5"', ['amoladora 5 pulgadas', 'amoladora mediana'], 'unidad', 'Amoladora intermedia entre la de 4.5 y la de 7: potencia para metales con peso manejable.'],
    ['Broca HSS 5mm', ['broca metal 5', 'broca hss 5'], 'unidad', 'Broca de acero rápido de cinco milímetros para metales, plásticos y madera. Aguantadora para el taladro de casa.'],
    ['Broca widia 6mm', ['broca pared 6', 'broca concreto 6'], 'unidad', 'Broca con punta de widia para perforar ladrillo, hormigón y cerámico. La del sostén de la repisa nueva.'],
    ['Caja de herramientas plástica', ['cajita herramientas', 'maletin herramientas'], 'unidad', 'Caja con bandeja interna y cierre firme para llevar herramientas de un lado a otro sin que se mezclen.'],
    ['Cizalla corta chapas', ['tijera corta chapa', 'cizalla manual'], 'unidad', 'Tijera de palanca que corta chapa galvanizada y aluminio con esfuerzo mínimo. Cortes limpios sin amoladora.'],
    ['Corta cerámica manual', ['cortadora ceramica', 'cortadora de cerámicos'], 'unidad', 'Cortadora manual con riel y rueda de widia para cerámicos y porcelanatos: corte recto sin electricidad ni polvo.'],
    ['Cortador de vidrio', ['cortavidrio', 'cortador vidrio'], 'unidad', 'Herramienta con rueda de carburo para cortar vidrio: se raya, se apoya en el borde y el corte abre limpio.'],
    ['Corta tubos PVC', ['cortador tubo', 'cortatubos'], 'unidad', 'Pinza de corte con rueda para caños de PVC y termofusión: corte perpendicular y sin rebaba en un giro.'],
    ['Cuchilla cutter con hojas', ['cutter', 'cuchilla industrial'], 'unidad', 'Cutter industrial con cuchilla trapezoidal quebrable: para placas, gomas, cartón y mil trabajos del taller.'],
    ['Discos de lija para orbital x10', ['hojas lija orbital', 'discos lija orbital'], 'paquete', 'Hojas de lija con velcro para lijadora orbital: distintos granos para madera, metal y pintura.'],
    ['Escuadra metálica 50cm', ['escuadra grande', 'escuadra 50'], 'unidad', 'Escuadra de cincuenta centímetros para marcar cortes y verificar ángulos rectos en carpintería y chapa.'],
    ['Formón de madera 25mm', ['formon', 'buril madera'], 'unidad', 'Formón de acero al cromo de veinticinco milímetros para desbaste y ajuste de madera: bisagras, cerraduras y molduras.'],
    ['Gato hidráulico 2 toneladas', ['gato hidraulico', 'gato auto'], 'unidad', 'Gato de botella de dos toneladas para levantar autos, muebles y estructuras. El salvavidas del garaje.'],
    ['Juego llaves Allen x9', ['llaves allen', 'juego allen'], 'juego', 'Set de nueve llaves hexagonales de 1.5 a 10 milímetros para muebles, bicis y maquinaria. Siempre falta una: acá están todas.'],
    ['Llave cruz para canillas', ['llave cruz', 'llave canilla'], 'unidad', 'Llave en cruz con boca cuadrada para abrir canillas y tanques viejos cuyos eje se corrió. La rescatista de la plomería.'],
    ['Linterna frontal LED', ['linterna de cabeza', 'frontal led'], 'unidad', 'Linterna con vincha elástica que ilumina donde mirás: deja las dos manos libres para trabajar en lugares oscuros.'],
    ['Martillo de goma', ['mazo goma', 'martillo goma blanco'], 'unidad', 'Martillo de goma blanco para asentar cerámicos, placas y maderas sin marcar la superficie.'],
    ['Mazo de 2kg', ['mazo 2 kilos', 'maceta hierro'], 'unidad', 'Mazo de hierro de dos kilos para demoliciones y hincado de estacas. Golpe seco, resultado garantizado.'],
    ['Mini amoladora 3"', ['amoladora chiquita', 'rotativas air'], 'unidad', 'Mini amoladora de tres pulgadas para trabajos de precisión: pulido, corte fino y desbaste en espacios chicos.'],
    ['Morsa de banco', ['prensa banco', 'morsa de banco'], 'unidad', 'Morsa de fundición para fijar al banco del taller: agarra piezas mientras las limas, taladrás o soldás.'],
    ['Nivel de aluminio 120cm', ['nivel 1.20', 'nivel grande'], 'unidad', 'Nivel rígido de un metro veinte para paredes y pisos largos: esquinas de cocina, duchas y frentes.'],
    ['Nivel 30cm', ['nivel chico', 'nivel de bolsillo'], 'unidad', 'Nivel compacto que vive en el bolsillo del overol: cuadros, repisas y salidas de caño a ras.'],
    ['Palanca de acero', ['pata cabra', 'pie de cabra', 'palanca demolición'], 'unidad', 'Palanca forjada con uñas para despegar pisos, marcos y demoler sin dañar lo que queda.'],
    ['Pelacables', ['pinza peladora', 'pelador cables'], 'unidad', 'Pinza que pela el aislamiento del cable en un apretón: corte limpio, sin cortar hilos, en distintos calibres.'],
    ['Pistola para silicona', ['pistola silicona', 'pistola cartucho'], 'unidad', 'Pistola de palanca para cartuchos de silicona y selladores: aplicación pareja sin dedos embarrados.'],
    ['Pinza de presión (vise grip)', ['vise grip', 'pinza presion'], 'unidad', 'Pinza que se traba y queda apretada sola: sostiene piezas, extrae clavos trancados y reemplaza a la llave que no está.'],
    ['Pinza de punta curva', ['pinza punta curva', 'pinza electricista curva'], 'unidad', 'Pinza de punta curvada para llegar a lugares donde la recta no entra: detrás del tablero, dentro del motor.'],
    ['Hojas para caladora x10', ['hojas caladora', 'hojas sierra caladora'], 'paquete', 'Juego de hojas de repuesto para caladora: madera, metal y plástico, con dientes finos y gruesos.'],
    ['Kit brocas x25', ['juego brocas', 'set brocas'], 'juego', 'Estuche con veinticinco brocas de metal, pared y madera: el kit completo para cualquier taladrada de la casa.'],
    ['Soplete de gas con cartucho', ['soplete propano', 'antorcha gas'], 'unidad', 'Soplete portátil a cartucho para quemar pintura, dorar tubos y encender brasas. Con encendido piezoeléctrico.'],
    ['Tronzadora 14"', ['cortadora metales', 'troncadora'], 'unidad', 'Cortadora de disco para metales de catorce pulgadas: corta perfiles, tubos y barras rectas y rápido. La amiga de todo taller.'],
  ],

  maderera: [
    ['Deck de eucalipto metro', ['deck eucalipto', 'tablon deck eucalipto'], 'metro', 'Lámina de eucalipto tratado para decks exteriores: resiste el sol y la lluvia y envejece con elegancia.'],
    ['Junquillo madera para vidrio', ['junquillo vidrio', 'moldura vidrio'], 'metro', 'Moldura fina que sostiene el vidrio en marcos y vitrinas. Se clava o se pega y tapa el lugar de junta.'],
    ['Moldura corona 4x2', ['moldura corona', 'cornisa madera'], 'metro', 'Moldura superior que corona armarios y paredes: el toque clásico que viste el encuentro con el techo.'],
    ['MDF 6mm 1.83x2.44', ['mdf fino 6', 'mdf 6 milimetros'], 'placa', 'Placa MDF de seis milímetros para fondos de muebles, puertas livianas y decoración. Se corta y se pinta fácil.'],
    ['MDF 9mm 1.83x2.44', ['mdf 9', 'mdf medio'], 'placa', 'MDF de nueve milímetros para cajones, revestimientos y muebles livianos. El intermedio entre el fino y el estructural.'],
    ['MDF hidrófugo 18mm', ['mdf rh', 'mdf humedad'], 'placa', 'Placa MDF con resina repelente de agua para baños y cocinas: el mueble no se hinchas ni se descascara con el vapor.'],
    ['OSB 15mm 1.22x2.44', ['osb 15', 'tablero osb 15'], 'placa', 'Tablero de virutas prensadas de quince milímetros para pisos de entrepiso, techos y encofrados.'],
    ['OSB 18mm 1.22x2.44', ['osb 18', 'tablero osb 18'], 'placa', 'OSB estructural de dieciocho milímetros para pisos que cargan peso y paneles de obra.'],
    ['Pasamanos redondo 2"', ['pasamano', 'baranda redonda'], 'metro', 'Tubo de madera torneada de dos pulgadas para pasamanos de escalera y barandas: agarre firme y liso.'],
    ['Placa dura 3mm', ['fibra dura', 'masisa 3'], 'placa', 'Tablero de fibra dura de tres milímetros para fondos de muebles y cielorrasos económicos.'],
    ['Pino cepillado 1x3 x3m', ['liston pino 1x3', 'tiras pino 1x3'], 'unidad', 'Tira de pino cepillado de una por tres pulgadas para estructuras livianas, estantes y bastidores.'],
    ['Pino cepillado 2x2 x3m', ['tiras pino 2x2', 'liston 2x2'], 'unidad', 'Tira cuadrada de pino para esqueletos de muebles, soportes de cielorraso y marcos livianos.'],
    ['Poste tratado 12x12', ['poste 12x12', 'pilar tratado'], 'unidad', 'Poste de madera impregnada de doce por doce para corrales, pérgolas y estructuras de exterior enterradas.'],
    ['Revestimiento lapacho metro', ['lapacho', 'revestimiento madera dura'], 'metro', 'Lámina de lapacho para revestimientos exteriores: madera dura que resiste el sol sin pintura.'],
    ['Rosetón de madera', ['roseton', 'roseta madera'], 'unidad', 'Pieza torneada que decora el encuentro de la moldura con el techo. El detalle clásico del living tradicional.'],
    ['Tablón algarrobo 3x4', ['algarrobo 3x4', 'madera dura algarrobo'], 'unidad', 'Tablón de algarrobo de tres por cuatro: madera dura para mesas, bancos y piezas que aguantan generaciones.'],
    ['Tablón nogal 2x6', ['nogal 2x6', 'tablon nogal'], 'unidad', 'Tablón de nogal con veta profunda para muebles de terminación fina: mesas ratonas y tablones decorativos.'],
    ['Tablón pino 3x6 x4m', ['tablon 3x6', 'pino 3x6'], 'unidad', 'Tablón grueso de pino de cuatro metros para vigas vistas, mesas rústicas y bancos de jardín.'],
    ['Tabla cedro 1x6', ['cedro 1x6', 'madera cedro'], 'unidad', 'Tabla de cedro de una por seis: aroma inconfundible, ideal para guardas, cajas y revestimientos interiores.'],
    ['Trupán fenólico 4mm', ['trupan fenolico fino', 'fenolico 4'], 'placa', 'Trupán con fenólico de cuatro milímetros para plantillas, relojes y piezas de precisión: superficie dura y lisa.'],
    ['Tirante eucalipto 2x4', ['tirante 2x4', 'eucalipto 2x4'], 'unidad', 'Tirante de eucalipto de dos por cuatro para techos livianos y cielorrasos con vigas medianas.'],
    ['Viga laminada eucalipto 3x9', ['viga laminada', 'viga eucalipto 3x9'], 'unidad', 'Viga de madera laminada de gran canto para techos con luces largas: no se dobla como la madera maciza.'],
    ['Viga para pérgola 4x8', ['viga pergola', 'travesano pergola'], 'unidad', 'Viga de madera dura para pérgolas: canta fuerte, sostiene la sombra y viste el patio.'],
    ['Zanca escalera pino', ['zanca', 'laterales escalera'], 'unidad', 'Pieza dentada que sostiene los escalones de la escalera de madera. Se corta con la sierra y se monta en una tarde.'],
    ['Dowel madera x50', ['tarugos madera', 'clavijas madera'], 'paquete', 'Clavijas cilíndricas para uniones de madera sin tornillo: muebles armados con pegamento y precisión.'],
    ['Pino cepillado 2x8 x3m', ['pino 2x8', 'tablilla pino 2x8'], 'unidad', 'Tabla ancha de pino para estantes profundos, tapas de mesas y bordes de escalones.'],
  ],

  carpinteria: [
    ['Alza de bisagra', ['alza puerta', 'levantador bisagra'], 'unidad', 'Lámina que se coloca entre la bisagra y la puerta para levantarla o nivelarla sin renovar el marco.'],
    ['Bisagra cazoleta 40mm', ['bisagra coccina 40', 'hinge 40'], 'unidad', 'Cazoleta de cuarenta milímetros para puertas de mueble más gruesas: misma lógica que la de 35, más fuerza.'],
    ['Bisagra de cajón con cierre suave', ['bisagra cierre suave', 'hinge soft close'], 'unidad', 'Cazoleta con amortiguación que frena la puerta antes de cerrar: adiós portazos en la cocina.'],
    ['Bisagra para vidrio', ['bisagra cristal', 'bisagra vitrina'], 'unidad', 'Bisagra que aprieta el vidrio con gomas sin perforarlo: puertas de vitrinas y muebles exhibidores.'],
    ['Corredera vidrio 6mm', ['riel vidrio 6', 'guia corrediza vidrio'], 'unidad', 'Riel plástico o metálico para deslizar puertas de vidrio de seis milímetros: muebles y divisores de ambiente.'],
    ['Cerradura cajón con llave', ['cerradura cajon', 'cerradura escritorio'], 'unidad', 'Cerradura chiquita para cajones de escritorio y cómodas: la llave que guarda lo que importa.'],
    ['Cierre magnético para alacenas', ['cierre magnetico', 'traba alacena'], 'unidad', 'Pareja de imán y placa que mantiene la puerta del mueble cerrada sin llave ni pestillo. Silencioso y eterno.'],
    ['Cuñas niveladoras x50', ['cuñas niveladoras', 'cuñitas plásticas'], 'paquete', 'Cuñas plásticas para nivelar muebles y puertas sobre pisos irregulares: se apilan hasta lograr el nivel exacto.'],
    ['Enganche para mesa plegable', ['enganche mesa', 'traba plegable'], 'unidad', 'Herraje que sostiene la pata o el tablero plegado contra el mueble: mesas de jardín y mesadas auxiliares.'],
    ['Estructura placard 1.80m', ['kit estructura placard', 'interior placard'], 'juego', 'Kit con barras, estantes y separadores para armar el interior de un placard de un metro ochenta. Orden por fin.'],
    ['Ganchos para repisas x4', ['soportes repisa', 'ganchos estante'], 'paquete', 'Soportes en L con tornillería para estantes de madera: aguantan libros, plantas y lo que se te ocurra.'],
    ['Herraje para cama 1 plaza', ['herraje cama', 'rinconera cama'], 'juego', 'Kit de esquineros y bulones para armar la estructura de una cama: armás la base con tablas comunes.'],
    ['Manija de ventana', ['tirador ventana', 'manija aluminio'], 'unidad', 'Manija de repuesto para ventanas de aluminio: se cambia con dos tornillos y la ventana vuelve a cerrar firme.'],
    ['Pata plegable para mesa', ['patas mesa plegable', 'pata abatible'], 'unidad', 'Pata metálica con cierre que se esconde bajo la mesada: mesas plegables de laundry y patios chicos.'],
    ['Pistola de cola caliente', ['pistola silicona caliente', 'cola termofusible'], 'unidad', 'Pistola que derrite barras de cola para pegar rápido madera, tela y decoración. La aliada de las manualidades y los arreglos.'],
    ['Barras de cola x10', ['barra cola caliente', 'glue sticks'], 'paquete', 'Repuesto de diez barras para pistola de cola: traslúcidas, de agarre fuerte y secado en segundos.'],
    ['Perfil U para vidrio', ['perfil u', 'canal u vidrio'], 'metro', 'Canal en U de plástico o aluminio que recibe el vidrio en muebles y divisiones: sujeta y decora.'],
    ['Pomo de puerta', ['pomo puerta', 'boton puerta'], 'unidad', 'Pomo esférico de repuesto para puertas interiores: rosca estándar y colocación en minutos.'],
    ['Push to open', ['mecanismo push', 'apertura push'], 'unidad', 'Mecanismo que abre el mueble con un toque: sin tiradores, la cara de la cocina minimalista.'],
    ['Soporte mesa abatible', ['mensula abatible', 'soporte plegable mesa'], 'unidad', 'Ménsula con plegado en dos posiciones para mesas de pared: la mesa aparece cuando la necesitás y desaparece cuando no.'],
    ['Tapa de tornillo blanca x50', ['tapas tornillo', 'taponcitos'], 'paquete', 'Tapitas plásticas que cubren la cabeza de los tornillos de muebles: acabado prolijo sin carpintero.'],
    ['Tirador barra 128mm', ['tirador 128', 'tirador barra cocina'], 'unidad', 'Tirador de barra con separación de 128 milímetros, la medida estándar de la mayoría de las puertas de cocina.'],
    ['Tirador doble cara para vidrio', ['tirador doble', 'manijon vidrio'], 'unidad', 'Manijón que se fija a los dos lados del vidrio con tornillo pasante: para puertas de shower y muebles exhibidores.'],
    ['Tornillo mueble 7x50 x50', ['tornillo euro', 'tornillo mueble 7'], 'caja', 'Tornillos de cabeza amplia para unir tableros de muebles: agarran la madera sin partirla.'],
    ['Tope magnético de pared', ['tope puerta iman', 'freno puerta'], 'unidad', 'Tope con imán que abraza la puerta y la frena antes del golpe contra la pared. Protege el revoque y la puerta.'],
  ],
}
